// Code generated by tools/crwriter; DO NOT EDIT.

package upgradepatches

/*
 * This file is part of the KubeVirt project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2024 Red Hat, Inc.
 *
 */

var hyperConvergedCRDefault = []byte(`{
  "kind": "HyperConverged",
  "apiVersion": "hco.kubevirt.io/v1beta1",
  "metadata": {
    "name": "kubevirt-hyperconverged",
    "creationTimestamp": null
  },
  "spec": {
    "infra": {},
    "workloads": {},
    "featureGates": {
      "downwardMetrics": false,
      "enableCommonBootImageImport": true,
      "deployVmConsoleProxy": false,
      "deployKubeSecondaryDNS": false,
      "disableMDevConfiguration": false,
      "persistentReservation": false,
      "autoResourceLimits": false,
      "alignCPUs": false,
      "enableApplicationAwareQuota": false
    },
    "liveMigrationConfig": {
      "parallelMigrationsPerCluster": 5,
      "parallelOutboundMigrationsPerNode": 2,
      "completionTimeoutPerGiB": 150,
      "progressTimeout": 150,
      "allowAutoConverge": false,
      "allowPostCopy": false
    },
    "certConfig": {
      "ca": {
        "duration": "48h0m0s",
        "renewBefore": "24h0m0s"
      },
      "server": {
        "duration": "24h0m0s",
        "renewBefore": "12h0m0s"
      }
    },
    "workloadUpdateStrategy": {
      "workloadUpdateMethods": [
        "LiveMigrate"
      ],
      "batchEvictionSize": 10,
      "batchEvictionInterval": "1m0s"
    },
    "uninstallStrategy": "BlockUninstallIfWorkloadsExist",
    "virtualMachineOptions": {
      "disableFreePageReporting": false,
      "disableSerialConsoleLog": true
    },
    "higherWorkloadDensity": {
      "memoryOvercommitPercentage": 100
    }
  },
  "status": {}
}
`)
