linters:
  enable:
  - ginkgolinter
  - revive
  - gocognit
  - unparam
linters-settings:
  ginkgolinter:
    forbid-focus-container: true
issues:
  exclude-rules:
  - linters:
    - revive
    source: ". \"github.com/onsi/(ginkgo/v2|gomega)\""
    text: "dot-imports: should not use dot imports"
