language: go
go:
- "1.10.x"
sudo: required
dist: trusty

install:
    - go get github.com/mattn/goveralls
    - go get -v github.com/onsi/ginkgo/ginkgo
    - go get -v github.com/onsi/gomega
    - go get -v -t ./...
    - export PATH=$PATH:$HOME/gopath/bin

services:
- docker

script:
- make build
- make test
- $GOPATH/bin/goveralls -service=travis-ci -coverprofile=pkg/controller/hyperconverged/hyperconverged.coverprofile

# Keeping this around from kubevirt/kubevirt for updating in the future
# deploy:
# - provider: script
#   script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && DOCKER_PREFIX="index.docker.io/kubevirt" DOCKER_TAG="latest" make bazel-push-images
#   skip_cleanup: true
#   on:
#     branch: master
# - provider: script
#   script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && DOCKER_PREFIX="index.docker.io/kubevirt"
#     DOCKER_TAG="$TRAVIS_TAG" QUAY_REPOSITORY="kubevirt" PACKAGE_NAME="kubevirt-operatorhub"
#     sh -c 'make bazel-push-images && make manifests && make olm-push'
#   skip_cleanup: true
#   file:
#   on:
#     tags: true
# - provider: releases
#   skip_cleanup: true
#   api_key:
#     secure: KD1d1EkvX5iY5pvKQbi6Aj6y49XXnQBxBMok9x2d9LVMbmzBQIHoTqUQz2Dv2TSpANshkIrLmR1eT/brCK382cIUVvA6kG8JB2yqAAE2hzJ8u49+CI4iyqpBWw1HCuH/4xPWZUPVBW0Yl9WsW0vencAeKK6cTDm4Z9K3esJf+iZMpJh7ZpK2ESn9d2RZsrpOKJpxYrvt14Wox+8YfqPRCTJoO/Q8vdXbyOrRVpK6daSe11HsmTZZpFzgLWGojpjH05wcENUaokpCIp8Hgx3rJmO9z5iReNG+2QuPCw0QyEIKGAvzlA5KbYFWBUurxz0XsnaovbJ7BKI070arxQKjKRnjSNE3kEValOwMIE8dA835A1nChm85NILQdWvlbexSxPpz0z62SGPjFthUj9VBx/RnUrd1itxWOi6ZW5k6PnWDUoKPr63+fYSAkp6bXO9ELexA19wUfQCicGRBEO3mJ6QvKKbiDAFKWcABlavxlNtFgw1mMPxxWEhKkW0PrCqOVu9fDDzJ48DCD5XHRT8HUVHDeKcscMTW675rlzo3SxTJdqnZSybpbMSmKbxNs0rM8kPXf1RQLsGDg4CC6Daxz255PV5Y/+p0AhZ2hWtfC3c/Ff8wOdDSdCaEcg5tGa/e1kJWAKuIATUGdZsFZUri8ePQcgcXzM4ihANn7gP8Cl4=
#   file_glob: true
#   file:
#   - _out/cmd/virtctl/virtctl-*
#   - _out/manifests/release/kubevirt.yaml
#   - _out/templates/manifests/release/kubevirt.yaml.j2
#   - _out/manifests/release/demo-content.yaml
#   - _out/manifests/release/kubevirt-operator.yaml
#   - _out/manifests/release/kubevirt-cr.yaml
#   - _out/templates/manifests/release/kubevirt-operator.yaml.j2
#   - _out/templates/manifests/release/kubevirt-cr.yaml.j2
#   - _out/manifests/release/olm/kubevirt-operatorsource.yaml
#   - _out/manifests/release/olm/bundle/kubevirtoperator.*.csv.yaml
#   prerelease: true
#   overwrite: true
#   name: $TRAVIS_TAG
#   on:
#     tags: true
#     repo: kubevirt/kubevirt

# env:
#   global:
#   # QUAY_USERNAME
#   - secure:
#   # QUAY_PASSWORD
#   - secure:
#   # DOCKER_PASS
#   - secure:
#   # DOCKER_USER
#   - secure:

