//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * This file is part of the KubeVirt project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2026 Red Hat, Inc.
 *
 */

// Code generated by defaulter-gen. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&HyperConverged{}, func(obj interface{}) { SetObjectDefaults_HyperConverged(obj.(*HyperConverged)) })
	scheme.AddTypeDefaultingFunc(&HyperConvergedList{}, func(obj interface{}) { SetObjectDefaults_HyperConvergedList(obj.(*HyperConvergedList)) })
	return nil
}

func SetObjectDefaults_HyperConverged(in *HyperConverged) {
	if in.Spec.Virtualization.LiveMigrationConfig.ParallelMigrationsPerCluster == nil {
		var ptrVar1 uint32 = 5
		in.Spec.Virtualization.LiveMigrationConfig.ParallelMigrationsPerCluster = &ptrVar1
	}
	if in.Spec.Virtualization.LiveMigrationConfig.ParallelOutboundMigrationsPerNode == nil {
		var ptrVar1 uint32 = 2
		in.Spec.Virtualization.LiveMigrationConfig.ParallelOutboundMigrationsPerNode = &ptrVar1
	}
	if in.Spec.Virtualization.LiveMigrationConfig.CompletionTimeoutPerGiB == nil {
		var ptrVar1 int64 = 150
		in.Spec.Virtualization.LiveMigrationConfig.CompletionTimeoutPerGiB = &ptrVar1
	}
	if in.Spec.Virtualization.LiveMigrationConfig.ProgressTimeout == nil {
		var ptrVar1 int64 = 150
		in.Spec.Virtualization.LiveMigrationConfig.ProgressTimeout = &ptrVar1
	}
	if in.Spec.Virtualization.LiveMigrationConfig.AllowAutoConverge == nil {
		var ptrVar1 bool = false
		in.Spec.Virtualization.LiveMigrationConfig.AllowAutoConverge = &ptrVar1
	}
	if in.Spec.Virtualization.LiveMigrationConfig.AllowPostCopy == nil {
		var ptrVar1 bool = false
		in.Spec.Virtualization.LiveMigrationConfig.AllowPostCopy = &ptrVar1
	}
	if in.Spec.Virtualization.WorkloadUpdateStrategy.WorkloadUpdateMethods == nil {
		if err := json.Unmarshal([]byte(`["LiveMigrate"]`), &in.Spec.Virtualization.WorkloadUpdateStrategy.WorkloadUpdateMethods); err != nil {
			panic(err)
		}
	}
	if in.Spec.Virtualization.WorkloadUpdateStrategy.BatchEvictionSize == nil {
		var ptrVar1 int = 10
		in.Spec.Virtualization.WorkloadUpdateStrategy.BatchEvictionSize = &ptrVar1
	}
	if in.Spec.Virtualization.WorkloadUpdateStrategy.BatchEvictionInterval == nil {
		if err := json.Unmarshal([]byte(`"1m0s"`), &in.Spec.Virtualization.WorkloadUpdateStrategy.BatchEvictionInterval); err != nil {
			panic(err)
		}
	}
	if in.Spec.Virtualization.VirtualMachineOptions == nil {
		if err := json.Unmarshal([]byte(`{"disableFreePageReporting": false, "disableSerialConsoleLog": false}`), &in.Spec.Virtualization.VirtualMachineOptions); err != nil {
			panic(err)
		}
	}
	if in.Spec.Virtualization.VirtualMachineOptions != nil {
		if in.Spec.Virtualization.VirtualMachineOptions.DisableFreePageReporting == nil {
			var ptrVar1 bool = false
			in.Spec.Virtualization.VirtualMachineOptions.DisableFreePageReporting = &ptrVar1
		}
		if in.Spec.Virtualization.VirtualMachineOptions.DisableSerialConsoleLog == nil {
			var ptrVar1 bool = false
			in.Spec.Virtualization.VirtualMachineOptions.DisableSerialConsoleLog = &ptrVar1
		}
	}
	if in.Spec.Virtualization.HigherWorkloadDensity == nil {
		if err := json.Unmarshal([]byte(`{"memoryOvercommitPercentage": 100}`), &in.Spec.Virtualization.HigherWorkloadDensity); err != nil {
			panic(err)
		}
	}
	if in.Spec.Virtualization.HigherWorkloadDensity != nil {
		if in.Spec.Virtualization.HigherWorkloadDensity.MemoryOvercommitPercentage == 0 {
			in.Spec.Virtualization.HigherWorkloadDensity.MemoryOvercommitPercentage = 100
		}
	}
	if in.Spec.Virtualization.VmiCPUAllocationRatio == nil {
		var ptrVar1 int = 10
		in.Spec.Virtualization.VmiCPUAllocationRatio = &ptrVar1
	}
	if in.Spec.Security.CertConfig.CA.Duration == nil {
		if err := json.Unmarshal([]byte(`"48h0m0s"`), &in.Spec.Security.CertConfig.CA.Duration); err != nil {
			panic(err)
		}
	}
	if in.Spec.Security.CertConfig.CA.RenewBefore == nil {
		if err := json.Unmarshal([]byte(`"24h0m0s"`), &in.Spec.Security.CertConfig.CA.RenewBefore); err != nil {
			panic(err)
		}
	}
	if in.Spec.Security.CertConfig.Server.Duration == nil {
		if err := json.Unmarshal([]byte(`"24h0m0s"`), &in.Spec.Security.CertConfig.Server.Duration); err != nil {
			panic(err)
		}
	}
	if in.Spec.Security.CertConfig.Server.RenewBefore == nil {
		if err := json.Unmarshal([]byte(`"12h0m0s"`), &in.Spec.Security.CertConfig.Server.RenewBefore); err != nil {
			panic(err)
		}
	}
	if in.Spec.UninstallStrategy == "" {
		in.Spec.UninstallStrategy = "BlockUninstallIfWorkloadsExist"
	}
	if in.Spec.EnableCommonBootImageImport == nil {
		var ptrVar1 bool = true
		in.Spec.EnableCommonBootImageImport = &ptrVar1
	}
	if in.Spec.DeployVMConsoleProxy == nil {
		var ptrVar1 bool = false
		in.Spec.DeployVMConsoleProxy = &ptrVar1
	}
	if in.Spec.EnableApplicationAwareQuota == nil {
		var ptrVar1 bool = false
		in.Spec.EnableApplicationAwareQuota = &ptrVar1
	}
}

func SetObjectDefaults_HyperConvergedList(in *HyperConvergedList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_HyperConverged(a)
	}
}
