apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cdis.cdi.kubevirt.io
  labels:
    operator.cdi.kubevirt.io: ""
spec:
  group: cdi.kubevirt.io
  names:
    kind: CDI
    listKind: CDIList
    plural: cdis
    singular: cdi
  scope: Cluster
  version: v1alpha1
