---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperconverged-cluster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hyperconverged-cluster-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: hyperconverged-cluster-operator
    spec:
      containers:
      - command:
        - hyperconverged-cluster-operator
        env:
        - name: OPERATOR_IMAGE
          value: quay.io/kubevirt/hyperconverged-cluster-operator:latest
        - name: OPERATOR_NAME
          value: hyperconverged-cluster-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/kubevirt/hyperconverged-cluster-operator:latest
        imagePullPolicy: Always
        name: hyperconverged-cluster-operator
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/operator-sdk-ready
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
        resources: {}
      serviceAccountName: hyperconverged-cluster-operator
