---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.hostpathprovisioner.kubevirt.io: ""
  name: hostpathprovisioners.hostpathprovisioner.kubevirt.io
spec:
  group: hostpathprovisioner.kubevirt.io
  names:
    kind: HostPathProvisioner
    listKind: HostPathProvisionerList
    plural: hostpathprovisioners
    shortNames:
    - hpp
    - hpps
    singular: hostpathprovisioner
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
