
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cache-kubevirt-io-v1beta1-hyperconverged
  failurePolicy: Fail
  name: mhyperconverged.kb.io
  rules:
  - apiGroups:
    - cache.kubevirt.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hyperconvergeds
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cache-kubevirt-io-v1beta1-hyperconverged
  failurePolicy: Fail
  name: vhyperconverged.kb.io
  rules:
  - apiGroups:
    - cache.kubevirt.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hyperconvergeds
  sideEffects: None
