apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/kubevirt/hco-container-registry:latest
  displayName: KubeVirt HyperConverged
  publisher: KubeVirt Project
