---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperconverged-cluster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hyperconverged-cluster-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: hyperconverged-cluster-operator
    spec:
      containers:
      - command:
        - hyperconverged-cluster-operator
        env:
        - name: OPERATOR_IMAGE
          value: quay.io/kubevirt/hyperconverged-cluster-operator:latest
        - name: OPERATOR_NAME
          value: hyperconverged-cluster-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/kubevirt/hyperconverged-cluster-operator:latest
        imagePullPolicy: Always
        name: hyperconverged-cluster-operator
        resources: {}
      serviceAccountName: hyperconverged-cluster-operator


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kubevirt.io: virt-operator
  name: virt-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      kubevirt.io: virt-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly","operator":"Exists"}]'
      creationTimestamp: null
      labels:
        kubevirt.io: virt-operator
        prometheus.kubevirt.io: ""
      name: virt-operator
    spec:
      containers:
      - command:
        - virt-operator
        - --port
        - "8443"
        - -v
        - "2"
        env:
        - name: OPERATOR_IMAGE
          value: kubevirt/virt-operator:latest
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
        image: kubevirt/virt-operator:latest
        imagePullPolicy: IfNotPresent
        name: virt-operator
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          timeoutSeconds: 10
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kubevirt-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdi-operator
  namespace: kubevirt-hyperconverged
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cdi-operator
      operator.cdi.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: cdi-operator
        operator.cdi.kubevirt.io: ""
    spec:
      containers:
      - env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: DOCKER_REPO
          value: kubevirt
        - name: DOCKER_TAG
          value: v1.9.1
        - name: CONTROLLER_IMAGE
          value: cdi-controller
        - name: IMPORTER_IMAGE
          value: cdi-importer
        - name: CLONER_IMAGE
          value: cdi-cloner
        - name: APISERVER_IMAGE
          value: cdi-apiserver
        - name: UPLOAD_SERVER_IMAGE
          value: cdi-uploadserver
        - name: UPLOAD_PROXY_IMAGE
          value: cdi-uploadproxy
        - name: VERBOSITY
          value: "1"
        - name: PULL_POLICY
          value: IfNotPresent
        image: kubevirt/cdi-operator:v1.9.1
        imagePullPolicy: IfNotPresent
        name: cdi-operator
        ports:
        - containerPort: 60000
          name: metrics
          protocol: TCP
        resources: {}
      serviceAccountName: cdi-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-network-addons-operator
  namespace: kubevirt-hyperconverged
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-network-addons-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: cluster-network-addons-operator
    spec:
      containers:
      - env:
        - name: MULTUS_IMAGE
          value: quay.io/kubevirt/cluster-network-addon-multus:v3.2.0-1.gitbf61002
        - name: LINUX_BRIDGE_IMAGE
          value: quay.io/kubevirt/cni-default-plugins:v0.1.0
        - name: LINUX_BRIDGE_MARKER_IMAGE
          value: quay.io/kubevirt/bridge-marker:0.1.0
        - name: SRIOV_DP_IMAGE
          value: quay.io/kubevirt/cluster-network-addon-sriov-device-plugin:v2.0.0-1.git9a20829
        - name: SRIOV_CNI_IMAGE
          value: quay.io/kubevirt/cluster-network-addon-sriov-cni:v1.1.0-1.git9e4c973
        - name: SRIOV_ROOT_DEVICES
        - name: SRIOV_NETWORK_NAME
          value: sriov-network
        - name: SRIOV_NETWORK_TYPE
          value: sriov
        - name: KUBEMACPOOL_IMAGE
          value: quay.io/kubevirt/kubemacpool:v0.3.0
        - name: OPERATOR_IMAGE
          value: quay.io/kubevirt/cluster-network-addons-operator:0.7.0
        - name: OPERATOR_NAME
          value: cluster-network-addons-operator
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
        image: quay.io/kubevirt/cluster-network-addons-operator:0.7.0
        imagePullPolicy: IfNotPresent
        name: cluster-network-addons-operator
        resources: {}
      serviceAccountName: cluster-network-addons-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-ssp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubevirt-ssp-operator
  template:
    metadata:
      labels:
        name: kubevirt-ssp-operator
    spec:
      serviceAccountName: kubevirt-ssp-operator
      containers:
        - name: kubevirt-ssp-operator
          image: quay.io/fromani/kubevirt-ssp-operator-container:latest
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WATCH_NAMESPACE
              value: ""
            - name: VIRT_LAUNCHER_TAG
              value: v0.17.4
            - name: OPERATOR_NAME
              value: "kubevirt-ssp-operator"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-maintenance-operator
  namespace: node-maintenance-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-maintenance-operator
  template:
    metadata:
      labels:
        name: node-maintenance-operator
    spec:
      serviceAccountName: node-maintenance-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: node-maintenance-operator
          image: quay.io/kubevirt/node-maintenance-operator:v0.3.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "node-maintenance-operator"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-web-ui-operator
  namespace: kubevirt-hyperconverged
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubevirt-web-ui-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kubevirt-web-ui-operator
    spec:
      containers:
      - env:
        - name: OPERATOR_NAME
          value: kubevirt-web-ui-operator
        - name: OPERATOR_REGISTRY
          value: quay.io/kubevirt
        - name: OPERATOR_TAG
          value: latest
        - name: WEBUI_TAG
          value: latest
        - name: BRANDING
          value: okdvirt
        - name: IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/kubevirt/kubevirt-web-ui-operator:latest
        imagePullPolicy: IfNotPresent
        name: kubevirt-web-ui-operator
        ports:
        - containerPort: 60000
          name: metrics
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/operator-sdk-ready
          failureThreshold: 1
          initialDelaySeconds: 4
          periodSeconds: 10
        resources: {}
      serviceAccountName: kubevirt-web-ui-operator
