---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirtcommontemplatesbundles.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: KubevirtCommonTemplatesBundle
    listKind: KubevirtCommonTemplatesBundleList
    plural: kubevirtcommontemplatesbundles
    singular: kubevirtcommontemplatesbundle
  scope: Namespaced
  version: v1
  subresources:
    status: {}

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirtnodelabellerbundles.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: KubevirtNodeLabellerBundle
    listKind: KubevirtNodeLabellerBundleList
    plural: kubevirtnodelabellerbundles
    singular: kubevirtnodelabellerbundle
  scope: Namespaced
  version: v1
  subresources:
    status: {}

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirttemplatevalidators.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: KubevirtTemplateValidator
    listKind: KubevirtTemplateValidatorList
    plural: kubevirttemplatevalidators
    singular: kubevirttemplatevalidator
  scope: Namespaced
  version: v1
  subresources:
    status: {}

