# permissions for end users to view hyperconvergeds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hyperconverged-viewer-role
rules:
- apiGroups:
  - cache.kubevirt.io
  resources:
  - hyperconvergeds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.kubevirt.io
  resources:
  - hyperconvergeds/status
  verbs:
  - get
