# permissions for end users to edit hyperconvergeds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hyperconverged-editor-role
rules:
- apiGroups:
  - cache.kubevirt.io
  resources:
  - hyperconvergeds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.kubevirt.io
  resources:
  - hyperconvergeds/status
  verbs:
  - get
