#!/bin/bash

KUBEVIRT_VERSION="v0.41.3"
CDI_VERSION="v1.34.1"
NETWORK_ADDONS_VERSION="v0.53.6"
SSP_VERSION="v0.11.2"
NMO_VERSION="v0.9.1"
HPPO_VERSION="v0.8.2"
HPP_VERSION="v0.8.0"
CONVERSION_CONTAINER_VERSION="v2.0.0"
VMWARE_CONTAINER_VERSION="v2.0.0-9"
VM_IMPORT_VERSION="v0.3.6"

CONTAINER_REGISTRY="quay.io/kubevirt"

RELEASE_DELTA="${RELEASE_DELTA:-0}"

PACKAGE_DIR="./deploy/olm-catalog/community-kubevirt-hyperconverged"
CSV_VERSION=$(ls -d ${PACKAGE_DIR}/*/ | sort -rV | awk "NR==$((RELEASE_DELTA+1))" | cut -d '/' -f 5)
REPLACES_CSV_VERSION=$(ls -d ${PACKAGE_DIR}/*/ | sort -rV | awk "NR==$((RELEASE_DELTA+2))" | cut -d '/' -f 5)
