apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hyperconverged-cluster-operator
  labels:
    operator.hco.kubevirt.io: ""
subjects:
- kind: ServiceAccount
  name: hyperconverged-cluster-operator
  namespace: kubevirt
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
