apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt-hyperconverged
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hco-operatorhub
  namespace: kubevirt-hyperconverged
spec:
  channel: "1.0.0"
  installPlanApproval: Automatic
  name: hco-operatorhub
  source: installed-community-kubevirt-hyperconverged
  sourceNamespace: kubevirt-hyperconverged
  startingCSV: kubevirt-hyperconverged-operator.v1.0.0
