---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hyperconverged-cluster-operator
  name: hyperconverged-cluster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hyperconverged-cluster-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hyperconverged-cluster-operator
    spec:
      containers:
      - command:
        - hyperconverged-cluster-operator
        env:
        - name: WEBHOOK_MODE
          value: "false"
        - name: KVM_EMULATION
        - name: OPERATOR_IMAGE
          value: quay.io/kubevirt/hyperconverged-cluster-operator@sha256:19e3a3a9636185361e30f859216b83c9fcd1c3acbfd7129bf8a6adbc468b5a2e
        - name: OPERATOR_NAME
          value: hyperconverged-cluster-operator
        - name: OPERATOR_NAMESPACE
          value: kubevirt-hyperconverged
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
        - name: CONVERSION_CONTAINER
          value: quay.io/kubevirt/kubevirt-v2v-conversion@sha256:c620233c71b805004c2cd38927c421b69d99b27cb40af521967e655882b2f815
        - name: VMWARE_CONTAINER
          value: quay.io/kubevirt/kubevirt-vmware@sha256:ae5ccd98a49ab9e154ce482d2fa73f044b00211f273210a9cd371b40746d3c92
        - name: SMBIOS
          value: |-
            Family: KubeVirt
            Manufacturer: KubeVirt
            Product: None
        - name: MACHINETYPE
        - name: HCO_KV_IO_VERSION
          value: 1.3.0
        - name: KUBEVIRT_VERSION
          value: v0.35.0
        - name: CDI_VERSION
          value: v1.25.0
        - name: NETWORK_ADDONS_VERSION
          value: v0.42.3
        - name: SSP_VERSION
          value: v1.2.1
        - name: NMO_VERSION
          value: v0.7.0
        - name: HPPO_VERSION
          value: v0.6.0
        - name: VM_IMPORT_VERSION
          value: v0.2.5
        image: quay.io/kubevirt/hyperconverged-cluster-operator@sha256:19e3a3a9636185361e30f859216b83c9fcd1c3acbfd7129bf8a6adbc468b5a2e
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /livez
            port: 6060
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
        name: hyperconverged-cluster-operator
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /readyz
            port: 6060
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
        resources: {}
      serviceAccountName: hyperconverged-cluster-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hyperconverged-cluster-webhook
  name: hyperconverged-cluster-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hyperconverged-cluster-webhook
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hyperconverged-cluster-webhook
    spec:
      containers:
      - command:
        - hyperconverged-cluster-operator
        env:
        - name: WEBHOOK_MODE
          value: "true"
        - name: OPERATOR_IMAGE
          value: quay.io/kubevirt/hyperconverged-cluster-operator@sha256:19e3a3a9636185361e30f859216b83c9fcd1c3acbfd7129bf8a6adbc468b5a2e
        - name: OPERATOR_NAME
          value: hyperconverged-cluster-webhook
        - name: OPERATOR_NAMESPACE
          value: kubevirt-hyperconverged
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
        image: quay.io/kubevirt/hyperconverged-cluster-operator@sha256:19e3a3a9636185361e30f859216b83c9fcd1c3acbfd7129bf8a6adbc468b5a2e
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /livez
            port: 6060
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
        name: hyperconverged-cluster-webhook
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /readyz
            port: 6060
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
        resources: {}
      serviceAccountName: hyperconverged-cluster-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cluster-network-addons-operator
  name: cluster-network-addons-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-network-addons-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: cluster-network-addons-operator
    spec:
      containers:
      - env:
        - name: MULTUS_IMAGE
          value: nfvpe/multus@sha256:167722b954355361bd69829466f27172b871dbdbf86b85a95816362885dc0aba
        - name: LINUX_BRIDGE_IMAGE
          value: quay.io/kubevirt/cni-default-plugins@sha256:3dd438117076016d6d2acd508b93f106ca80a28c0af6e2e914d812f9a1d55142
        - name: LINUX_BRIDGE_MARKER_IMAGE
          value: quay.io/kubevirt/bridge-marker@sha256:e55f73526468fee46a35ae41aa860f492d208b8a7a132832c5b9a76d4a51566a
        - name: NMSTATE_HANDLER_IMAGE
          value: quay.io/nmstate/kubernetes-nmstate-handler@sha256:444ab3349882ac58f594396529708146993b831c2e3e1d524eaa12e17e09f150
        - name: OVS_CNI_IMAGE
          value: quay.io/kubevirt/ovs-cni-plugin@sha256:4101c52617efb54a45181548c257a08e3689f634b79b9dfcff42bffd8b25af53
        - name: OVS_MARKER_IMAGE
          value: quay.io/kubevirt/ovs-cni-marker@sha256:0f08d6b1550a90c9f10221f2bb07709d1090e7c675ee1a711981bd429074d620
        - name: KUBEMACPOOL_IMAGE
          value: quay.io/kubevirt/kubemacpool@sha256:79c4534d418c4a350a663e38499c22d54dc68c400f517aead4479f6d862b408e
        - name: MACVTAP_CNI_IMAGE
          value: quay.io/kubevirt/macvtap-cni@sha256:407f75760fc096666becfa45d94f51757ebbe8f382e9e7b57ceeded0b8cfb6b8
        - name: OPERATOR_IMAGE
          value: quay.io/kubevirt/cluster-network-addons-operator@sha256:8fe7a5ae4cde693cf1adf681af58bb3911157c92a260b01c58cd43b2211403b3
        - name: OPERATOR_NAME
          value: cluster-network-addons-operator
        - name: OPERATOR_VERSION
          value: v0.42.3
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERAND_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
        image: quay.io/kubevirt/cluster-network-addons-operator@sha256:8fe7a5ae4cde693cf1adf681af58bb3911157c92a260b01c58cd43b2211403b3
        imagePullPolicy: IfNotPresent
        name: cluster-network-addons-operator
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cluster-network-addons-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: virt-operator
  name: virt-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      kubevirt.io: virt-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        kubevirt.io: virt-operator
        prometheus.kubevirt.io: ""
      name: virt-operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: kubevirt.io
                  operator: In
                  values:
                  - virt-operator
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - command:
        - virt-operator
        - --port
        - "8443"
        - -v
        - "2"
        env:
        - name: OPERATOR_IMAGE
          value: docker.io/kubevirt/virt-operator@sha256:494f1bfde54677e217ea621ff845c71bb1311d27064ba3b9f3811cb2244e54bf
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: KUBEVIRT_VERSION
          value: v0.35.0
        - name: VIRT_API_SHASUM
          value: sha256:bf38c1997f3c60a71d53b956f235973834d37c0c604b5711084b2a7ef8cd3c7b
        - name: VIRT_CONTROLLER_SHASUM
          value: sha256:7b81c59034df51c1a1f54d3180e0df678469790b6a8ac4fcc5fcaa615b1ca84c
        - name: VIRT_HANDLER_SHASUM
          value: sha256:14b4bd6d62b585ef2f4dbacafc75a66a6c575c64ed630835cf4ef6c0f77d40d1
        - name: VIRT_LAUNCHER_SHASUM
          value: sha256:a6d9f1dada1d33a218ba9ed0494d2e2cd09f5596eff5eb5b8d70bfe1fd4f8812
        image: docker.io/kubevirt/virt-operator@sha256:494f1bfde54677e217ea621ff845c71bb1311d27064ba3b9f3811cb2244e54bf
        imagePullPolicy: IfNotPresent
        name: virt-operator
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 8444
          name: webhooks
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          timeoutSeconds: 10
        resources: {}
        volumeMounts:
        - mountPath: /etc/virt-operator/certificates
          name: kubevirt-operator-certs
          readOnly: true
      priorityClassName: kubevirt-cluster-critical
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kubevirt-operator
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - name: kubevirt-operator-certs
        secret:
          optional: true
          secretName: kubevirt-operator-certs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kubevirt-ssp-operator
  name: kubevirt-ssp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubevirt-ssp-operator
  strategy: {}
  template:
    metadata:
      labels:
        name: kubevirt-ssp-operator
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: IMAGE_REFERENCE
          value: quay.io/fromani/kubevirt-ssp-operator-container@sha256:13ecfd8bc5779721378cfed69109bcc99392b0dcd589ddd600eb2648de9fce8c
        - name: WATCH_NAMESPACE
        - name: KVM_INFO_TAG
        - name: VALIDATOR_TAG
        - name: VIRT_LAUNCHER_TAG
        - name: NODE_LABELLER_TAG
        - name: CPU_PLUGIN_TAG
        - name: IMAGE_NAME_PREFIX
        - name: OPERATOR_NAME
          value: kubevirt-ssp-operator
        - name: OPERATOR_VERSION
          value: v1.2.1
        image: quay.io/fromani/kubevirt-ssp-operator-container@sha256:13ecfd8bc5779721378cfed69109bcc99392b0dcd589ddd600eb2648de9fce8c
        imagePullPolicy: IfNotPresent
        name: kubevirt-ssp-operator
        ports:
        - containerPort: 60000
          name: metrics
        resources: {}
      serviceAccountName: kubevirt-ssp-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cdi-operator
  name: cdi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cdi-operator
      operator.cdi.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      labels:
        name: cdi-operator
        operator.cdi.kubevirt.io: ""
    spec:
      containers:
      - env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: OPERATOR_VERSION
          value: v1.25.0
        - name: CONTROLLER_IMAGE
          value: docker.io/kubevirt/cdi-controller@sha256:34b7d03ffec9b84ba2e51163367898566acd6c283f489d5e8213670ab8cc719a
        - name: IMPORTER_IMAGE
          value: docker.io/kubevirt/cdi-importer@sha256:60e45465ff001060568956c62fd16e1369f7e3eb1a03ef10c8a30caca5b9e6d7
        - name: CLONER_IMAGE
          value: docker.io/kubevirt/cdi-cloner@sha256:07526b6e857141fe6dee2bc1030aaea3be8a5ee84d92d8bf0cedc80083756148
        - name: APISERVER_IMAGE
          value: docker.io/kubevirt/cdi-apiserver@sha256:d3f930e7d95a618d3248b158ca4b43e93b7046251e92211bc0601a92df5873d0
        - name: UPLOAD_SERVER_IMAGE
          value: docker.io/kubevirt/cdi-uploadserver@sha256:a7fee7110aff08cc73ead74bf95fb27fa8fddca11b7c113d7760ba4fa9377217
        - name: UPLOAD_PROXY_IMAGE
          value: docker.io/kubevirt/cdi-uploadproxy@sha256:060781e0ad6fcce19eca414503a5b187f75581d709a2d94e83204da250a50040
        - name: VERBOSITY
          value: "1"
        - name: PULL_POLICY
          value: IfNotPresent
        image: docker.io/kubevirt/cdi-operator@sha256:d3ef43e7bf332668d6e2a6a3ddf657ef7c96841dfba6c56043e4199641c148e3
        imagePullPolicy: IfNotPresent
        name: cdi-operator
        ports:
        - containerPort: 60000
          name: metrics
          protocol: TCP
        resources: {}
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cdi-operator
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: node-maintenance-operator
  name: node-maintenance-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-maintenance-operator
  strategy: {}
  template:
    metadata:
      labels:
        name: node-maintenance-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      containers:
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: node-maintenance-operator
        image: quay.io/kubevirt/node-maintenance-operator:v0.7.0
        imagePullPolicy: Always
        name: node-maintenance-operator
        resources: {}
      serviceAccountName: node-maintenance-operator
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hostpath-provisioner-operator
  name: hostpath-provisioner-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hostpath-provisioner-operator
      operator.hostpath-provisioner.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      labels:
        name: hostpath-provisioner-operator
        operator.hostpath-provisioner.kubevirt.io: ""
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: hostpath-provisioner-operator
        - name: PROVISIONER_IMAGE
          value: quay.io/kubevirt/hostpath-provisioner@sha256:9d92c216bc50d7fbfc787f315ad77dabd2ac26d981702efd545a1dd1f2b37c6c
        - name: PULL_POLICY
          value: IfNotPresent
        image: quay.io/kubevirt/hostpath-provisioner-operator@sha256:4285a9b7a624b2f300a4060a035d506195dc9b342928f98adc5f7784d8478929
        imagePullPolicy: IfNotPresent
        name: hostpath-provisioner-operator
        resources: {}
      serviceAccountName: hostpath-provisioner-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: vm-import-operator
  name: vm-import-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vm-import-operator
      operator.v2v.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      labels:
        name: vm-import-operator
        operator.v2v.kubevirt.io: ""
    spec:
      containers:
      - env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: OPERATOR_VERSION
          value: v0.2.5
        - name: CONTROLLER_IMAGE
          value: quay.io/kubevirt/vm-import-controller@sha256:481f4a493a66d1310734ac135e8dbaa5dc01c9d93f6e9ecc9326b81c1c08dbfe
        - name: PULL_POLICY
          value: IfNotPresent
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MONITORING_NAMESPACE
          value: openshift-monitoring
        - name: VIRTV2V_IMAGE
          value: quay.io/kubevirt/vm-import-virtv2v@sha256:97caccb965d771afefd901c71381b6c1126e4177b477d47f2ca5ca57c5b06593
        image: quay.io/kubevirt/vm-import-operator@sha256:74fc74dab0671ef1098e69872e47bcb6f85a40b4b18a1e23fd6d3cfc36dfee32
        imagePullPolicy: IfNotPresent
        name: vm-import-operator
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: vm-import-operator
