---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hyperconverged-cluster-operator
  name: hyperconverged-cluster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hyperconverged-cluster-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hyperconverged-cluster-operator
    spec:
      containers:
      - command:
        - hyperconverged-cluster-operator
        env:
        - name: WEBHOOK_MODE
          value: "false"
        - name: APP
          value: OPERATOR
        - name: KVM_EMULATION
        - name: OPERATOR_IMAGE
          value: quay.io/kubevirt/hyperconverged-cluster-operator@sha256:e7356254a1251f1fba682be77c9a90b1f840d6a84ff88492fb1e87ae30dda9da
        - name: OPERATOR_NAME
          value: hyperconverged-cluster-operator
        - name: OPERATOR_NAMESPACE
          value: kubevirt-hyperconverged
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
        - name: CONVERSION_CONTAINER
          value: quay.io/kubevirt/kubevirt-v2v-conversion@sha256:c620233c71b805004c2cd38927c421b69d99b27cb40af521967e655882b2f815
        - name: VMWARE_CONTAINER
          value: quay.io/kubevirt/kubevirt-vmware@sha256:ae5ccd98a49ab9e154ce482d2fa73f044b00211f273210a9cd371b40746d3c92
        - name: SMBIOS
          value: |-
            Family: KubeVirt
            Manufacturer: KubeVirt
            Product: None
        - name: MACHINETYPE
        - name: HCO_KV_IO_VERSION
          value: 1.3.0
        - name: KUBEVIRT_VERSION
          value: v0.36.0
        - name: CDI_VERSION
          value: v1.28.0
        - name: NETWORK_ADDONS_VERSION
          value: v0.44.0
        - name: SSP_VERSION
          value: v1.2.1
        - name: NMO_VERSION
          value: v0.7.0
        - name: HPPO_VERSION
          value: v0.7.0
        - name: VM_IMPORT_VERSION
          value: v0.2.5
        image: quay.io/kubevirt/hyperconverged-cluster-operator@sha256:e7356254a1251f1fba682be77c9a90b1f840d6a84ff88492fb1e87ae30dda9da
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /livez
            port: 6060
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
        name: hyperconverged-cluster-operator
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /readyz
            port: 6060
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
        resources: {}
      serviceAccountName: hyperconverged-cluster-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hyperconverged-cluster-webhook
  name: hyperconverged-cluster-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hyperconverged-cluster-webhook
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hyperconverged-cluster-webhook
    spec:
      containers:
      - command:
        - hyperconverged-cluster-webhook
        env:
        - name: WEBHOOK_MODE
          value: "true"
        - name: APP
          value: WEBHOOK
        - name: OPERATOR_IMAGE
          value: quay.io/kubevirt/hyperconverged-cluster-webhook@sha256:e352594403627756bae3b4d6579967819fc544ced3c371d971a090a99fe0a9e9
        - name: OPERATOR_NAME
          value: hyperconverged-cluster-webhook
        - name: OPERATOR_NAMESPACE
          value: kubevirt-hyperconverged
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
        image: quay.io/kubevirt/hyperconverged-cluster-webhook@sha256:e352594403627756bae3b4d6579967819fc544ced3c371d971a090a99fe0a9e9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /livez
            port: 6060
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
        name: hyperconverged-cluster-webhook
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /readyz
            port: 6060
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
        resources: {}
      serviceAccountName: hyperconverged-cluster-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cluster-network-addons-operator
  name: cluster-network-addons-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-network-addons-operator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        description: cluster-network-addons-operator manages the lifecycle of different Kubernetes network components on top of Kubernetes cluster
      labels:
        name: cluster-network-addons-operator
    spec:
      containers:
      - env:
        - name: MULTUS_IMAGE
          value: nfvpe/multus@sha256:ac1266b87ba44c09dc2a336f0d5dad968fccd389ce1944a85e87b32cd21f7224
        - name: LINUX_BRIDGE_IMAGE
          value: quay.io/kubevirt/cni-default-plugins@sha256:606eaa06262ad6edd5aa809491c7e46b9ddbc9c52ba8c47e89e734e3e80cd311
        - name: LINUX_BRIDGE_MARKER_IMAGE
          value: quay.io/kubevirt/bridge-marker@sha256:799459f8509a06ea643aa2f6ac02826721a641333aacab07e53166139a5a66c3
        - name: NMSTATE_HANDLER_IMAGE
          value: quay.io/nmstate/kubernetes-nmstate-handler@sha256:d5155de6aa6cf97c2feb5f4171384e63ce957362a66d47ec14982cbabca5169c
        - name: OVS_CNI_IMAGE
          value: quay.io/kubevirt/ovs-cni-plugin@sha256:d43d34ed4b1bd0b107c2049d21e33f9f870c36e5bf6dc1d80ab567271735c8da
        - name: OVS_MARKER_IMAGE
          value: quay.io/kubevirt/ovs-cni-marker@sha256:8ec72d6a3d58cea27a2b9a52e6ef4ee0d753b3ba989d24555bdfbf01a995a9c1
        - name: KUBEMACPOOL_IMAGE
          value: quay.io/kubevirt/kubemacpool@sha256:e68811ce7697ab0f1257f307fcd63b08b6295de7f300e01a982e4e624bfa7398
        - name: MACVTAP_CNI_IMAGE
          value: quay.io/kubevirt/macvtap-cni@sha256:f20d5e56f8b8c1ab7e5a64e536b66f65aa688b2d1dc0b37e3c26c2af2b481266
        - name: OPERATOR_IMAGE
          value: quay.io/kubevirt/cluster-network-addons-operator@sha256:38dadf3624c30092b67aa74487b3f744c835f9a17f33b4408f1f1bab3a79004d
        - name: OPERATOR_NAME
          value: cluster-network-addons-operator
        - name: OPERATOR_VERSION
          value: v0.44.0
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERAND_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
        image: quay.io/kubevirt/cluster-network-addons-operator@sha256:38dadf3624c30092b67aa74487b3f744c835f9a17f33b4408f1f1bab3a79004d
        imagePullPolicy: IfNotPresent
        name: cluster-network-addons-operator
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cluster-network-addons-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: virt-operator
  name: virt-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      kubevirt.io: virt-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        kubevirt.io: virt-operator
        prometheus.kubevirt.io: ""
      name: virt-operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: kubevirt.io
                  operator: In
                  values:
                  - virt-operator
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - command:
        - virt-operator
        - --port
        - "8443"
        - -v
        - "2"
        env:
        - name: OPERATOR_IMAGE
          value: docker.io/kubevirt/virt-operator@sha256:4c33eaab42033c84310b62e146274f95a55699235c59846c8cec3009a91a723f
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: KUBEVIRT_VERSION
          value: v0.36.0
        - name: VIRT_API_SHASUM
          value: sha256:4d778f63d2f5ecb61d4f6fe8b5ead010836d46d75349f3c3634f5862614e4a21
        - name: VIRT_CONTROLLER_SHASUM
          value: sha256:f1fe5d43cd89b2f7d18cb23a14753b260a85f7e862b13529b640d7e8c36e81d5
        - name: VIRT_HANDLER_SHASUM
          value: sha256:10e9294253c2037d29a9a33dfeb3b096dbb7ceb5ed2f0fc1662d66535108d236
        - name: VIRT_LAUNCHER_SHASUM
          value: sha256:1bb248aeb9d0bc66667f6133f8230cc80944b562c3d267cc00a5382954140c12
        image: docker.io/kubevirt/virt-operator@sha256:4c33eaab42033c84310b62e146274f95a55699235c59846c8cec3009a91a723f
        imagePullPolicy: IfNotPresent
        name: virt-operator
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 8444
          name: webhooks
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          timeoutSeconds: 10
        resources: {}
        volumeMounts:
        - mountPath: /etc/virt-operator/certificates
          name: kubevirt-operator-certs
          readOnly: true
      priorityClassName: kubevirt-cluster-critical
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kubevirt-operator
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - name: kubevirt-operator-certs
        secret:
          optional: true
          secretName: kubevirt-operator-certs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kubevirt-ssp-operator
  name: kubevirt-ssp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubevirt-ssp-operator
  strategy: {}
  template:
    metadata:
      labels:
        name: kubevirt-ssp-operator
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: IMAGE_REFERENCE
          value: quay.io/fromani/kubevirt-ssp-operator-container@sha256:13ecfd8bc5779721378cfed69109bcc99392b0dcd589ddd600eb2648de9fce8c
        - name: WATCH_NAMESPACE
        - name: KVM_INFO_TAG
        - name: VALIDATOR_TAG
        - name: VIRT_LAUNCHER_TAG
        - name: NODE_LABELLER_TAG
        - name: CPU_PLUGIN_TAG
        - name: IMAGE_NAME_PREFIX
        - name: OPERATOR_NAME
          value: kubevirt-ssp-operator
        - name: OPERATOR_VERSION
          value: v1.2.1
        image: quay.io/fromani/kubevirt-ssp-operator-container@sha256:13ecfd8bc5779721378cfed69109bcc99392b0dcd589ddd600eb2648de9fce8c
        imagePullPolicy: IfNotPresent
        name: kubevirt-ssp-operator
        ports:
        - containerPort: 60000
          name: metrics
        resources: {}
      serviceAccountName: kubevirt-ssp-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cdi-operator
  name: cdi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cdi-operator
      operator.cdi.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      labels:
        name: cdi-operator
        operator.cdi.kubevirt.io: ""
    spec:
      containers:
      - env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: OPERATOR_VERSION
          value: v1.28.0
        - name: CONTROLLER_IMAGE
          value: docker.io/kubevirt/cdi-controller@sha256:bbd22f481ec1dd1eaf63af9888d107c3f67507e578600da8a5429540c78527bc
        - name: IMPORTER_IMAGE
          value: docker.io/kubevirt/cdi-importer@sha256:d16dd224def1713a51278f6f164a04c7e9b38364b794f14d18c2d8d14ab04eb3
        - name: CLONER_IMAGE
          value: docker.io/kubevirt/cdi-cloner@sha256:c8946ef116d4d2fccf08b895faf07d9bb85f76d315e4380416261db9970306f1
        - name: APISERVER_IMAGE
          value: docker.io/kubevirt/cdi-apiserver@sha256:02d0363e32cd28145a9802cad2c0adc077e67715d55a948c0bc92ae2adf08813
        - name: UPLOAD_SERVER_IMAGE
          value: docker.io/kubevirt/cdi-uploadserver@sha256:3915ba0501fa0e3ee9ae178d6617d0c1ac5f34a83243f723421c42de99e705e5
        - name: UPLOAD_PROXY_IMAGE
          value: docker.io/kubevirt/cdi-uploadproxy@sha256:9e5ae41e3da07c30ac9a0326c89f2d64021abfc5d74ee6c4b750d6915f02eeb5
        - name: VERBOSITY
          value: "1"
        - name: PULL_POLICY
          value: IfNotPresent
        image: docker.io/kubevirt/cdi-operator@sha256:8e9a4d4a819c11e53b9ebc316590aeb0515ffd92a92f0281d8c2d90fd819e711
        imagePullPolicy: IfNotPresent
        name: cdi-operator
        ports:
        - containerPort: 60000
          name: metrics
          protocol: TCP
        resources: {}
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cdi-operator
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: node-maintenance-operator
  name: node-maintenance-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-maintenance-operator
  strategy: {}
  template:
    metadata:
      labels:
        name: node-maintenance-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      containers:
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: node-maintenance-operator
        image: quay.io/kubevirt/node-maintenance-operator@sha256:71bb8de714dc0de0616050d66405ccb58841930fc1562a61399e1b964a0b678a
        imagePullPolicy: Always
        name: node-maintenance-operator
        resources: {}
      serviceAccountName: node-maintenance-operator
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hostpath-provisioner-operator
  name: hostpath-provisioner-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hostpath-provisioner-operator
      operator.hostpath-provisioner.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      labels:
        name: hostpath-provisioner-operator
        operator.hostpath-provisioner.kubevirt.io: ""
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: hostpath-provisioner-operator
        - name: PROVISIONER_IMAGE
          value: quay.io/kubevirt/hostpath-provisioner@sha256:3838d8e713d2e85a807a9c302501b25c248ba3f3c1602fe50480e6510de43e11
        - name: PULL_POLICY
          value: IfNotPresent
        image: quay.io/kubevirt/hostpath-provisioner-operator@sha256:a51e9b075a60600244757386f5894b314170543edb1d7f4738f4860a19602072
        imagePullPolicy: IfNotPresent
        name: hostpath-provisioner-operator
        resources: {}
      serviceAccountName: hostpath-provisioner-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: vm-import-operator
  name: vm-import-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vm-import-operator
      operator.v2v.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      labels:
        name: vm-import-operator
        operator.v2v.kubevirt.io: ""
    spec:
      containers:
      - env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: OPERATOR_VERSION
          value: v0.2.5
        - name: CONTROLLER_IMAGE
          value: quay.io/kubevirt/vm-import-controller@sha256:481f4a493a66d1310734ac135e8dbaa5dc01c9d93f6e9ecc9326b81c1c08dbfe
        - name: PULL_POLICY
          value: IfNotPresent
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MONITORING_NAMESPACE
          value: openshift-monitoring
        - name: VIRTV2V_IMAGE
          value: quay.io/kubevirt/vm-import-virtv2v@sha256:97caccb965d771afefd901c71381b6c1126e4177b477d47f2ca5ca57c5b06593
        image: quay.io/kubevirt/vm-import-operator@sha256:74fc74dab0671ef1098e69872e47bcb6f85a40b4b18a1e23fd6d3cfc36dfee32
        imagePullPolicy: IfNotPresent
        name: vm-import-operator
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: vm-import-operator
