apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperconverged-cluster-operator
  labels:
      operator.hco.kubevirt.io: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hyperconverged-cluster-operator
  template:
    metadata:
      labels:
        name: hyperconverged-cluster-operator
    spec:
      serviceAccountName: hyperconverged-cluster-operator
      containers:
        - name: hyperconverged-cluster-operator
          image: "docker.io/rthallisey/hyperconverged-cluster-operator:latest"
          command:
          - hyperconverged-cluster-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hyperconverged-cluster-operator"
