---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    kubevirt.io: ""
  name: hyperconverged-cluster-operator
  namespace: kubevirt-hyperconverged

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    kubevirt.io: ""
  name: cdi-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    kubevirt.io: ""
  name: kubevirt-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    kubevirt.io: ""
  name: cluster-network-addons-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    kubevirt.io: ""
  name: kubevirt-ssp-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    kubevirt.io: ""
  name: node-maintenance-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    machineremediation.kubevirt.io: ""
    machineremediation.kubevirt.io/version: v0.3.7
  name: machine-remediation-operator
  namespace: kubevirt-hyperconverged
