apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hyperconverged-cluster-webhook-service-cert
  labels:
    name: hyperconverged-cluster-webhook
spec:
  secretName: hyperconverged-cluster-webhook-service-cert
  dnsNames:
  - hyperconverged-cluster-webhook-service.kubevirt-hyperconverged.svc
  issuerRef:
    name: selfsigned
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-hco.kubevirt.io
  annotations:
    cert-manager.io/inject-ca-from: kubevirt-hyperconverged/hyperconverged-cluster-webhook-service-cert
  labels:
    name: hyperconverged-cluster-webhook
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    # caBundle: WILL BE INJECTED BY CERT-MANAGER BECAUSE OF THE ANNOTATION
    service:
      name: hyperconverged-cluster-webhook-service
      namespace: kubevirt-hyperconverged
      path: /validate-hco-kubevirt-io-v1beta1-hyperconverged
      port: 4343
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate-hco.kubevirt.io
  objectSelector: {}
  rules:
  - apiGroups:
    - hco.kubevirt.io
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - DELETE
    - UPDATE
    resources:
    - hyperconvergeds
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: node-maintenance-operator-service-cert
  labels:
    name: node-maintenance-operator
spec:
  secretName: node-maintenance-operator-service-cert
  dnsNames:
  - node-maintenance-operator-service.kubevirt-hyperconverged.svc
  issuerRef:
    name: selfsigned
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: nodemaintenance-validation.kubevirt.io
  annotations:
    cert-manager.io/inject-ca-from: kubevirt-hyperconverged/node-maintenance-operator-service-cert
  labels:
    name: node-maintenance-operator
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    # caBundle: WILL BE INJECTED BY CERT-MANAGER BECAUSE OF THE ANNOTATION
    service:
      name: node-maintenance-operator-service
      namespace: kubevirt-hyperconverged
      path: /validate-nodemaintenance-kubevirt-io-v1beta1-nodemaintenances
      port: 8443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: nodemaintenance-validation.kubevirt.io
  objectSelector: {}
  rules:
  - apiGroups:
    - nodemaintenance.kubevirt.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodemaintenances
    scope: Cluster
  sideEffects: None
  timeoutSeconds: 15
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssp-operator-service-cert
  labels:
    name: ssp-operator
spec:
  secretName: ssp-operator-service-cert
  dnsNames:
  - ssp-operator-service.kubevirt-hyperconverged.svc
  issuerRef:
    name: selfsigned
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: vssp.kb.io
  annotations:
    cert-manager.io/inject-ca-from: kubevirt-hyperconverged/ssp-operator-service-cert
  labels:
    name: ssp-operator
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    # caBundle: WILL BE INJECTED BY CERT-MANAGER BECAUSE OF THE ANNOTATION
    service:
      name: ssp-operator-service
      namespace: kubevirt-hyperconverged
      path: /validate-ssp-kubevirt-io-v1beta1-ssp
      port: 9443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vssp.kb.io
  objectSelector: {}
  rules:
  - apiGroups:
    - ssp.kubevirt.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ssps
  sideEffects: None
  timeoutSeconds: 10
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: kubevirt-hyperconverged
  name: hostpath-provisioner-operator-webhook-service-cert
  labels:
    name: hostpath-provisioner-operator
spec:
  secretName: hostpath-provisioner-operator-webhook-service-cert
  dnsNames:
  - hostpath-provisioner-operator-webhook-service.hostpath-provisioner.svc
  issuerRef:
    name: selfsigned
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: hostpathprovisioner.kubevirt.io
  annotations:
    cert-manager.io/inject-ca-from: hostpath-provisioner/hostpath-provisioner-operator-webhook-service-cert
  labels:
    name: hostpath-provisioner-operator
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: hostpath-provisioner-operator-webhook-service
      namespace: hostpath-provisioner
      path: /validate-hostpathprovisioner-kubevirt-io-v1beta1-hostpathprovisioner
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate-hostpath-provisioner.kubevirt.io
  objectSelector: {}
  rules:
  - apiGroups:
    - hostpathprovisioner.kubevirt.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - DELETE
    - UPDATE
    resources:
    - "*/*"
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutate-hco.kubevirt.io
  annotations:
    cert-manager.io/inject-ca-from: kubevirt-hyperconverged/hyperconverged-cluster-webhook-service-cert
  labels:
    name: hyperconverged-cluster-webhook
webhooks:
- name: mutate-hyperconverged-hco.kubevirt.io
  admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    # caBundle: WILL BE INJECTED BY CERT-MANAGER BECAUSE OF THE ANNOTATION
    service:
      name: hyperconverged-cluster-webhook-service
      namespace: kubevirt-hyperconverged
      path: /mutate-hco-kubevirt-io-v1beta1-hyperconverged
      port: 4343
  failurePolicy: Fail
  matchPolicy: Equivalent
  rules:
  - apiGroups:
    - "hco.kubevirt.io"
    apiVersions:
    - "v1beta1"
    operations:
    - CREATE
    - UPDATE
    resources:
    - hyperconvergeds
    scope: '*'
  sideEffects: NoneOnDryRun
  timeoutSeconds: 30
