FROM quay.io/openshift/origin-operator-registry:latest@sha256:dde6c523e74da6b8cdb481adc648cce95d205df15e56bef43e7c0aca9d0588a5

USER 0
RUN rm -rf /manifests \
    && rm -rf /db \
    && mkdir -p /manifests \
    && mkdir -p /db \
    && touch /db/bundles.db \
    && chown -R 1001:1001 /db

USER 1001
COPY patched_manifests/ /manifests

# Initialize the database
RUN initializer --manifests /manifests/ --output /db/bundles.db

ENTRYPOINT ["registry-server"]
CMD ["--database", "/db/bundles.db"]
