FROM quay.io/openshift/origin-operator-registry:latest@sha256:ed6ee42175195d18afc4a371d480d4ede04ea348ce9cdb52933a24330fef510e

USER 0
RUN rm -rf /manifests \
    && rm -rf /db \
    && mkdir -p /manifests \
    && mkdir -p /db \
    && touch /db/bundles.db \
    && chown -R 1001:1001 /db

USER 1001
COPY patched_manifests/ /manifests

# Initialize the database
RUN initializer --manifests /manifests/ --output /db/bundles.db

ENTRYPOINT ["registry-server"]
CMD ["--database", "/db/bundles.db"]
