FROM quay.io/openshift/origin-operator-registry:latest@sha256:694b47f0278f9696db82295aca8b4f1f43fbbec33d8c97ee4e0004a895abd7a8

USER 0
RUN rm -rf /manifests \
    && rm -rf /db \
    && mkdir -p /manifests \
    && mkdir -p /db \
    && touch /db/bundles.db \
    && chown -R 1001:1001 /db

USER 1001
COPY patched_manifests/ /manifests

# Initialize the database
RUN initializer --manifests /manifests/ --output /db/bundles.db

ENTRYPOINT ["registry-server"]
CMD ["--database", "/db/bundles.db"]
