@startuml
title HCO - Aggregate Nagative Conditions

start
  #springgreen:Set **ReconcileComplete = True**]
  !x=1
if ((x) [Degraded = True] Exists) then
  !x=x+1
  #orangered:<<implicit>>\n**Degraded = True** /
  -[#orangered]-> yes;
  if ((x) [Progressing = True] Exists) then
    !x=x+1
    -[#springgreen]-> no;
    #springgreen:(x) Set **Progressing = False**]
    !x=x+1
  else
    -[#orangered]-> yes;
    #orangered:<<implicit>>\n**Progressing = True** /
  endif
  if ((x) [Upgradable = False] Exists) then
    !x=x+1
    -[#springgreen]-> no;
    #orangered:(x) Set **Upgradable = False**]
    !x=x+1
  else
    -[#orangered]-> yes;
    #orangered:<<implicit>>\n**Upgradable = False**/
  endif
  if ((x) [Available = False] Exists) then
    !x=x+1
    -[#springgreen]-> no;
    #orangered:(x) Set **Available = False**]
    !x=x+1
  else
    -[#orangered]-> yes;
    #orangered:<<implicit>>\n**Available = False**/
  endif
else
  -[#springgreen]-> no;
  #springgreen:(x) Set **Degraded = False**]
  !x=x+1
  if ((x) [Progressing = True] Exists) then
    !x=x+1
    -[#orangered]-> yes;
    #orangered:<<implicit>>\n**Progressing = True**/
    if ((x) [Upgradable = False] Exists) then
      !x=x+1
      -[#springgreen]-> no;
      #orangered:(x) Set **Upgradable = False**]
      !x=x+1
    else
      -[#orangered]-> yes;
      #orangered:<<implicit>>\n**Upgradable = False**/
    endif
    if ((x) [Available = False] Exists) then
      !x=x+1
      -[#springgreen]-> no;
      #springgreen:(x) Set **Available = True**]
      !x=x+1
    else
      #orangered:<<implicit>>\n**Available = False**/
      -[#orangered]-> yes;
    endif
  else
    -[#springgreen]-> no;
    #springgreen:(x) Set **Progressing = False**]
    !x=x+1
    if ((x) [Upgradable = False] Exists) then
      !x=x+1
      -[#springgreen]-> no;
      #springgreen:(x) Set **Upgradable = True**]
      !x=x+1
    else
    #orangered:<<implicit>>\n**Upgradable = False**/
      -[#orangered]-> yes;
    endif
    if ((x) [Available = False] Exists) then
      !x=x+1
      -[#springgreen]-> no;
      #springgreen:(x) Set **Available = True**]
      !x=x+1
    else
      -[#orangered]-> yes;
      #orangered:<<implicit>>\n**Available = False**/
    endif
  endif
endif
end
@enduml