---
kind: HostPathProvisioner
apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  storagePools:
    - name: local
      pvcTemplate:
        storageClassName: local-block-hpp
        volumeMode: Block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      path: "/var/hpvolumes"
  workload:
    nodeSelector:
      kubernetes.io/os: linux
