---
kind: HostPathProvisioner
apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  pathConfig:
    path: "/var/hpvolumes"
    useNamingPrefix: false
