//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by the fg-conversion-generator tool; DO NOT EDIT.
// the sources for this file are the pkg/featuregatedetails/feature-gates.json file,
// for the feature gate statuses, and api/v1beta1/hyperconverged_types.go, for the
// v1beta1 feature gate fields and json names.
//
// to re-generate, run:
//   make generate-feature-gates

package v1beta1

import (
	"slices"

	hcofg "github.com/kubevirt/hyperconverged-cluster-operator/api/v1/featuregates"
)

func convert_v1beta1_FeatureGates_To_v1(in *HyperConvergedFeatureGates, out *hcofg.HyperConvergedFeatureGates) {
	var (
		v1Idx     int
		v1Found   bool
		v1Enabled bool
	)

	// converting the DecentralizedLiveMigration v1beta1 beta feature gate to v1
	v1Idx = out.Index("decentralizedLiveMigration")
	v1Found = v1Idx >= 0
	if in.DecentralizedLiveMigration == nil {
		if v1Found {
			*out = slices.Delete(*out, v1Idx, v1Idx+1)
		}
	} else {
		v1Enabled = v1Found && ((*out)[v1Idx].State == nil || *((*out)[v1Idx].State) == "Enabled")
		if (!v1Found && !*in.DecentralizedLiveMigration) || (v1Found && v1Enabled != *in.DecentralizedLiveMigration) {
			if *in.DecentralizedLiveMigration {
				out.Enable("decentralizedLiveMigration")
			} else {
				out.Disable("decentralizedLiveMigration")
			}
		}
	}

	// converting the DeclarativeHotplugVolumes v1beta1 beta feature gate to v1
	v1Idx = out.Index("declarativeHotplugVolumes")
	v1Found = v1Idx >= 0
	if in.DeclarativeHotplugVolumes == nil {
		if v1Found {
			*out = slices.Delete(*out, v1Idx, v1Idx+1)
		}
	} else {
		v1Enabled = v1Found && ((*out)[v1Idx].State == nil || *((*out)[v1Idx].State) == "Enabled")
		if (!v1Found && !*in.DeclarativeHotplugVolumes) || (v1Found && v1Enabled != *in.DeclarativeHotplugVolumes) {
			if *in.DeclarativeHotplugVolumes {
				out.Enable("declarativeHotplugVolumes")
			} else {
				out.Disable("declarativeHotplugVolumes")
			}
		}
	}

	// converting the AlignCPUs v1beta1 alpha feature gate to v1
	v1Idx = out.Index("alignCPUs")
	v1Found = v1Idx >= 0
	if in.AlignCPUs == nil {
		if v1Found {
			*out = slices.Delete(*out, v1Idx, v1Idx+1)
		}
	} else {
		v1Enabled = v1Found && ((*out)[v1Idx].State == nil || *((*out)[v1Idx].State) == "Enabled")
		if (!v1Found && *in.AlignCPUs) || (v1Found && v1Enabled != *in.AlignCPUs) {
			if *in.AlignCPUs {
				out.Enable("alignCPUs")
			} else {
				out.Disable("alignCPUs")
			}
		}
	}

	// converting the ContainerPathVolumes v1beta1 alpha feature gate to v1
	v1Idx = out.Index("containerPathVolumes")
	v1Found = v1Idx >= 0
	if in.ContainerPathVolumes == nil {
		if v1Found {
			*out = slices.Delete(*out, v1Idx, v1Idx+1)
		}
	} else {
		v1Enabled = v1Found && ((*out)[v1Idx].State == nil || *((*out)[v1Idx].State) == "Enabled")
		if (!v1Found && *in.ContainerPathVolumes) || (v1Found && v1Enabled != *in.ContainerPathVolumes) {
			if *in.ContainerPathVolumes {
				out.Enable("containerPathVolumes")
			} else {
				out.Disable("containerPathVolumes")
			}
		}
	}

	// converting the DeployKubeSecondaryDNS v1beta1 alpha feature gate to v1
	v1Idx = out.Index("deployKubeSecondaryDNS")
	v1Found = v1Idx >= 0
	if in.DeployKubeSecondaryDNS == nil {
		if v1Found {
			*out = slices.Delete(*out, v1Idx, v1Idx+1)
		}
	} else {
		v1Enabled = v1Found && ((*out)[v1Idx].State == nil || *((*out)[v1Idx].State) == "Enabled")
		if (!v1Found && *in.DeployKubeSecondaryDNS) || (v1Found && v1Enabled != *in.DeployKubeSecondaryDNS) {
			if *in.DeployKubeSecondaryDNS {
				out.Enable("deployKubeSecondaryDNS")
			} else {
				out.Disable("deployKubeSecondaryDNS")
			}
		}
	}

	// converting the DownwardMetrics v1beta1 alpha feature gate to v1
	v1Idx = out.Index("downwardMetrics")
	v1Found = v1Idx >= 0
	if in.DownwardMetrics == nil {
		if v1Found {
			*out = slices.Delete(*out, v1Idx, v1Idx+1)
		}
	} else {
		v1Enabled = v1Found && ((*out)[v1Idx].State == nil || *((*out)[v1Idx].State) == "Enabled")
		if (!v1Found && *in.DownwardMetrics) || (v1Found && v1Enabled != *in.DownwardMetrics) {
			if *in.DownwardMetrics {
				out.Enable("downwardMetrics")
			} else {
				out.Disable("downwardMetrics")
			}
		}
	}

	// converting the EnableMultiArchBootImageImport v1beta1 alpha feature gate to v1
	v1Idx = out.Index("enableMultiArchBootImageImport")
	v1Found = v1Idx >= 0
	if in.EnableMultiArchBootImageImport == nil {
		if v1Found {
			*out = slices.Delete(*out, v1Idx, v1Idx+1)
		}
	} else {
		v1Enabled = v1Found && ((*out)[v1Idx].State == nil || *((*out)[v1Idx].State) == "Enabled")
		if (!v1Found && *in.EnableMultiArchBootImageImport) || (v1Found && v1Enabled != *in.EnableMultiArchBootImageImport) {
			if *in.EnableMultiArchBootImageImport {
				out.Enable("enableMultiArchBootImageImport")
			} else {
				out.Disable("enableMultiArchBootImageImport")
			}
		}
	}

	// converting the IncrementalBackup v1beta1 alpha feature gate to v1
	v1Idx = out.Index("incrementalBackup")
	v1Found = v1Idx >= 0
	if in.IncrementalBackup == nil {
		if v1Found {
			*out = slices.Delete(*out, v1Idx, v1Idx+1)
		}
	} else {
		v1Enabled = v1Found && ((*out)[v1Idx].State == nil || *((*out)[v1Idx].State) == "Enabled")
		if (!v1Found && *in.IncrementalBackup) || (v1Found && v1Enabled != *in.IncrementalBackup) {
			if *in.IncrementalBackup {
				out.Enable("incrementalBackup")
			} else {
				out.Disable("incrementalBackup")
			}
		}
	}

	// converting the ObjectGraph v1beta1 alpha feature gate to v1
	v1Idx = out.Index("objectGraph")
	v1Found = v1Idx >= 0
	if in.ObjectGraph == nil {
		if v1Found {
			*out = slices.Delete(*out, v1Idx, v1Idx+1)
		}
	} else {
		v1Enabled = v1Found && ((*out)[v1Idx].State == nil || *((*out)[v1Idx].State) == "Enabled")
		if (!v1Found && *in.ObjectGraph) || (v1Found && v1Enabled != *in.ObjectGraph) {
			if *in.ObjectGraph {
				out.Enable("objectGraph")
			} else {
				out.Disable("objectGraph")
			}
		}
	}

	// the DisableMDevConfiguration feature gate is deprecated and should have a custom conversion logic in api/v1beta1/conversion.go

	// the PersistentReservation feature gate is deprecated and should have a custom conversion logic in api/v1beta1/conversion.go
}

func convert_v1_FeatureGates_To_v1beta1(in hcofg.HyperConvergedFeatureGates, out *HyperConvergedFeatureGates) {
	// converting the decentralizedLiveMigration v1 beta feature gate to v1beta1
	out.DecentralizedLiveMigration = new(in.IsEnabled("decentralizedLiveMigration"))

	// converting the declarativeHotplugVolumes v1 beta feature gate to v1beta1
	out.DeclarativeHotplugVolumes = new(in.IsEnabled("declarativeHotplugVolumes"))

	// converting the alignCPUs v1 alpha feature gate to v1beta1
	out.AlignCPUs = new(in.IsEnabled("alignCPUs"))

	// converting the containerPathVolumes v1 alpha feature gate to v1beta1
	out.ContainerPathVolumes = new(in.IsEnabled("containerPathVolumes"))

	// converting the deployKubeSecondaryDNS v1 alpha feature gate to v1beta1
	out.DeployKubeSecondaryDNS = new(in.IsEnabled("deployKubeSecondaryDNS"))

	// converting the downwardMetrics v1 alpha feature gate to v1beta1
	out.DownwardMetrics = new(in.IsEnabled("downwardMetrics"))

	// converting the enableMultiArchBootImageImport v1 alpha feature gate to v1beta1
	out.EnableMultiArchBootImageImport = new(in.IsEnabled("enableMultiArchBootImageImport"))

	// converting the incrementalBackup v1 alpha feature gate to v1beta1
	out.IncrementalBackup = new(in.IsEnabled("incrementalBackup"))

	// converting the objectGraph v1 alpha feature gate to v1beta1
	out.ObjectGraph = new(in.IsEnabled("objectGraph"))

	// the disableMDevConfiguration feature gate is deprecated and should have a custom conversion logic in api/v1beta1/conversion.go

	// the persistentReservation feature gate is deprecated and should have a custom conversion logic in api/v1beta1/conversion.go
}
