//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by the fg-conversion-generator tool; DO NOT EDIT.
// the sources for this file are the pkg/featuregatedetails/feature-gates.json file,
// for the feature gate statuses, and api/v1beta1/hyperconverged_types.go, for the
// v1beta1 feature gate fields and json names.
//
// to re-generate, run:
//   make generate-feature-gates

package v1beta1

import (
	"k8s.io/utils/ptr"

	hcofg "github.com/kubevirt/hyperconverged-cluster-operator/api/v1/featuregates"
)

func convert_v1beta1_FeatureGates_To_v1(in *HyperConvergedFeatureGates, out *hcofg.HyperConvergedFeatureGates) {
	// converting the DecentralizedLiveMigration v1beta1 beta feature gate to v1
	if !ptr.Deref(in.DecentralizedLiveMigration, true) {
		out.Disable("decentralizedLiveMigration")
	}

	// converting the VideoConfig v1beta1 beta feature gate to v1
	if !ptr.Deref(in.VideoConfig, true) {
		out.Disable("videoConfig")
	}

	// converting the AlignCPUs v1beta1 alpha feature gate to v1
	if ptr.Deref(in.AlignCPUs, false) {
		out.Enable("alignCPUs")
	}

	// converting the ContainerPathVolumes v1beta1 alpha feature gate to v1
	if ptr.Deref(in.ContainerPathVolumes, false) {
		out.Enable("containerPathVolumes")
	}

	// converting the DeclarativeHotplugVolumes v1beta1 alpha feature gate to v1
	if ptr.Deref(in.DeclarativeHotplugVolumes, false) {
		out.Enable("declarativeHotplugVolumes")
	}

	// converting the DeployKubeSecondaryDNS v1beta1 alpha feature gate to v1
	if ptr.Deref(in.DeployKubeSecondaryDNS, false) {
		out.Enable("deployKubeSecondaryDNS")
	}

	// converting the DownwardMetrics v1beta1 alpha feature gate to v1
	if ptr.Deref(in.DownwardMetrics, false) {
		out.Enable("downwardMetrics")
	}

	// converting the EnableMultiArchBootImageImport v1beta1 alpha feature gate to v1
	if ptr.Deref(in.EnableMultiArchBootImageImport, false) {
		out.Enable("enableMultiArchBootImageImport")
	}

	// converting the IncrementalBackup v1beta1 alpha feature gate to v1
	if ptr.Deref(in.IncrementalBackup, false) {
		out.Enable("incrementalBackup")
	}

	// converting the ObjectGraph v1beta1 alpha feature gate to v1
	if ptr.Deref(in.ObjectGraph, false) {
		out.Enable("objectGraph")
	}

	// converting the PersistentReservation v1beta1 alpha feature gate to v1
	if ptr.Deref(in.PersistentReservation, false) {
		out.Enable("persistentReservation")
	}

	// the DisableMDevConfiguration feature gate is deprecated and should have a custom conversion logic in api/v1beta1/conversion.go
}

func convert_v1_FeatureGates_To_v1beta1(in hcofg.HyperConvergedFeatureGates, out *HyperConvergedFeatureGates) {
	// converting the decentralizedLiveMigration v1 beta feature gate to v1beta1
	out.DecentralizedLiveMigration = new(in.IsEnabled("decentralizedLiveMigration"))

	// converting the videoConfig v1 beta feature gate to v1beta1
	out.VideoConfig = new(in.IsEnabled("videoConfig"))

	// converting the alignCPUs v1 alpha feature gate to v1beta1
	out.AlignCPUs = new(in.IsEnabled("alignCPUs"))

	// converting the containerPathVolumes v1 alpha feature gate to v1beta1
	out.ContainerPathVolumes = new(in.IsEnabled("containerPathVolumes"))

	// converting the declarativeHotplugVolumes v1 alpha feature gate to v1beta1
	out.DeclarativeHotplugVolumes = new(in.IsEnabled("declarativeHotplugVolumes"))

	// converting the deployKubeSecondaryDNS v1 alpha feature gate to v1beta1
	out.DeployKubeSecondaryDNS = new(in.IsEnabled("deployKubeSecondaryDNS"))

	// converting the downwardMetrics v1 alpha feature gate to v1beta1
	out.DownwardMetrics = new(in.IsEnabled("downwardMetrics"))

	// converting the enableMultiArchBootImageImport v1 alpha feature gate to v1beta1
	out.EnableMultiArchBootImageImport = new(in.IsEnabled("enableMultiArchBootImageImport"))

	// converting the incrementalBackup v1 alpha feature gate to v1beta1
	out.IncrementalBackup = new(in.IsEnabled("incrementalBackup"))

	// converting the objectGraph v1 alpha feature gate to v1beta1
	out.ObjectGraph = new(in.IsEnabled("objectGraph"))

	// converting the persistentReservation v1 alpha feature gate to v1beta1
	out.PersistentReservation = new(in.IsEnabled("persistentReservation"))

	// the disableMDevConfiguration feature gate is deprecated and should have a custom conversion logic in api/v1beta1/conversion.go
}
