//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by fg-json-generator; DO NOT EDIT.

package v1beta1

import (
	"k8s.io/utils/ptr"

	hcofg "github.com/kubevirt/hyperconverged-cluster-operator/api/v1/featuregates"
)

func convert_v1beta1_FeatureGates_To_v1(in *HyperConvergedFeatureGates, out *hcofg.HyperConvergedFeatureGates) {
	if ptr.Deref(in.DownwardMetrics, false) {
		out.Enable("downwardMetrics")
	}

	if ptr.Deref(in.DeployKubeSecondaryDNS, false) {
		out.Enable("deployKubeSecondaryDNS")
	}

	if ptr.Deref(in.DisableMDevConfiguration, false) {
		out.Enable("disableMDevConfiguration")
	}

	if ptr.Deref(in.PersistentReservation, false) {
		out.Enable("persistentReservation")
	}

	if ptr.Deref(in.AlignCPUs, false) {
		out.Enable("alignCPUs")
	}

	if ptr.Deref(in.EnableMultiArchBootImageImport, false) {
		out.Enable("enableMultiArchBootImageImport")
	}

	if !ptr.Deref(in.DecentralizedLiveMigration, true) {
		out.Disable("decentralizedLiveMigration")
	}

	if ptr.Deref(in.DeclarativeHotplugVolumes, false) {
		out.Enable("declarativeHotplugVolumes")
	}

	if !ptr.Deref(in.VideoConfig, true) {
		out.Disable("videoConfig")
	}

	if ptr.Deref(in.ObjectGraph, false) {
		out.Enable("objectGraph")
	}

	if ptr.Deref(in.IncrementalBackup, false) {
		out.Enable("incrementalBackup")
	}

	if ptr.Deref(in.InheritScratchSpaceStorageClass, false) {
		out.Enable("inheritScratchSpaceStorageClass")
	}
}

func convert_v1_FeatureGates_To_v1beta1(in hcofg.HyperConvergedFeatureGates, out *HyperConvergedFeatureGates) {
	out.DownwardMetrics = ptr.To(in.IsEnabled("downwardMetrics"))
	out.DeployKubeSecondaryDNS = ptr.To(in.IsEnabled("deployKubeSecondaryDNS"))
	out.DisableMDevConfiguration = ptr.To(in.IsEnabled("disableMDevConfiguration"))
	out.PersistentReservation = ptr.To(in.IsEnabled("persistentReservation"))
	out.AlignCPUs = ptr.To(in.IsEnabled("alignCPUs"))
	out.EnableMultiArchBootImageImport = ptr.To(in.IsEnabled("enableMultiArchBootImageImport"))
	out.DecentralizedLiveMigration = ptr.To(in.IsEnabled("decentralizedLiveMigration"))
	out.DeclarativeHotplugVolumes = ptr.To(in.IsEnabled("declarativeHotplugVolumes"))
	out.VideoConfig = ptr.To(in.IsEnabled("videoConfig"))
	out.ObjectGraph = ptr.To(in.IsEnabled("objectGraph"))
	out.IncrementalBackup = ptr.To(in.IsEnabled("incrementalBackup"))
	out.InheritScratchSpaceStorageClass = ptr.To(in.IsEnabled("inheritScratchSpaceStorageClass"))
}