//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * This file is part of the KubeVirt project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2026 Red Hat, Inc.
 *
 */

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	v1 "github.com/kubevirt/hyperconverged-cluster-operator/api/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1alpha1 "kubevirt.io/application-aware-quota/staging/src/kubevirt.io/application-aware-quota-api/pkg/apis/core/v1alpha1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ApplicationAwareConfigurations)(nil), (*v1.ApplicationAwareConfigurations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ApplicationAwareConfigurations_To_v1_ApplicationAwareConfigurations(a.(*ApplicationAwareConfigurations), b.(*v1.ApplicationAwareConfigurations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ApplicationAwareConfigurations)(nil), (*ApplicationAwareConfigurations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ApplicationAwareConfigurations_To_v1beta1_ApplicationAwareConfigurations(a.(*v1.ApplicationAwareConfigurations), b.(*ApplicationAwareConfigurations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HyperConverged)(nil), (*v1.HyperConverged)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HyperConverged_To_v1_HyperConverged(a.(*HyperConverged), b.(*v1.HyperConverged), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HyperConverged)(nil), (*HyperConverged)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HyperConverged_To_v1beta1_HyperConverged(a.(*v1.HyperConverged), b.(*HyperConverged), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HyperConvergedList)(nil), (*v1.HyperConvergedList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HyperConvergedList_To_v1_HyperConvergedList(a.(*HyperConvergedList), b.(*v1.HyperConvergedList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HyperConvergedList)(nil), (*HyperConvergedList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HyperConvergedList_To_v1beta1_HyperConvergedList(a.(*v1.HyperConvergedList), b.(*HyperConvergedList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HyperConvergedSpec)(nil), (*v1.HyperConvergedSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HyperConvergedSpec_To_v1_HyperConvergedSpec(a.(*HyperConvergedSpec), b.(*v1.HyperConvergedSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HyperConvergedSpec)(nil), (*HyperConvergedSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HyperConvergedSpec_To_v1beta1_HyperConvergedSpec(a.(*v1.HyperConvergedSpec), b.(*HyperConvergedSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MediatedDevicesConfiguration)(nil), (*v1.MediatedDevicesConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MediatedDevicesConfiguration_To_v1_MediatedDevicesConfiguration(a.(*MediatedDevicesConfiguration), b.(*v1.MediatedDevicesConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.MediatedDevicesConfiguration)(nil), (*MediatedDevicesConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_MediatedDevicesConfiguration_To_v1beta1_MediatedDevicesConfiguration(a.(*v1.MediatedDevicesConfiguration), b.(*MediatedDevicesConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeMediatedDeviceTypesConfig)(nil), (*v1.NodeMediatedDeviceTypesConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NodeMediatedDeviceTypesConfig_To_v1_NodeMediatedDeviceTypesConfig(a.(*NodeMediatedDeviceTypesConfig), b.(*v1.NodeMediatedDeviceTypesConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.NodeMediatedDeviceTypesConfig)(nil), (*NodeMediatedDeviceTypesConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_NodeMediatedDeviceTypesConfig_To_v1beta1_NodeMediatedDeviceTypesConfig(a.(*v1.NodeMediatedDeviceTypesConfig), b.(*NodeMediatedDeviceTypesConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_ApplicationAwareConfigurations_To_v1_ApplicationAwareConfigurations(in *ApplicationAwareConfigurations, out *v1.ApplicationAwareConfigurations, s conversion.Scope) error {
	out.VmiCalcConfigName = (*v1alpha1.VmiCalcConfigName)(unsafe.Pointer(in.VmiCalcConfigName))
	out.NamespaceSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.NamespaceSelector))
	out.AllowApplicationAwareClusterResourceQuota = in.AllowApplicationAwareClusterResourceQuota
	return nil
}

// Convert_v1beta1_ApplicationAwareConfigurations_To_v1_ApplicationAwareConfigurations is an autogenerated conversion function.
func Convert_v1beta1_ApplicationAwareConfigurations_To_v1_ApplicationAwareConfigurations(in *ApplicationAwareConfigurations, out *v1.ApplicationAwareConfigurations, s conversion.Scope) error {
	return autoConvert_v1beta1_ApplicationAwareConfigurations_To_v1_ApplicationAwareConfigurations(in, out, s)
}

func autoConvert_v1_ApplicationAwareConfigurations_To_v1beta1_ApplicationAwareConfigurations(in *v1.ApplicationAwareConfigurations, out *ApplicationAwareConfigurations, s conversion.Scope) error {
	// INFO: in.Enable opted out of conversion generation
	out.VmiCalcConfigName = (*v1alpha1.VmiCalcConfigName)(unsafe.Pointer(in.VmiCalcConfigName))
	out.NamespaceSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.NamespaceSelector))
	out.AllowApplicationAwareClusterResourceQuota = in.AllowApplicationAwareClusterResourceQuota
	return nil
}

// Convert_v1_ApplicationAwareConfigurations_To_v1beta1_ApplicationAwareConfigurations is an autogenerated conversion function.
func Convert_v1_ApplicationAwareConfigurations_To_v1beta1_ApplicationAwareConfigurations(in *v1.ApplicationAwareConfigurations, out *ApplicationAwareConfigurations, s conversion.Scope) error {
	return autoConvert_v1_ApplicationAwareConfigurations_To_v1beta1_ApplicationAwareConfigurations(in, out, s)
}

func autoConvert_v1beta1_HyperConverged_To_v1_HyperConverged(in *HyperConverged, out *v1.HyperConverged, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_HyperConvergedSpec_To_v1_HyperConvergedSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = in.Status
	return nil
}

// Convert_v1beta1_HyperConverged_To_v1_HyperConverged is an autogenerated conversion function.
func Convert_v1beta1_HyperConverged_To_v1_HyperConverged(in *HyperConverged, out *v1.HyperConverged, s conversion.Scope) error {
	return autoConvert_v1beta1_HyperConverged_To_v1_HyperConverged(in, out, s)
}

func autoConvert_v1_HyperConverged_To_v1beta1_HyperConverged(in *v1.HyperConverged, out *HyperConverged, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_HyperConvergedSpec_To_v1beta1_HyperConvergedSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = in.Status
	return nil
}

// Convert_v1_HyperConverged_To_v1beta1_HyperConverged is an autogenerated conversion function.
func Convert_v1_HyperConverged_To_v1beta1_HyperConverged(in *v1.HyperConverged, out *HyperConverged, s conversion.Scope) error {
	return autoConvert_v1_HyperConverged_To_v1beta1_HyperConverged(in, out, s)
}

func autoConvert_v1beta1_HyperConvergedList_To_v1_HyperConvergedList(in *HyperConvergedList, out *v1.HyperConvergedList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1.HyperConverged, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_HyperConverged_To_v1_HyperConverged(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_HyperConvergedList_To_v1_HyperConvergedList is an autogenerated conversion function.
func Convert_v1beta1_HyperConvergedList_To_v1_HyperConvergedList(in *HyperConvergedList, out *v1.HyperConvergedList, s conversion.Scope) error {
	return autoConvert_v1beta1_HyperConvergedList_To_v1_HyperConvergedList(in, out, s)
}

func autoConvert_v1_HyperConvergedList_To_v1beta1_HyperConvergedList(in *v1.HyperConvergedList, out *HyperConvergedList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HyperConverged, len(*in))
		for i := range *in {
			if err := Convert_v1_HyperConverged_To_v1beta1_HyperConverged(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1_HyperConvergedList_To_v1beta1_HyperConvergedList is an autogenerated conversion function.
func Convert_v1_HyperConvergedList_To_v1beta1_HyperConvergedList(in *v1.HyperConvergedList, out *HyperConvergedList, s conversion.Scope) error {
	return autoConvert_v1_HyperConvergedList_To_v1beta1_HyperConvergedList(in, out, s)
}

func autoConvert_v1beta1_HyperConvergedSpec_To_v1_HyperConvergedSpec(in *HyperConvergedSpec, out *v1.HyperConvergedSpec, s conversion.Scope) error {
	// INFO: in.LocalStorageClassName opted out of conversion generation
	// INFO: in.TuningPolicy opted out of conversion generation
	// INFO: in.Infra opted out of conversion generation
	// INFO: in.Workloads opted out of conversion generation
	// INFO: in.FeatureGates opted out of conversion generation
	// INFO: in.LiveMigrationConfig opted out of conversion generation
	// INFO: in.PermittedHostDevices opted out of conversion generation
	// INFO: in.MediatedDevicesConfiguration opted out of conversion generation
	// INFO: in.CertConfig opted out of conversion generation
	// INFO: in.ResourceRequirements opted out of conversion generation
	// INFO: in.ScratchSpaceStorageClass opted out of conversion generation
	// INFO: in.VddkInitImage opted out of conversion generation
	// INFO: in.DefaultCPUModel opted out of conversion generation
	// INFO: in.DefaultRuntimeClass opted out of conversion generation
	// INFO: in.ObsoleteCPUs opted out of conversion generation
	// INFO: in.CommonTemplatesNamespace opted out of conversion generation
	// INFO: in.StorageImport opted out of conversion generation
	// INFO: in.WorkloadUpdateStrategy opted out of conversion generation
	// INFO: in.DataImportCronTemplates opted out of conversion generation
	// INFO: in.FilesystemOverhead opted out of conversion generation
	// INFO: in.UninstallStrategy opted out of conversion generation
	// INFO: in.LogVerbosityConfig opted out of conversion generation
	// INFO: in.TLSSecurityProfile opted out of conversion generation
	// INFO: in.TektonPipelinesNamespace opted out of conversion generation
	// INFO: in.TektonTasksNamespace opted out of conversion generation
	// INFO: in.KubeSecondaryDNSNameServerIP opted out of conversion generation
	// INFO: in.KubeMacPoolConfiguration opted out of conversion generation
	// INFO: in.EvictionStrategy opted out of conversion generation
	// INFO: in.VMStateStorageClass opted out of conversion generation
	// INFO: in.VirtualMachineOptions opted out of conversion generation
	// INFO: in.CommonBootImageNamespace opted out of conversion generation
	// INFO: in.KSMConfiguration opted out of conversion generation
	// INFO: in.NetworkBinding opted out of conversion generation
	// INFO: in.ApplicationAwareConfig opted out of conversion generation
	// INFO: in.HigherWorkloadDensity opted out of conversion generation
	// INFO: in.EnableCommonBootImageImport opted out of conversion generation
	// INFO: in.InstancetypeConfig opted out of conversion generation
	// INFO: in.CommonInstancetypesDeployment opted out of conversion generation
	// INFO: in.DeployVMConsoleProxy opted out of conversion generation
	// INFO: in.EnableApplicationAwareQuota opted out of conversion generation
	// INFO: in.LiveUpdateConfiguration opted out of conversion generation
	// INFO: in.Hypervisors opted out of conversion generation
	// INFO: in.RoleAggregationStrategy opted out of conversion generation
	return nil
}

// Convert_v1beta1_HyperConvergedSpec_To_v1_HyperConvergedSpec is an autogenerated conversion function.
func Convert_v1beta1_HyperConvergedSpec_To_v1_HyperConvergedSpec(in *HyperConvergedSpec, out *v1.HyperConvergedSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_HyperConvergedSpec_To_v1_HyperConvergedSpec(in, out, s)
}

func autoConvert_v1_HyperConvergedSpec_To_v1beta1_HyperConvergedSpec(in *v1.HyperConvergedSpec, out *HyperConvergedSpec, s conversion.Scope) error {
	// INFO: in.FeatureGates opted out of conversion generation
	// INFO: in.Virtualization opted out of conversion generation
	// INFO: in.Storage opted out of conversion generation
	// INFO: in.Networking opted out of conversion generation
	// INFO: in.WorkloadSources opted out of conversion generation
	// INFO: in.Security opted out of conversion generation
	// INFO: in.Deployment opted out of conversion generation
	return nil
}

// Convert_v1_HyperConvergedSpec_To_v1beta1_HyperConvergedSpec is an autogenerated conversion function.
func Convert_v1_HyperConvergedSpec_To_v1beta1_HyperConvergedSpec(in *v1.HyperConvergedSpec, out *HyperConvergedSpec, s conversion.Scope) error {
	return autoConvert_v1_HyperConvergedSpec_To_v1beta1_HyperConvergedSpec(in, out, s)
}

func autoConvert_v1beta1_MediatedDevicesConfiguration_To_v1_MediatedDevicesConfiguration(in *MediatedDevicesConfiguration, out *v1.MediatedDevicesConfiguration, s conversion.Scope) error {
	out.MediatedDeviceTypes = *(*[]string)(unsafe.Pointer(&in.MediatedDeviceTypes))
	// INFO: in.MediatedDevicesTypes opted out of conversion generation
	if in.NodeMediatedDeviceTypes != nil {
		in, out := &in.NodeMediatedDeviceTypes, &out.NodeMediatedDeviceTypes
		*out = make([]v1.NodeMediatedDeviceTypesConfig, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_NodeMediatedDeviceTypesConfig_To_v1_NodeMediatedDeviceTypesConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.NodeMediatedDeviceTypes = nil
	}
	return nil
}

// Convert_v1beta1_MediatedDevicesConfiguration_To_v1_MediatedDevicesConfiguration is an autogenerated conversion function.
func Convert_v1beta1_MediatedDevicesConfiguration_To_v1_MediatedDevicesConfiguration(in *MediatedDevicesConfiguration, out *v1.MediatedDevicesConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_MediatedDevicesConfiguration_To_v1_MediatedDevicesConfiguration(in, out, s)
}

func autoConvert_v1_MediatedDevicesConfiguration_To_v1beta1_MediatedDevicesConfiguration(in *v1.MediatedDevicesConfiguration, out *MediatedDevicesConfiguration, s conversion.Scope) error {
	out.MediatedDeviceTypes = *(*[]string)(unsafe.Pointer(&in.MediatedDeviceTypes))
	if in.NodeMediatedDeviceTypes != nil {
		in, out := &in.NodeMediatedDeviceTypes, &out.NodeMediatedDeviceTypes
		*out = make([]NodeMediatedDeviceTypesConfig, len(*in))
		for i := range *in {
			if err := Convert_v1_NodeMediatedDeviceTypesConfig_To_v1beta1_NodeMediatedDeviceTypesConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.NodeMediatedDeviceTypes = nil
	}
	return nil
}

// Convert_v1_MediatedDevicesConfiguration_To_v1beta1_MediatedDevicesConfiguration is an autogenerated conversion function.
func Convert_v1_MediatedDevicesConfiguration_To_v1beta1_MediatedDevicesConfiguration(in *v1.MediatedDevicesConfiguration, out *MediatedDevicesConfiguration, s conversion.Scope) error {
	return autoConvert_v1_MediatedDevicesConfiguration_To_v1beta1_MediatedDevicesConfiguration(in, out, s)
}

func autoConvert_v1beta1_NodeMediatedDeviceTypesConfig_To_v1_NodeMediatedDeviceTypesConfig(in *NodeMediatedDeviceTypesConfig, out *v1.NodeMediatedDeviceTypesConfig, s conversion.Scope) error {
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.MediatedDeviceTypes = *(*[]string)(unsafe.Pointer(&in.MediatedDeviceTypes))
	// INFO: in.MediatedDevicesTypes opted out of conversion generation
	return nil
}

// Convert_v1beta1_NodeMediatedDeviceTypesConfig_To_v1_NodeMediatedDeviceTypesConfig is an autogenerated conversion function.
func Convert_v1beta1_NodeMediatedDeviceTypesConfig_To_v1_NodeMediatedDeviceTypesConfig(in *NodeMediatedDeviceTypesConfig, out *v1.NodeMediatedDeviceTypesConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_NodeMediatedDeviceTypesConfig_To_v1_NodeMediatedDeviceTypesConfig(in, out, s)
}

func autoConvert_v1_NodeMediatedDeviceTypesConfig_To_v1beta1_NodeMediatedDeviceTypesConfig(in *v1.NodeMediatedDeviceTypesConfig, out *NodeMediatedDeviceTypesConfig, s conversion.Scope) error {
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.MediatedDeviceTypes = *(*[]string)(unsafe.Pointer(&in.MediatedDeviceTypes))
	return nil
}

// Convert_v1_NodeMediatedDeviceTypesConfig_To_v1beta1_NodeMediatedDeviceTypesConfig is an autogenerated conversion function.
func Convert_v1_NodeMediatedDeviceTypesConfig_To_v1beta1_NodeMediatedDeviceTypesConfig(in *v1.NodeMediatedDeviceTypesConfig, out *NodeMediatedDeviceTypesConfig, s conversion.Scope) error {
	return autoConvert_v1_NodeMediatedDeviceTypesConfig_To_v1beta1_NodeMediatedDeviceTypesConfig(in, out, s)
}
