//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * This file is part of the KubeVirt project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2026 Red Hat, Inc.
 *
 */

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	v1 "github.com/kubevirt/hyperconverged-cluster-operator/api/v1"
	configv1 "github.com/openshift/api/config/v1"
	apicorev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1 "kubevirt.io/api/core/v1"
	v1alpha1 "kubevirt.io/application-aware-quota/staging/src/kubevirt.io/application-aware-quota-api/pkg/apis/core/v1alpha1"
	corev1beta1 "kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1"
	api "kubevirt.io/controller-lifecycle-operator-sdk/api"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ApplicationAwareConfigurations)(nil), (*v1.ApplicationAwareConfigurations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ApplicationAwareConfigurations_To_v1_ApplicationAwareConfigurations(a.(*ApplicationAwareConfigurations), b.(*v1.ApplicationAwareConfigurations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ApplicationAwareConfigurations)(nil), (*ApplicationAwareConfigurations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ApplicationAwareConfigurations_To_v1beta1_ApplicationAwareConfigurations(a.(*v1.ApplicationAwareConfigurations), b.(*ApplicationAwareConfigurations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CertRotateConfigCA)(nil), (*v1.CertRotateConfigCA)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CertRotateConfigCA_To_v1_CertRotateConfigCA(a.(*CertRotateConfigCA), b.(*v1.CertRotateConfigCA), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CertRotateConfigCA)(nil), (*CertRotateConfigCA)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CertRotateConfigCA_To_v1beta1_CertRotateConfigCA(a.(*v1.CertRotateConfigCA), b.(*CertRotateConfigCA), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CertRotateConfigServer)(nil), (*v1.CertRotateConfigServer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_CertRotateConfigServer_To_v1_CertRotateConfigServer(a.(*CertRotateConfigServer), b.(*v1.CertRotateConfigServer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CertRotateConfigServer)(nil), (*CertRotateConfigServer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CertRotateConfigServer_To_v1beta1_CertRotateConfigServer(a.(*v1.CertRotateConfigServer), b.(*CertRotateConfigServer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DataImportCronStatus)(nil), (*v1.DataImportCronStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DataImportCronStatus_To_v1_DataImportCronStatus(a.(*DataImportCronStatus), b.(*v1.DataImportCronStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.DataImportCronStatus)(nil), (*DataImportCronStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_DataImportCronStatus_To_v1beta1_DataImportCronStatus(a.(*v1.DataImportCronStatus), b.(*DataImportCronStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DataImportCronTemplate)(nil), (*v1.DataImportCronTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DataImportCronTemplate_To_v1_DataImportCronTemplate(a.(*DataImportCronTemplate), b.(*v1.DataImportCronTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.DataImportCronTemplate)(nil), (*DataImportCronTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_DataImportCronTemplate_To_v1beta1_DataImportCronTemplate(a.(*v1.DataImportCronTemplate), b.(*DataImportCronTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DataImportCronTemplateStatus)(nil), (*v1.DataImportCronTemplateStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DataImportCronTemplateStatus_To_v1_DataImportCronTemplateStatus(a.(*DataImportCronTemplateStatus), b.(*v1.DataImportCronTemplateStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.DataImportCronTemplateStatus)(nil), (*DataImportCronTemplateStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_DataImportCronTemplateStatus_To_v1beta1_DataImportCronTemplateStatus(a.(*v1.DataImportCronTemplateStatus), b.(*DataImportCronTemplateStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HigherWorkloadDensityConfiguration)(nil), (*v1.HigherWorkloadDensityConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HigherWorkloadDensityConfiguration_To_v1_HigherWorkloadDensityConfiguration(a.(*HigherWorkloadDensityConfiguration), b.(*v1.HigherWorkloadDensityConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HigherWorkloadDensityConfiguration)(nil), (*HigherWorkloadDensityConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HigherWorkloadDensityConfiguration_To_v1beta1_HigherWorkloadDensityConfiguration(a.(*v1.HigherWorkloadDensityConfiguration), b.(*HigherWorkloadDensityConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HyperConverged)(nil), (*v1.HyperConverged)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HyperConverged_To_v1_HyperConverged(a.(*HyperConverged), b.(*v1.HyperConverged), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HyperConverged)(nil), (*HyperConverged)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HyperConverged_To_v1beta1_HyperConverged(a.(*v1.HyperConverged), b.(*HyperConverged), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HyperConvergedCertConfig)(nil), (*v1.HyperConvergedCertConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HyperConvergedCertConfig_To_v1_HyperConvergedCertConfig(a.(*HyperConvergedCertConfig), b.(*v1.HyperConvergedCertConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HyperConvergedCertConfig)(nil), (*HyperConvergedCertConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HyperConvergedCertConfig_To_v1beta1_HyperConvergedCertConfig(a.(*v1.HyperConvergedCertConfig), b.(*HyperConvergedCertConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HyperConvergedConfig)(nil), (*v1.HyperConvergedConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HyperConvergedConfig_To_v1_HyperConvergedConfig(a.(*HyperConvergedConfig), b.(*v1.HyperConvergedConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HyperConvergedConfig)(nil), (*HyperConvergedConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HyperConvergedConfig_To_v1beta1_HyperConvergedConfig(a.(*v1.HyperConvergedConfig), b.(*HyperConvergedConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HyperConvergedFeatureGates)(nil), (*v1.HyperConvergedFeatureGates)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HyperConvergedFeatureGates_To_v1_HyperConvergedFeatureGates(a.(*HyperConvergedFeatureGates), b.(*v1.HyperConvergedFeatureGates), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HyperConvergedFeatureGates)(nil), (*HyperConvergedFeatureGates)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HyperConvergedFeatureGates_To_v1beta1_HyperConvergedFeatureGates(a.(*v1.HyperConvergedFeatureGates), b.(*HyperConvergedFeatureGates), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HyperConvergedList)(nil), (*v1.HyperConvergedList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HyperConvergedList_To_v1_HyperConvergedList(a.(*HyperConvergedList), b.(*v1.HyperConvergedList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HyperConvergedList)(nil), (*HyperConvergedList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HyperConvergedList_To_v1beta1_HyperConvergedList(a.(*v1.HyperConvergedList), b.(*HyperConvergedList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HyperConvergedObsoleteCPUs)(nil), (*v1.HyperConvergedObsoleteCPUs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HyperConvergedObsoleteCPUs_To_v1_HyperConvergedObsoleteCPUs(a.(*HyperConvergedObsoleteCPUs), b.(*v1.HyperConvergedObsoleteCPUs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HyperConvergedObsoleteCPUs)(nil), (*HyperConvergedObsoleteCPUs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HyperConvergedObsoleteCPUs_To_v1beta1_HyperConvergedObsoleteCPUs(a.(*v1.HyperConvergedObsoleteCPUs), b.(*HyperConvergedObsoleteCPUs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HyperConvergedSpec)(nil), (*v1.HyperConvergedSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HyperConvergedSpec_To_v1_HyperConvergedSpec(a.(*HyperConvergedSpec), b.(*v1.HyperConvergedSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HyperConvergedSpec)(nil), (*HyperConvergedSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HyperConvergedSpec_To_v1beta1_HyperConvergedSpec(a.(*v1.HyperConvergedSpec), b.(*HyperConvergedSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HyperConvergedStatus)(nil), (*v1.HyperConvergedStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HyperConvergedStatus_To_v1_HyperConvergedStatus(a.(*HyperConvergedStatus), b.(*v1.HyperConvergedStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HyperConvergedStatus)(nil), (*HyperConvergedStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HyperConvergedStatus_To_v1beta1_HyperConvergedStatus(a.(*v1.HyperConvergedStatus), b.(*HyperConvergedStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HyperConvergedWorkloadUpdateStrategy)(nil), (*v1.HyperConvergedWorkloadUpdateStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HyperConvergedWorkloadUpdateStrategy_To_v1_HyperConvergedWorkloadUpdateStrategy(a.(*HyperConvergedWorkloadUpdateStrategy), b.(*v1.HyperConvergedWorkloadUpdateStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.HyperConvergedWorkloadUpdateStrategy)(nil), (*HyperConvergedWorkloadUpdateStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HyperConvergedWorkloadUpdateStrategy_To_v1beta1_HyperConvergedWorkloadUpdateStrategy(a.(*v1.HyperConvergedWorkloadUpdateStrategy), b.(*HyperConvergedWorkloadUpdateStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KubeMacPoolConfig)(nil), (*v1.KubeMacPoolConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KubeMacPoolConfig_To_v1_KubeMacPoolConfig(a.(*KubeMacPoolConfig), b.(*v1.KubeMacPoolConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.KubeMacPoolConfig)(nil), (*KubeMacPoolConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_KubeMacPoolConfig_To_v1beta1_KubeMacPoolConfig(a.(*v1.KubeMacPoolConfig), b.(*KubeMacPoolConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LiveMigrationConfigurations)(nil), (*v1.LiveMigrationConfigurations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LiveMigrationConfigurations_To_v1_LiveMigrationConfigurations(a.(*LiveMigrationConfigurations), b.(*v1.LiveMigrationConfigurations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.LiveMigrationConfigurations)(nil), (*LiveMigrationConfigurations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LiveMigrationConfigurations_To_v1beta1_LiveMigrationConfigurations(a.(*v1.LiveMigrationConfigurations), b.(*LiveMigrationConfigurations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LogVerbosityConfiguration)(nil), (*v1.LogVerbosityConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LogVerbosityConfiguration_To_v1_LogVerbosityConfiguration(a.(*LogVerbosityConfiguration), b.(*v1.LogVerbosityConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.LogVerbosityConfiguration)(nil), (*LogVerbosityConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LogVerbosityConfiguration_To_v1beta1_LogVerbosityConfiguration(a.(*v1.LogVerbosityConfiguration), b.(*LogVerbosityConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MediatedDevicesConfiguration)(nil), (*v1.MediatedDevicesConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MediatedDevicesConfiguration_To_v1_MediatedDevicesConfiguration(a.(*MediatedDevicesConfiguration), b.(*v1.MediatedDevicesConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.MediatedDevicesConfiguration)(nil), (*MediatedDevicesConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_MediatedDevicesConfiguration_To_v1beta1_MediatedDevicesConfiguration(a.(*v1.MediatedDevicesConfiguration), b.(*MediatedDevicesConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MediatedHostDevice)(nil), (*v1.MediatedHostDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MediatedHostDevice_To_v1_MediatedHostDevice(a.(*MediatedHostDevice), b.(*v1.MediatedHostDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.MediatedHostDevice)(nil), (*MediatedHostDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_MediatedHostDevice_To_v1beta1_MediatedHostDevice(a.(*v1.MediatedHostDevice), b.(*MediatedHostDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeInfoStatus)(nil), (*v1.NodeInfoStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NodeInfoStatus_To_v1_NodeInfoStatus(a.(*NodeInfoStatus), b.(*v1.NodeInfoStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.NodeInfoStatus)(nil), (*NodeInfoStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_NodeInfoStatus_To_v1beta1_NodeInfoStatus(a.(*v1.NodeInfoStatus), b.(*NodeInfoStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeMediatedDeviceTypesConfig)(nil), (*v1.NodeMediatedDeviceTypesConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NodeMediatedDeviceTypesConfig_To_v1_NodeMediatedDeviceTypesConfig(a.(*NodeMediatedDeviceTypesConfig), b.(*v1.NodeMediatedDeviceTypesConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.NodeMediatedDeviceTypesConfig)(nil), (*NodeMediatedDeviceTypesConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_NodeMediatedDeviceTypesConfig_To_v1beta1_NodeMediatedDeviceTypesConfig(a.(*v1.NodeMediatedDeviceTypesConfig), b.(*NodeMediatedDeviceTypesConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperandResourceRequirements)(nil), (*v1.OperandResourceRequirements)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OperandResourceRequirements_To_v1_OperandResourceRequirements(a.(*OperandResourceRequirements), b.(*v1.OperandResourceRequirements), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.OperandResourceRequirements)(nil), (*OperandResourceRequirements)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OperandResourceRequirements_To_v1beta1_OperandResourceRequirements(a.(*v1.OperandResourceRequirements), b.(*OperandResourceRequirements), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PciHostDevice)(nil), (*v1.PciHostDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PciHostDevice_To_v1_PciHostDevice(a.(*PciHostDevice), b.(*v1.PciHostDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.PciHostDevice)(nil), (*PciHostDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PciHostDevice_To_v1beta1_PciHostDevice(a.(*v1.PciHostDevice), b.(*PciHostDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PermittedHostDevices)(nil), (*v1.PermittedHostDevices)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PermittedHostDevices_To_v1_PermittedHostDevices(a.(*PermittedHostDevices), b.(*v1.PermittedHostDevices), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.PermittedHostDevices)(nil), (*PermittedHostDevices)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PermittedHostDevices_To_v1beta1_PermittedHostDevices(a.(*v1.PermittedHostDevices), b.(*PermittedHostDevices), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StorageImportConfig)(nil), (*v1.StorageImportConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_StorageImportConfig_To_v1_StorageImportConfig(a.(*StorageImportConfig), b.(*v1.StorageImportConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.StorageImportConfig)(nil), (*StorageImportConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_StorageImportConfig_To_v1beta1_StorageImportConfig(a.(*v1.StorageImportConfig), b.(*StorageImportConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*USBHostDevice)(nil), (*v1.USBHostDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_USBHostDevice_To_v1_USBHostDevice(a.(*USBHostDevice), b.(*v1.USBHostDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.USBHostDevice)(nil), (*USBHostDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_USBHostDevice_To_v1beta1_USBHostDevice(a.(*v1.USBHostDevice), b.(*USBHostDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*USBSelector)(nil), (*v1.USBSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_USBSelector_To_v1_USBSelector(a.(*USBSelector), b.(*v1.USBSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.USBSelector)(nil), (*USBSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_USBSelector_To_v1beta1_USBSelector(a.(*v1.USBSelector), b.(*USBSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Version)(nil), (*v1.Version)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Version_To_v1_Version(a.(*Version), b.(*v1.Version), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.Version)(nil), (*Version)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Version_To_v1beta1_Version(a.(*v1.Version), b.(*Version), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineOptions)(nil), (*v1.VirtualMachineOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineOptions_To_v1_VirtualMachineOptions(a.(*VirtualMachineOptions), b.(*v1.VirtualMachineOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.VirtualMachineOptions)(nil), (*VirtualMachineOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_VirtualMachineOptions_To_v1beta1_VirtualMachineOptions(a.(*v1.VirtualMachineOptions), b.(*VirtualMachineOptions), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_ApplicationAwareConfigurations_To_v1_ApplicationAwareConfigurations(in *ApplicationAwareConfigurations, out *v1.ApplicationAwareConfigurations, s conversion.Scope) error {
	out.VmiCalcConfigName = (*v1alpha1.VmiCalcConfigName)(unsafe.Pointer(in.VmiCalcConfigName))
	out.NamespaceSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.NamespaceSelector))
	out.AllowApplicationAwareClusterResourceQuota = in.AllowApplicationAwareClusterResourceQuota
	return nil
}

// Convert_v1beta1_ApplicationAwareConfigurations_To_v1_ApplicationAwareConfigurations is an autogenerated conversion function.
func Convert_v1beta1_ApplicationAwareConfigurations_To_v1_ApplicationAwareConfigurations(in *ApplicationAwareConfigurations, out *v1.ApplicationAwareConfigurations, s conversion.Scope) error {
	return autoConvert_v1beta1_ApplicationAwareConfigurations_To_v1_ApplicationAwareConfigurations(in, out, s)
}

func autoConvert_v1_ApplicationAwareConfigurations_To_v1beta1_ApplicationAwareConfigurations(in *v1.ApplicationAwareConfigurations, out *ApplicationAwareConfigurations, s conversion.Scope) error {
	out.VmiCalcConfigName = (*v1alpha1.VmiCalcConfigName)(unsafe.Pointer(in.VmiCalcConfigName))
	out.NamespaceSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.NamespaceSelector))
	out.AllowApplicationAwareClusterResourceQuota = in.AllowApplicationAwareClusterResourceQuota
	return nil
}

// Convert_v1_ApplicationAwareConfigurations_To_v1beta1_ApplicationAwareConfigurations is an autogenerated conversion function.
func Convert_v1_ApplicationAwareConfigurations_To_v1beta1_ApplicationAwareConfigurations(in *v1.ApplicationAwareConfigurations, out *ApplicationAwareConfigurations, s conversion.Scope) error {
	return autoConvert_v1_ApplicationAwareConfigurations_To_v1beta1_ApplicationAwareConfigurations(in, out, s)
}

func autoConvert_v1beta1_CertRotateConfigCA_To_v1_CertRotateConfigCA(in *CertRotateConfigCA, out *v1.CertRotateConfigCA, s conversion.Scope) error {
	out.Duration = (*metav1.Duration)(unsafe.Pointer(in.Duration))
	out.RenewBefore = (*metav1.Duration)(unsafe.Pointer(in.RenewBefore))
	return nil
}

// Convert_v1beta1_CertRotateConfigCA_To_v1_CertRotateConfigCA is an autogenerated conversion function.
func Convert_v1beta1_CertRotateConfigCA_To_v1_CertRotateConfigCA(in *CertRotateConfigCA, out *v1.CertRotateConfigCA, s conversion.Scope) error {
	return autoConvert_v1beta1_CertRotateConfigCA_To_v1_CertRotateConfigCA(in, out, s)
}

func autoConvert_v1_CertRotateConfigCA_To_v1beta1_CertRotateConfigCA(in *v1.CertRotateConfigCA, out *CertRotateConfigCA, s conversion.Scope) error {
	out.Duration = (*metav1.Duration)(unsafe.Pointer(in.Duration))
	out.RenewBefore = (*metav1.Duration)(unsafe.Pointer(in.RenewBefore))
	return nil
}

// Convert_v1_CertRotateConfigCA_To_v1beta1_CertRotateConfigCA is an autogenerated conversion function.
func Convert_v1_CertRotateConfigCA_To_v1beta1_CertRotateConfigCA(in *v1.CertRotateConfigCA, out *CertRotateConfigCA, s conversion.Scope) error {
	return autoConvert_v1_CertRotateConfigCA_To_v1beta1_CertRotateConfigCA(in, out, s)
}

func autoConvert_v1beta1_CertRotateConfigServer_To_v1_CertRotateConfigServer(in *CertRotateConfigServer, out *v1.CertRotateConfigServer, s conversion.Scope) error {
	out.Duration = (*metav1.Duration)(unsafe.Pointer(in.Duration))
	out.RenewBefore = (*metav1.Duration)(unsafe.Pointer(in.RenewBefore))
	return nil
}

// Convert_v1beta1_CertRotateConfigServer_To_v1_CertRotateConfigServer is an autogenerated conversion function.
func Convert_v1beta1_CertRotateConfigServer_To_v1_CertRotateConfigServer(in *CertRotateConfigServer, out *v1.CertRotateConfigServer, s conversion.Scope) error {
	return autoConvert_v1beta1_CertRotateConfigServer_To_v1_CertRotateConfigServer(in, out, s)
}

func autoConvert_v1_CertRotateConfigServer_To_v1beta1_CertRotateConfigServer(in *v1.CertRotateConfigServer, out *CertRotateConfigServer, s conversion.Scope) error {
	out.Duration = (*metav1.Duration)(unsafe.Pointer(in.Duration))
	out.RenewBefore = (*metav1.Duration)(unsafe.Pointer(in.RenewBefore))
	return nil
}

// Convert_v1_CertRotateConfigServer_To_v1beta1_CertRotateConfigServer is an autogenerated conversion function.
func Convert_v1_CertRotateConfigServer_To_v1beta1_CertRotateConfigServer(in *v1.CertRotateConfigServer, out *CertRotateConfigServer, s conversion.Scope) error {
	return autoConvert_v1_CertRotateConfigServer_To_v1beta1_CertRotateConfigServer(in, out, s)
}

func autoConvert_v1beta1_DataImportCronStatus_To_v1_DataImportCronStatus(in *DataImportCronStatus, out *v1.DataImportCronStatus, s conversion.Scope) error {
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	out.CommonTemplate = in.CommonTemplate
	out.Modified = in.Modified
	out.OriginalSupportedArchitectures = in.OriginalSupportedArchitectures
	return nil
}

// Convert_v1beta1_DataImportCronStatus_To_v1_DataImportCronStatus is an autogenerated conversion function.
func Convert_v1beta1_DataImportCronStatus_To_v1_DataImportCronStatus(in *DataImportCronStatus, out *v1.DataImportCronStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_DataImportCronStatus_To_v1_DataImportCronStatus(in, out, s)
}

func autoConvert_v1_DataImportCronStatus_To_v1beta1_DataImportCronStatus(in *v1.DataImportCronStatus, out *DataImportCronStatus, s conversion.Scope) error {
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	out.CommonTemplate = in.CommonTemplate
	out.Modified = in.Modified
	out.OriginalSupportedArchitectures = in.OriginalSupportedArchitectures
	return nil
}

// Convert_v1_DataImportCronStatus_To_v1beta1_DataImportCronStatus is an autogenerated conversion function.
func Convert_v1_DataImportCronStatus_To_v1beta1_DataImportCronStatus(in *v1.DataImportCronStatus, out *DataImportCronStatus, s conversion.Scope) error {
	return autoConvert_v1_DataImportCronStatus_To_v1beta1_DataImportCronStatus(in, out, s)
}

func autoConvert_v1beta1_DataImportCronTemplate_To_v1_DataImportCronTemplate(in *DataImportCronTemplate, out *v1.DataImportCronTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = (*corev1beta1.DataImportCronSpec)(unsafe.Pointer(in.Spec))
	return nil
}

// Convert_v1beta1_DataImportCronTemplate_To_v1_DataImportCronTemplate is an autogenerated conversion function.
func Convert_v1beta1_DataImportCronTemplate_To_v1_DataImportCronTemplate(in *DataImportCronTemplate, out *v1.DataImportCronTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_DataImportCronTemplate_To_v1_DataImportCronTemplate(in, out, s)
}

func autoConvert_v1_DataImportCronTemplate_To_v1beta1_DataImportCronTemplate(in *v1.DataImportCronTemplate, out *DataImportCronTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = (*corev1beta1.DataImportCronSpec)(unsafe.Pointer(in.Spec))
	return nil
}

// Convert_v1_DataImportCronTemplate_To_v1beta1_DataImportCronTemplate is an autogenerated conversion function.
func Convert_v1_DataImportCronTemplate_To_v1beta1_DataImportCronTemplate(in *v1.DataImportCronTemplate, out *DataImportCronTemplate, s conversion.Scope) error {
	return autoConvert_v1_DataImportCronTemplate_To_v1beta1_DataImportCronTemplate(in, out, s)
}

func autoConvert_v1beta1_DataImportCronTemplateStatus_To_v1_DataImportCronTemplateStatus(in *DataImportCronTemplateStatus, out *v1.DataImportCronTemplateStatus, s conversion.Scope) error {
	if err := Convert_v1beta1_DataImportCronTemplate_To_v1_DataImportCronTemplate(&in.DataImportCronTemplate, &out.DataImportCronTemplate, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_DataImportCronStatus_To_v1_DataImportCronStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DataImportCronTemplateStatus_To_v1_DataImportCronTemplateStatus is an autogenerated conversion function.
func Convert_v1beta1_DataImportCronTemplateStatus_To_v1_DataImportCronTemplateStatus(in *DataImportCronTemplateStatus, out *v1.DataImportCronTemplateStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_DataImportCronTemplateStatus_To_v1_DataImportCronTemplateStatus(in, out, s)
}

func autoConvert_v1_DataImportCronTemplateStatus_To_v1beta1_DataImportCronTemplateStatus(in *v1.DataImportCronTemplateStatus, out *DataImportCronTemplateStatus, s conversion.Scope) error {
	if err := Convert_v1_DataImportCronTemplate_To_v1beta1_DataImportCronTemplate(&in.DataImportCronTemplate, &out.DataImportCronTemplate, s); err != nil {
		return err
	}
	if err := Convert_v1_DataImportCronStatus_To_v1beta1_DataImportCronStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_DataImportCronTemplateStatus_To_v1beta1_DataImportCronTemplateStatus is an autogenerated conversion function.
func Convert_v1_DataImportCronTemplateStatus_To_v1beta1_DataImportCronTemplateStatus(in *v1.DataImportCronTemplateStatus, out *DataImportCronTemplateStatus, s conversion.Scope) error {
	return autoConvert_v1_DataImportCronTemplateStatus_To_v1beta1_DataImportCronTemplateStatus(in, out, s)
}

func autoConvert_v1beta1_HigherWorkloadDensityConfiguration_To_v1_HigherWorkloadDensityConfiguration(in *HigherWorkloadDensityConfiguration, out *v1.HigherWorkloadDensityConfiguration, s conversion.Scope) error {
	out.MemoryOvercommitPercentage = in.MemoryOvercommitPercentage
	return nil
}

// Convert_v1beta1_HigherWorkloadDensityConfiguration_To_v1_HigherWorkloadDensityConfiguration is an autogenerated conversion function.
func Convert_v1beta1_HigherWorkloadDensityConfiguration_To_v1_HigherWorkloadDensityConfiguration(in *HigherWorkloadDensityConfiguration, out *v1.HigherWorkloadDensityConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_HigherWorkloadDensityConfiguration_To_v1_HigherWorkloadDensityConfiguration(in, out, s)
}

func autoConvert_v1_HigherWorkloadDensityConfiguration_To_v1beta1_HigherWorkloadDensityConfiguration(in *v1.HigherWorkloadDensityConfiguration, out *HigherWorkloadDensityConfiguration, s conversion.Scope) error {
	out.MemoryOvercommitPercentage = in.MemoryOvercommitPercentage
	return nil
}

// Convert_v1_HigherWorkloadDensityConfiguration_To_v1beta1_HigherWorkloadDensityConfiguration is an autogenerated conversion function.
func Convert_v1_HigherWorkloadDensityConfiguration_To_v1beta1_HigherWorkloadDensityConfiguration(in *v1.HigherWorkloadDensityConfiguration, out *HigherWorkloadDensityConfiguration, s conversion.Scope) error {
	return autoConvert_v1_HigherWorkloadDensityConfiguration_To_v1beta1_HigherWorkloadDensityConfiguration(in, out, s)
}

func autoConvert_v1beta1_HyperConverged_To_v1_HyperConverged(in *HyperConverged, out *v1.HyperConverged, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_HyperConvergedSpec_To_v1_HyperConvergedSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_HyperConvergedStatus_To_v1_HyperConvergedStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_HyperConverged_To_v1_HyperConverged is an autogenerated conversion function.
func Convert_v1beta1_HyperConverged_To_v1_HyperConverged(in *HyperConverged, out *v1.HyperConverged, s conversion.Scope) error {
	return autoConvert_v1beta1_HyperConverged_To_v1_HyperConverged(in, out, s)
}

func autoConvert_v1_HyperConverged_To_v1beta1_HyperConverged(in *v1.HyperConverged, out *HyperConverged, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_HyperConvergedSpec_To_v1beta1_HyperConvergedSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_HyperConvergedStatus_To_v1beta1_HyperConvergedStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_HyperConverged_To_v1beta1_HyperConverged is an autogenerated conversion function.
func Convert_v1_HyperConverged_To_v1beta1_HyperConverged(in *v1.HyperConverged, out *HyperConverged, s conversion.Scope) error {
	return autoConvert_v1_HyperConverged_To_v1beta1_HyperConverged(in, out, s)
}

func autoConvert_v1beta1_HyperConvergedCertConfig_To_v1_HyperConvergedCertConfig(in *HyperConvergedCertConfig, out *v1.HyperConvergedCertConfig, s conversion.Scope) error {
	if err := Convert_v1beta1_CertRotateConfigCA_To_v1_CertRotateConfigCA(&in.CA, &out.CA, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_CertRotateConfigServer_To_v1_CertRotateConfigServer(&in.Server, &out.Server, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_HyperConvergedCertConfig_To_v1_HyperConvergedCertConfig is an autogenerated conversion function.
func Convert_v1beta1_HyperConvergedCertConfig_To_v1_HyperConvergedCertConfig(in *HyperConvergedCertConfig, out *v1.HyperConvergedCertConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_HyperConvergedCertConfig_To_v1_HyperConvergedCertConfig(in, out, s)
}

func autoConvert_v1_HyperConvergedCertConfig_To_v1beta1_HyperConvergedCertConfig(in *v1.HyperConvergedCertConfig, out *HyperConvergedCertConfig, s conversion.Scope) error {
	if err := Convert_v1_CertRotateConfigCA_To_v1beta1_CertRotateConfigCA(&in.CA, &out.CA, s); err != nil {
		return err
	}
	if err := Convert_v1_CertRotateConfigServer_To_v1beta1_CertRotateConfigServer(&in.Server, &out.Server, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_HyperConvergedCertConfig_To_v1beta1_HyperConvergedCertConfig is an autogenerated conversion function.
func Convert_v1_HyperConvergedCertConfig_To_v1beta1_HyperConvergedCertConfig(in *v1.HyperConvergedCertConfig, out *HyperConvergedCertConfig, s conversion.Scope) error {
	return autoConvert_v1_HyperConvergedCertConfig_To_v1beta1_HyperConvergedCertConfig(in, out, s)
}

func autoConvert_v1beta1_HyperConvergedConfig_To_v1_HyperConvergedConfig(in *HyperConvergedConfig, out *v1.HyperConvergedConfig, s conversion.Scope) error {
	out.NodePlacement = (*api.NodePlacement)(unsafe.Pointer(in.NodePlacement))
	return nil
}

// Convert_v1beta1_HyperConvergedConfig_To_v1_HyperConvergedConfig is an autogenerated conversion function.
func Convert_v1beta1_HyperConvergedConfig_To_v1_HyperConvergedConfig(in *HyperConvergedConfig, out *v1.HyperConvergedConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_HyperConvergedConfig_To_v1_HyperConvergedConfig(in, out, s)
}

func autoConvert_v1_HyperConvergedConfig_To_v1beta1_HyperConvergedConfig(in *v1.HyperConvergedConfig, out *HyperConvergedConfig, s conversion.Scope) error {
	out.NodePlacement = (*api.NodePlacement)(unsafe.Pointer(in.NodePlacement))
	return nil
}

// Convert_v1_HyperConvergedConfig_To_v1beta1_HyperConvergedConfig is an autogenerated conversion function.
func Convert_v1_HyperConvergedConfig_To_v1beta1_HyperConvergedConfig(in *v1.HyperConvergedConfig, out *HyperConvergedConfig, s conversion.Scope) error {
	return autoConvert_v1_HyperConvergedConfig_To_v1beta1_HyperConvergedConfig(in, out, s)
}

func autoConvert_v1beta1_HyperConvergedFeatureGates_To_v1_HyperConvergedFeatureGates(in *HyperConvergedFeatureGates, out *v1.HyperConvergedFeatureGates, s conversion.Scope) error {
	out.DownwardMetrics = (*bool)(unsafe.Pointer(in.DownwardMetrics))
	out.WithHostPassthroughCPU = (*bool)(unsafe.Pointer(in.WithHostPassthroughCPU))
	out.EnableCommonBootImageImport = (*bool)(unsafe.Pointer(in.EnableCommonBootImageImport))
	out.DeployTektonTaskResources = (*bool)(unsafe.Pointer(in.DeployTektonTaskResources))
	out.DeployVMConsoleProxy = (*bool)(unsafe.Pointer(in.DeployVMConsoleProxy))
	out.DeployKubeSecondaryDNS = (*bool)(unsafe.Pointer(in.DeployKubeSecondaryDNS))
	out.DeployKubevirtIpamController = (*bool)(unsafe.Pointer(in.DeployKubevirtIpamController))
	out.NonRoot = (*bool)(unsafe.Pointer(in.NonRoot))
	out.DisableMDevConfiguration = (*bool)(unsafe.Pointer(in.DisableMDevConfiguration))
	out.PersistentReservation = (*bool)(unsafe.Pointer(in.PersistentReservation))
	out.EnableManagedTenantQuota = (*bool)(unsafe.Pointer(in.EnableManagedTenantQuota))
	out.AutoResourceLimits = (*bool)(unsafe.Pointer(in.AutoResourceLimits))
	out.AlignCPUs = (*bool)(unsafe.Pointer(in.AlignCPUs))
	out.EnableApplicationAwareQuota = (*bool)(unsafe.Pointer(in.EnableApplicationAwareQuota))
	out.PrimaryUserDefinedNetworkBinding = (*bool)(unsafe.Pointer(in.PrimaryUserDefinedNetworkBinding))
	out.EnableMultiArchBootImageImport = (*bool)(unsafe.Pointer(in.EnableMultiArchBootImageImport))
	out.DecentralizedLiveMigration = (*bool)(unsafe.Pointer(in.DecentralizedLiveMigration))
	out.DeclarativeHotplugVolumes = (*bool)(unsafe.Pointer(in.DeclarativeHotplugVolumes))
	out.VideoConfig = (*bool)(unsafe.Pointer(in.VideoConfig))
	out.ObjectGraph = (*bool)(unsafe.Pointer(in.ObjectGraph))
	return nil
}

// Convert_v1beta1_HyperConvergedFeatureGates_To_v1_HyperConvergedFeatureGates is an autogenerated conversion function.
func Convert_v1beta1_HyperConvergedFeatureGates_To_v1_HyperConvergedFeatureGates(in *HyperConvergedFeatureGates, out *v1.HyperConvergedFeatureGates, s conversion.Scope) error {
	return autoConvert_v1beta1_HyperConvergedFeatureGates_To_v1_HyperConvergedFeatureGates(in, out, s)
}

func autoConvert_v1_HyperConvergedFeatureGates_To_v1beta1_HyperConvergedFeatureGates(in *v1.HyperConvergedFeatureGates, out *HyperConvergedFeatureGates, s conversion.Scope) error {
	out.DownwardMetrics = (*bool)(unsafe.Pointer(in.DownwardMetrics))
	out.WithHostPassthroughCPU = (*bool)(unsafe.Pointer(in.WithHostPassthroughCPU))
	out.EnableCommonBootImageImport = (*bool)(unsafe.Pointer(in.EnableCommonBootImageImport))
	out.DeployTektonTaskResources = (*bool)(unsafe.Pointer(in.DeployTektonTaskResources))
	out.DeployVMConsoleProxy = (*bool)(unsafe.Pointer(in.DeployVMConsoleProxy))
	out.DeployKubeSecondaryDNS = (*bool)(unsafe.Pointer(in.DeployKubeSecondaryDNS))
	out.DeployKubevirtIpamController = (*bool)(unsafe.Pointer(in.DeployKubevirtIpamController))
	out.NonRoot = (*bool)(unsafe.Pointer(in.NonRoot))
	out.DisableMDevConfiguration = (*bool)(unsafe.Pointer(in.DisableMDevConfiguration))
	out.PersistentReservation = (*bool)(unsafe.Pointer(in.PersistentReservation))
	out.EnableManagedTenantQuota = (*bool)(unsafe.Pointer(in.EnableManagedTenantQuota))
	out.AutoResourceLimits = (*bool)(unsafe.Pointer(in.AutoResourceLimits))
	out.AlignCPUs = (*bool)(unsafe.Pointer(in.AlignCPUs))
	out.EnableApplicationAwareQuota = (*bool)(unsafe.Pointer(in.EnableApplicationAwareQuota))
	out.PrimaryUserDefinedNetworkBinding = (*bool)(unsafe.Pointer(in.PrimaryUserDefinedNetworkBinding))
	out.EnableMultiArchBootImageImport = (*bool)(unsafe.Pointer(in.EnableMultiArchBootImageImport))
	out.DecentralizedLiveMigration = (*bool)(unsafe.Pointer(in.DecentralizedLiveMigration))
	out.DeclarativeHotplugVolumes = (*bool)(unsafe.Pointer(in.DeclarativeHotplugVolumes))
	out.VideoConfig = (*bool)(unsafe.Pointer(in.VideoConfig))
	out.ObjectGraph = (*bool)(unsafe.Pointer(in.ObjectGraph))
	return nil
}

// Convert_v1_HyperConvergedFeatureGates_To_v1beta1_HyperConvergedFeatureGates is an autogenerated conversion function.
func Convert_v1_HyperConvergedFeatureGates_To_v1beta1_HyperConvergedFeatureGates(in *v1.HyperConvergedFeatureGates, out *HyperConvergedFeatureGates, s conversion.Scope) error {
	return autoConvert_v1_HyperConvergedFeatureGates_To_v1beta1_HyperConvergedFeatureGates(in, out, s)
}

func autoConvert_v1beta1_HyperConvergedList_To_v1_HyperConvergedList(in *HyperConvergedList, out *v1.HyperConvergedList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1.HyperConverged)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_HyperConvergedList_To_v1_HyperConvergedList is an autogenerated conversion function.
func Convert_v1beta1_HyperConvergedList_To_v1_HyperConvergedList(in *HyperConvergedList, out *v1.HyperConvergedList, s conversion.Scope) error {
	return autoConvert_v1beta1_HyperConvergedList_To_v1_HyperConvergedList(in, out, s)
}

func autoConvert_v1_HyperConvergedList_To_v1beta1_HyperConvergedList(in *v1.HyperConvergedList, out *HyperConvergedList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]HyperConverged)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_HyperConvergedList_To_v1beta1_HyperConvergedList is an autogenerated conversion function.
func Convert_v1_HyperConvergedList_To_v1beta1_HyperConvergedList(in *v1.HyperConvergedList, out *HyperConvergedList, s conversion.Scope) error {
	return autoConvert_v1_HyperConvergedList_To_v1beta1_HyperConvergedList(in, out, s)
}

func autoConvert_v1beta1_HyperConvergedObsoleteCPUs_To_v1_HyperConvergedObsoleteCPUs(in *HyperConvergedObsoleteCPUs, out *v1.HyperConvergedObsoleteCPUs, s conversion.Scope) error {
	out.MinCPUModel = in.MinCPUModel
	out.CPUModels = *(*[]string)(unsafe.Pointer(&in.CPUModels))
	return nil
}

// Convert_v1beta1_HyperConvergedObsoleteCPUs_To_v1_HyperConvergedObsoleteCPUs is an autogenerated conversion function.
func Convert_v1beta1_HyperConvergedObsoleteCPUs_To_v1_HyperConvergedObsoleteCPUs(in *HyperConvergedObsoleteCPUs, out *v1.HyperConvergedObsoleteCPUs, s conversion.Scope) error {
	return autoConvert_v1beta1_HyperConvergedObsoleteCPUs_To_v1_HyperConvergedObsoleteCPUs(in, out, s)
}

func autoConvert_v1_HyperConvergedObsoleteCPUs_To_v1beta1_HyperConvergedObsoleteCPUs(in *v1.HyperConvergedObsoleteCPUs, out *HyperConvergedObsoleteCPUs, s conversion.Scope) error {
	out.MinCPUModel = in.MinCPUModel
	out.CPUModels = *(*[]string)(unsafe.Pointer(&in.CPUModels))
	return nil
}

// Convert_v1_HyperConvergedObsoleteCPUs_To_v1beta1_HyperConvergedObsoleteCPUs is an autogenerated conversion function.
func Convert_v1_HyperConvergedObsoleteCPUs_To_v1beta1_HyperConvergedObsoleteCPUs(in *v1.HyperConvergedObsoleteCPUs, out *HyperConvergedObsoleteCPUs, s conversion.Scope) error {
	return autoConvert_v1_HyperConvergedObsoleteCPUs_To_v1beta1_HyperConvergedObsoleteCPUs(in, out, s)
}

func autoConvert_v1beta1_HyperConvergedSpec_To_v1_HyperConvergedSpec(in *HyperConvergedSpec, out *v1.HyperConvergedSpec, s conversion.Scope) error {
	out.LocalStorageClassName = in.LocalStorageClassName
	out.TuningPolicy = v1.HyperConvergedTuningPolicy(in.TuningPolicy)
	if err := Convert_v1beta1_HyperConvergedConfig_To_v1_HyperConvergedConfig(&in.Infra, &out.Infra, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_HyperConvergedConfig_To_v1_HyperConvergedConfig(&in.Workloads, &out.Workloads, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_HyperConvergedFeatureGates_To_v1_HyperConvergedFeatureGates(&in.FeatureGates, &out.FeatureGates, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_LiveMigrationConfigurations_To_v1_LiveMigrationConfigurations(&in.LiveMigrationConfig, &out.LiveMigrationConfig, s); err != nil {
		return err
	}
	out.PermittedHostDevices = (*v1.PermittedHostDevices)(unsafe.Pointer(in.PermittedHostDevices))
	out.MediatedDevicesConfiguration = (*v1.MediatedDevicesConfiguration)(unsafe.Pointer(in.MediatedDevicesConfiguration))
	if err := Convert_v1beta1_HyperConvergedCertConfig_To_v1_HyperConvergedCertConfig(&in.CertConfig, &out.CertConfig, s); err != nil {
		return err
	}
	out.ResourceRequirements = (*v1.OperandResourceRequirements)(unsafe.Pointer(in.ResourceRequirements))
	out.ScratchSpaceStorageClass = (*string)(unsafe.Pointer(in.ScratchSpaceStorageClass))
	out.VddkInitImage = (*string)(unsafe.Pointer(in.VddkInitImage))
	out.DefaultCPUModel = (*string)(unsafe.Pointer(in.DefaultCPUModel))
	out.DefaultRuntimeClass = (*string)(unsafe.Pointer(in.DefaultRuntimeClass))
	out.ObsoleteCPUs = (*v1.HyperConvergedObsoleteCPUs)(unsafe.Pointer(in.ObsoleteCPUs))
	out.CommonTemplatesNamespace = (*string)(unsafe.Pointer(in.CommonTemplatesNamespace))
	out.StorageImport = (*v1.StorageImportConfig)(unsafe.Pointer(in.StorageImport))
	if err := Convert_v1beta1_HyperConvergedWorkloadUpdateStrategy_To_v1_HyperConvergedWorkloadUpdateStrategy(&in.WorkloadUpdateStrategy, &out.WorkloadUpdateStrategy, s); err != nil {
		return err
	}
	out.DataImportCronTemplates = *(*[]v1.DataImportCronTemplate)(unsafe.Pointer(&in.DataImportCronTemplates))
	out.FilesystemOverhead = (*corev1beta1.FilesystemOverhead)(unsafe.Pointer(in.FilesystemOverhead))
	out.UninstallStrategy = v1.HyperConvergedUninstallStrategy(in.UninstallStrategy)
	out.LogVerbosityConfig = (*v1.LogVerbosityConfiguration)(unsafe.Pointer(in.LogVerbosityConfig))
	out.TLSSecurityProfile = (*configv1.TLSSecurityProfile)(unsafe.Pointer(in.TLSSecurityProfile))
	out.TektonPipelinesNamespace = (*string)(unsafe.Pointer(in.TektonPipelinesNamespace))
	out.TektonTasksNamespace = (*string)(unsafe.Pointer(in.TektonTasksNamespace))
	out.KubeSecondaryDNSNameServerIP = (*string)(unsafe.Pointer(in.KubeSecondaryDNSNameServerIP))
	out.KubeMacPoolConfiguration = (*v1.KubeMacPoolConfig)(unsafe.Pointer(in.KubeMacPoolConfiguration))
	out.EvictionStrategy = (*corev1.EvictionStrategy)(unsafe.Pointer(in.EvictionStrategy))
	out.VMStateStorageClass = (*string)(unsafe.Pointer(in.VMStateStorageClass))
	out.VirtualMachineOptions = (*v1.VirtualMachineOptions)(unsafe.Pointer(in.VirtualMachineOptions))
	out.CommonBootImageNamespace = (*string)(unsafe.Pointer(in.CommonBootImageNamespace))
	out.KSMConfiguration = (*corev1.KSMConfiguration)(unsafe.Pointer(in.KSMConfiguration))
	out.NetworkBinding = *(*map[string]corev1.InterfaceBindingPlugin)(unsafe.Pointer(&in.NetworkBinding))
	out.ApplicationAwareConfig = (*v1.ApplicationAwareConfigurations)(unsafe.Pointer(in.ApplicationAwareConfig))
	out.HigherWorkloadDensity = (*v1.HigherWorkloadDensityConfiguration)(unsafe.Pointer(in.HigherWorkloadDensity))
	out.EnableCommonBootImageImport = (*bool)(unsafe.Pointer(in.EnableCommonBootImageImport))
	out.InstancetypeConfig = (*corev1.InstancetypeConfiguration)(unsafe.Pointer(in.InstancetypeConfig))
	out.CommonInstancetypesDeployment = (*corev1.CommonInstancetypesDeployment)(unsafe.Pointer(in.CommonInstancetypesDeployment))
	out.DeployVMConsoleProxy = (*bool)(unsafe.Pointer(in.DeployVMConsoleProxy))
	out.EnableApplicationAwareQuota = (*bool)(unsafe.Pointer(in.EnableApplicationAwareQuota))
	out.LiveUpdateConfiguration = (*corev1.LiveUpdateConfiguration)(unsafe.Pointer(in.LiveUpdateConfiguration))
	return nil
}

// Convert_v1beta1_HyperConvergedSpec_To_v1_HyperConvergedSpec is an autogenerated conversion function.
func Convert_v1beta1_HyperConvergedSpec_To_v1_HyperConvergedSpec(in *HyperConvergedSpec, out *v1.HyperConvergedSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_HyperConvergedSpec_To_v1_HyperConvergedSpec(in, out, s)
}

func autoConvert_v1_HyperConvergedSpec_To_v1beta1_HyperConvergedSpec(in *v1.HyperConvergedSpec, out *HyperConvergedSpec, s conversion.Scope) error {
	out.LocalStorageClassName = in.LocalStorageClassName
	out.TuningPolicy = HyperConvergedTuningPolicy(in.TuningPolicy)
	if err := Convert_v1_HyperConvergedConfig_To_v1beta1_HyperConvergedConfig(&in.Infra, &out.Infra, s); err != nil {
		return err
	}
	if err := Convert_v1_HyperConvergedConfig_To_v1beta1_HyperConvergedConfig(&in.Workloads, &out.Workloads, s); err != nil {
		return err
	}
	if err := Convert_v1_HyperConvergedFeatureGates_To_v1beta1_HyperConvergedFeatureGates(&in.FeatureGates, &out.FeatureGates, s); err != nil {
		return err
	}
	if err := Convert_v1_LiveMigrationConfigurations_To_v1beta1_LiveMigrationConfigurations(&in.LiveMigrationConfig, &out.LiveMigrationConfig, s); err != nil {
		return err
	}
	out.PermittedHostDevices = (*PermittedHostDevices)(unsafe.Pointer(in.PermittedHostDevices))
	out.MediatedDevicesConfiguration = (*MediatedDevicesConfiguration)(unsafe.Pointer(in.MediatedDevicesConfiguration))
	if err := Convert_v1_HyperConvergedCertConfig_To_v1beta1_HyperConvergedCertConfig(&in.CertConfig, &out.CertConfig, s); err != nil {
		return err
	}
	out.ResourceRequirements = (*OperandResourceRequirements)(unsafe.Pointer(in.ResourceRequirements))
	out.ScratchSpaceStorageClass = (*string)(unsafe.Pointer(in.ScratchSpaceStorageClass))
	out.VddkInitImage = (*string)(unsafe.Pointer(in.VddkInitImage))
	out.DefaultCPUModel = (*string)(unsafe.Pointer(in.DefaultCPUModel))
	out.DefaultRuntimeClass = (*string)(unsafe.Pointer(in.DefaultRuntimeClass))
	out.ObsoleteCPUs = (*HyperConvergedObsoleteCPUs)(unsafe.Pointer(in.ObsoleteCPUs))
	out.CommonTemplatesNamespace = (*string)(unsafe.Pointer(in.CommonTemplatesNamespace))
	out.StorageImport = (*StorageImportConfig)(unsafe.Pointer(in.StorageImport))
	if err := Convert_v1_HyperConvergedWorkloadUpdateStrategy_To_v1beta1_HyperConvergedWorkloadUpdateStrategy(&in.WorkloadUpdateStrategy, &out.WorkloadUpdateStrategy, s); err != nil {
		return err
	}
	out.DataImportCronTemplates = *(*[]DataImportCronTemplate)(unsafe.Pointer(&in.DataImportCronTemplates))
	out.FilesystemOverhead = (*corev1beta1.FilesystemOverhead)(unsafe.Pointer(in.FilesystemOverhead))
	out.UninstallStrategy = HyperConvergedUninstallStrategy(in.UninstallStrategy)
	out.LogVerbosityConfig = (*LogVerbosityConfiguration)(unsafe.Pointer(in.LogVerbosityConfig))
	out.TLSSecurityProfile = (*configv1.TLSSecurityProfile)(unsafe.Pointer(in.TLSSecurityProfile))
	out.TektonPipelinesNamespace = (*string)(unsafe.Pointer(in.TektonPipelinesNamespace))
	out.TektonTasksNamespace = (*string)(unsafe.Pointer(in.TektonTasksNamespace))
	out.KubeSecondaryDNSNameServerIP = (*string)(unsafe.Pointer(in.KubeSecondaryDNSNameServerIP))
	out.KubeMacPoolConfiguration = (*KubeMacPoolConfig)(unsafe.Pointer(in.KubeMacPoolConfiguration))
	out.EvictionStrategy = (*corev1.EvictionStrategy)(unsafe.Pointer(in.EvictionStrategy))
	out.VMStateStorageClass = (*string)(unsafe.Pointer(in.VMStateStorageClass))
	out.VirtualMachineOptions = (*VirtualMachineOptions)(unsafe.Pointer(in.VirtualMachineOptions))
	out.CommonBootImageNamespace = (*string)(unsafe.Pointer(in.CommonBootImageNamespace))
	out.KSMConfiguration = (*corev1.KSMConfiguration)(unsafe.Pointer(in.KSMConfiguration))
	out.NetworkBinding = *(*map[string]corev1.InterfaceBindingPlugin)(unsafe.Pointer(&in.NetworkBinding))
	out.ApplicationAwareConfig = (*ApplicationAwareConfigurations)(unsafe.Pointer(in.ApplicationAwareConfig))
	out.HigherWorkloadDensity = (*HigherWorkloadDensityConfiguration)(unsafe.Pointer(in.HigherWorkloadDensity))
	out.EnableCommonBootImageImport = (*bool)(unsafe.Pointer(in.EnableCommonBootImageImport))
	out.InstancetypeConfig = (*corev1.InstancetypeConfiguration)(unsafe.Pointer(in.InstancetypeConfig))
	out.CommonInstancetypesDeployment = (*corev1.CommonInstancetypesDeployment)(unsafe.Pointer(in.CommonInstancetypesDeployment))
	out.DeployVMConsoleProxy = (*bool)(unsafe.Pointer(in.DeployVMConsoleProxy))
	out.EnableApplicationAwareQuota = (*bool)(unsafe.Pointer(in.EnableApplicationAwareQuota))
	out.LiveUpdateConfiguration = (*corev1.LiveUpdateConfiguration)(unsafe.Pointer(in.LiveUpdateConfiguration))
	return nil
}

// Convert_v1_HyperConvergedSpec_To_v1beta1_HyperConvergedSpec is an autogenerated conversion function.
func Convert_v1_HyperConvergedSpec_To_v1beta1_HyperConvergedSpec(in *v1.HyperConvergedSpec, out *HyperConvergedSpec, s conversion.Scope) error {
	return autoConvert_v1_HyperConvergedSpec_To_v1beta1_HyperConvergedSpec(in, out, s)
}

func autoConvert_v1beta1_HyperConvergedStatus_To_v1_HyperConvergedStatus(in *HyperConvergedStatus, out *v1.HyperConvergedStatus, s conversion.Scope) error {
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	out.RelatedObjects = *(*[]apicorev1.ObjectReference)(unsafe.Pointer(&in.RelatedObjects))
	out.Versions = *(*[]v1.Version)(unsafe.Pointer(&in.Versions))
	out.ObservedGeneration = in.ObservedGeneration
	out.DataImportSchedule = in.DataImportSchedule
	out.DataImportCronTemplates = *(*[]v1.DataImportCronTemplateStatus)(unsafe.Pointer(&in.DataImportCronTemplates))
	out.SystemHealthStatus = in.SystemHealthStatus
	out.InfrastructureHighlyAvailable = (*bool)(unsafe.Pointer(in.InfrastructureHighlyAvailable))
	if err := Convert_v1beta1_NodeInfoStatus_To_v1_NodeInfoStatus(&in.NodeInfo, &out.NodeInfo, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_HyperConvergedStatus_To_v1_HyperConvergedStatus is an autogenerated conversion function.
func Convert_v1beta1_HyperConvergedStatus_To_v1_HyperConvergedStatus(in *HyperConvergedStatus, out *v1.HyperConvergedStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_HyperConvergedStatus_To_v1_HyperConvergedStatus(in, out, s)
}

func autoConvert_v1_HyperConvergedStatus_To_v1beta1_HyperConvergedStatus(in *v1.HyperConvergedStatus, out *HyperConvergedStatus, s conversion.Scope) error {
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	out.RelatedObjects = *(*[]apicorev1.ObjectReference)(unsafe.Pointer(&in.RelatedObjects))
	out.Versions = *(*[]Version)(unsafe.Pointer(&in.Versions))
	out.ObservedGeneration = in.ObservedGeneration
	out.DataImportSchedule = in.DataImportSchedule
	out.DataImportCronTemplates = *(*[]DataImportCronTemplateStatus)(unsafe.Pointer(&in.DataImportCronTemplates))
	out.SystemHealthStatus = in.SystemHealthStatus
	out.InfrastructureHighlyAvailable = (*bool)(unsafe.Pointer(in.InfrastructureHighlyAvailable))
	if err := Convert_v1_NodeInfoStatus_To_v1beta1_NodeInfoStatus(&in.NodeInfo, &out.NodeInfo, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_HyperConvergedStatus_To_v1beta1_HyperConvergedStatus is an autogenerated conversion function.
func Convert_v1_HyperConvergedStatus_To_v1beta1_HyperConvergedStatus(in *v1.HyperConvergedStatus, out *HyperConvergedStatus, s conversion.Scope) error {
	return autoConvert_v1_HyperConvergedStatus_To_v1beta1_HyperConvergedStatus(in, out, s)
}

func autoConvert_v1beta1_HyperConvergedWorkloadUpdateStrategy_To_v1_HyperConvergedWorkloadUpdateStrategy(in *HyperConvergedWorkloadUpdateStrategy, out *v1.HyperConvergedWorkloadUpdateStrategy, s conversion.Scope) error {
	out.WorkloadUpdateMethods = *(*[]string)(unsafe.Pointer(&in.WorkloadUpdateMethods))
	out.BatchEvictionSize = (*int)(unsafe.Pointer(in.BatchEvictionSize))
	out.BatchEvictionInterval = (*metav1.Duration)(unsafe.Pointer(in.BatchEvictionInterval))
	return nil
}

// Convert_v1beta1_HyperConvergedWorkloadUpdateStrategy_To_v1_HyperConvergedWorkloadUpdateStrategy is an autogenerated conversion function.
func Convert_v1beta1_HyperConvergedWorkloadUpdateStrategy_To_v1_HyperConvergedWorkloadUpdateStrategy(in *HyperConvergedWorkloadUpdateStrategy, out *v1.HyperConvergedWorkloadUpdateStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_HyperConvergedWorkloadUpdateStrategy_To_v1_HyperConvergedWorkloadUpdateStrategy(in, out, s)
}

func autoConvert_v1_HyperConvergedWorkloadUpdateStrategy_To_v1beta1_HyperConvergedWorkloadUpdateStrategy(in *v1.HyperConvergedWorkloadUpdateStrategy, out *HyperConvergedWorkloadUpdateStrategy, s conversion.Scope) error {
	out.WorkloadUpdateMethods = *(*[]string)(unsafe.Pointer(&in.WorkloadUpdateMethods))
	out.BatchEvictionSize = (*int)(unsafe.Pointer(in.BatchEvictionSize))
	out.BatchEvictionInterval = (*metav1.Duration)(unsafe.Pointer(in.BatchEvictionInterval))
	return nil
}

// Convert_v1_HyperConvergedWorkloadUpdateStrategy_To_v1beta1_HyperConvergedWorkloadUpdateStrategy is an autogenerated conversion function.
func Convert_v1_HyperConvergedWorkloadUpdateStrategy_To_v1beta1_HyperConvergedWorkloadUpdateStrategy(in *v1.HyperConvergedWorkloadUpdateStrategy, out *HyperConvergedWorkloadUpdateStrategy, s conversion.Scope) error {
	return autoConvert_v1_HyperConvergedWorkloadUpdateStrategy_To_v1beta1_HyperConvergedWorkloadUpdateStrategy(in, out, s)
}

func autoConvert_v1beta1_KubeMacPoolConfig_To_v1_KubeMacPoolConfig(in *KubeMacPoolConfig, out *v1.KubeMacPoolConfig, s conversion.Scope) error {
	out.RangeStart = (*string)(unsafe.Pointer(in.RangeStart))
	out.RangeEnd = (*string)(unsafe.Pointer(in.RangeEnd))
	return nil
}

// Convert_v1beta1_KubeMacPoolConfig_To_v1_KubeMacPoolConfig is an autogenerated conversion function.
func Convert_v1beta1_KubeMacPoolConfig_To_v1_KubeMacPoolConfig(in *KubeMacPoolConfig, out *v1.KubeMacPoolConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_KubeMacPoolConfig_To_v1_KubeMacPoolConfig(in, out, s)
}

func autoConvert_v1_KubeMacPoolConfig_To_v1beta1_KubeMacPoolConfig(in *v1.KubeMacPoolConfig, out *KubeMacPoolConfig, s conversion.Scope) error {
	out.RangeStart = (*string)(unsafe.Pointer(in.RangeStart))
	out.RangeEnd = (*string)(unsafe.Pointer(in.RangeEnd))
	return nil
}

// Convert_v1_KubeMacPoolConfig_To_v1beta1_KubeMacPoolConfig is an autogenerated conversion function.
func Convert_v1_KubeMacPoolConfig_To_v1beta1_KubeMacPoolConfig(in *v1.KubeMacPoolConfig, out *KubeMacPoolConfig, s conversion.Scope) error {
	return autoConvert_v1_KubeMacPoolConfig_To_v1beta1_KubeMacPoolConfig(in, out, s)
}

func autoConvert_v1beta1_LiveMigrationConfigurations_To_v1_LiveMigrationConfigurations(in *LiveMigrationConfigurations, out *v1.LiveMigrationConfigurations, s conversion.Scope) error {
	out.ParallelMigrationsPerCluster = (*uint32)(unsafe.Pointer(in.ParallelMigrationsPerCluster))
	out.ParallelOutboundMigrationsPerNode = (*uint32)(unsafe.Pointer(in.ParallelOutboundMigrationsPerNode))
	out.BandwidthPerMigration = (*string)(unsafe.Pointer(in.BandwidthPerMigration))
	out.CompletionTimeoutPerGiB = (*int64)(unsafe.Pointer(in.CompletionTimeoutPerGiB))
	out.ProgressTimeout = (*int64)(unsafe.Pointer(in.ProgressTimeout))
	out.Network = (*string)(unsafe.Pointer(in.Network))
	out.AllowAutoConverge = (*bool)(unsafe.Pointer(in.AllowAutoConverge))
	out.AllowPostCopy = (*bool)(unsafe.Pointer(in.AllowPostCopy))
	return nil
}

// Convert_v1beta1_LiveMigrationConfigurations_To_v1_LiveMigrationConfigurations is an autogenerated conversion function.
func Convert_v1beta1_LiveMigrationConfigurations_To_v1_LiveMigrationConfigurations(in *LiveMigrationConfigurations, out *v1.LiveMigrationConfigurations, s conversion.Scope) error {
	return autoConvert_v1beta1_LiveMigrationConfigurations_To_v1_LiveMigrationConfigurations(in, out, s)
}

func autoConvert_v1_LiveMigrationConfigurations_To_v1beta1_LiveMigrationConfigurations(in *v1.LiveMigrationConfigurations, out *LiveMigrationConfigurations, s conversion.Scope) error {
	out.ParallelMigrationsPerCluster = (*uint32)(unsafe.Pointer(in.ParallelMigrationsPerCluster))
	out.ParallelOutboundMigrationsPerNode = (*uint32)(unsafe.Pointer(in.ParallelOutboundMigrationsPerNode))
	out.BandwidthPerMigration = (*string)(unsafe.Pointer(in.BandwidthPerMigration))
	out.CompletionTimeoutPerGiB = (*int64)(unsafe.Pointer(in.CompletionTimeoutPerGiB))
	out.ProgressTimeout = (*int64)(unsafe.Pointer(in.ProgressTimeout))
	out.Network = (*string)(unsafe.Pointer(in.Network))
	out.AllowAutoConverge = (*bool)(unsafe.Pointer(in.AllowAutoConverge))
	out.AllowPostCopy = (*bool)(unsafe.Pointer(in.AllowPostCopy))
	return nil
}

// Convert_v1_LiveMigrationConfigurations_To_v1beta1_LiveMigrationConfigurations is an autogenerated conversion function.
func Convert_v1_LiveMigrationConfigurations_To_v1beta1_LiveMigrationConfigurations(in *v1.LiveMigrationConfigurations, out *LiveMigrationConfigurations, s conversion.Scope) error {
	return autoConvert_v1_LiveMigrationConfigurations_To_v1beta1_LiveMigrationConfigurations(in, out, s)
}

func autoConvert_v1beta1_LogVerbosityConfiguration_To_v1_LogVerbosityConfiguration(in *LogVerbosityConfiguration, out *v1.LogVerbosityConfiguration, s conversion.Scope) error {
	out.Kubevirt = (*corev1.LogVerbosity)(unsafe.Pointer(in.Kubevirt))
	out.CDI = (*int32)(unsafe.Pointer(in.CDI))
	return nil
}

// Convert_v1beta1_LogVerbosityConfiguration_To_v1_LogVerbosityConfiguration is an autogenerated conversion function.
func Convert_v1beta1_LogVerbosityConfiguration_To_v1_LogVerbosityConfiguration(in *LogVerbosityConfiguration, out *v1.LogVerbosityConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_LogVerbosityConfiguration_To_v1_LogVerbosityConfiguration(in, out, s)
}

func autoConvert_v1_LogVerbosityConfiguration_To_v1beta1_LogVerbosityConfiguration(in *v1.LogVerbosityConfiguration, out *LogVerbosityConfiguration, s conversion.Scope) error {
	out.Kubevirt = (*corev1.LogVerbosity)(unsafe.Pointer(in.Kubevirt))
	out.CDI = (*int32)(unsafe.Pointer(in.CDI))
	return nil
}

// Convert_v1_LogVerbosityConfiguration_To_v1beta1_LogVerbosityConfiguration is an autogenerated conversion function.
func Convert_v1_LogVerbosityConfiguration_To_v1beta1_LogVerbosityConfiguration(in *v1.LogVerbosityConfiguration, out *LogVerbosityConfiguration, s conversion.Scope) error {
	return autoConvert_v1_LogVerbosityConfiguration_To_v1beta1_LogVerbosityConfiguration(in, out, s)
}

func autoConvert_v1beta1_MediatedDevicesConfiguration_To_v1_MediatedDevicesConfiguration(in *MediatedDevicesConfiguration, out *v1.MediatedDevicesConfiguration, s conversion.Scope) error {
	out.MediatedDeviceTypes = *(*[]string)(unsafe.Pointer(&in.MediatedDeviceTypes))
	out.MediatedDevicesTypes = *(*[]string)(unsafe.Pointer(&in.MediatedDevicesTypes))
	out.NodeMediatedDeviceTypes = *(*[]v1.NodeMediatedDeviceTypesConfig)(unsafe.Pointer(&in.NodeMediatedDeviceTypes))
	return nil
}

// Convert_v1beta1_MediatedDevicesConfiguration_To_v1_MediatedDevicesConfiguration is an autogenerated conversion function.
func Convert_v1beta1_MediatedDevicesConfiguration_To_v1_MediatedDevicesConfiguration(in *MediatedDevicesConfiguration, out *v1.MediatedDevicesConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_MediatedDevicesConfiguration_To_v1_MediatedDevicesConfiguration(in, out, s)
}

func autoConvert_v1_MediatedDevicesConfiguration_To_v1beta1_MediatedDevicesConfiguration(in *v1.MediatedDevicesConfiguration, out *MediatedDevicesConfiguration, s conversion.Scope) error {
	out.MediatedDeviceTypes = *(*[]string)(unsafe.Pointer(&in.MediatedDeviceTypes))
	out.MediatedDevicesTypes = *(*[]string)(unsafe.Pointer(&in.MediatedDevicesTypes))
	out.NodeMediatedDeviceTypes = *(*[]NodeMediatedDeviceTypesConfig)(unsafe.Pointer(&in.NodeMediatedDeviceTypes))
	return nil
}

// Convert_v1_MediatedDevicesConfiguration_To_v1beta1_MediatedDevicesConfiguration is an autogenerated conversion function.
func Convert_v1_MediatedDevicesConfiguration_To_v1beta1_MediatedDevicesConfiguration(in *v1.MediatedDevicesConfiguration, out *MediatedDevicesConfiguration, s conversion.Scope) error {
	return autoConvert_v1_MediatedDevicesConfiguration_To_v1beta1_MediatedDevicesConfiguration(in, out, s)
}

func autoConvert_v1beta1_MediatedHostDevice_To_v1_MediatedHostDevice(in *MediatedHostDevice, out *v1.MediatedHostDevice, s conversion.Scope) error {
	out.MDEVNameSelector = in.MDEVNameSelector
	out.ResourceName = in.ResourceName
	out.ExternalResourceProvider = in.ExternalResourceProvider
	out.Disabled = in.Disabled
	return nil
}

// Convert_v1beta1_MediatedHostDevice_To_v1_MediatedHostDevice is an autogenerated conversion function.
func Convert_v1beta1_MediatedHostDevice_To_v1_MediatedHostDevice(in *MediatedHostDevice, out *v1.MediatedHostDevice, s conversion.Scope) error {
	return autoConvert_v1beta1_MediatedHostDevice_To_v1_MediatedHostDevice(in, out, s)
}

func autoConvert_v1_MediatedHostDevice_To_v1beta1_MediatedHostDevice(in *v1.MediatedHostDevice, out *MediatedHostDevice, s conversion.Scope) error {
	out.MDEVNameSelector = in.MDEVNameSelector
	out.ResourceName = in.ResourceName
	out.ExternalResourceProvider = in.ExternalResourceProvider
	out.Disabled = in.Disabled
	return nil
}

// Convert_v1_MediatedHostDevice_To_v1beta1_MediatedHostDevice is an autogenerated conversion function.
func Convert_v1_MediatedHostDevice_To_v1beta1_MediatedHostDevice(in *v1.MediatedHostDevice, out *MediatedHostDevice, s conversion.Scope) error {
	return autoConvert_v1_MediatedHostDevice_To_v1beta1_MediatedHostDevice(in, out, s)
}

func autoConvert_v1beta1_NodeInfoStatus_To_v1_NodeInfoStatus(in *NodeInfoStatus, out *v1.NodeInfoStatus, s conversion.Scope) error {
	out.WorkloadsArchitectures = *(*[]string)(unsafe.Pointer(&in.WorkloadsArchitectures))
	out.ControlPlaneArchitectures = *(*[]string)(unsafe.Pointer(&in.ControlPlaneArchitectures))
	return nil
}

// Convert_v1beta1_NodeInfoStatus_To_v1_NodeInfoStatus is an autogenerated conversion function.
func Convert_v1beta1_NodeInfoStatus_To_v1_NodeInfoStatus(in *NodeInfoStatus, out *v1.NodeInfoStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_NodeInfoStatus_To_v1_NodeInfoStatus(in, out, s)
}

func autoConvert_v1_NodeInfoStatus_To_v1beta1_NodeInfoStatus(in *v1.NodeInfoStatus, out *NodeInfoStatus, s conversion.Scope) error {
	out.WorkloadsArchitectures = *(*[]string)(unsafe.Pointer(&in.WorkloadsArchitectures))
	out.ControlPlaneArchitectures = *(*[]string)(unsafe.Pointer(&in.ControlPlaneArchitectures))
	return nil
}

// Convert_v1_NodeInfoStatus_To_v1beta1_NodeInfoStatus is an autogenerated conversion function.
func Convert_v1_NodeInfoStatus_To_v1beta1_NodeInfoStatus(in *v1.NodeInfoStatus, out *NodeInfoStatus, s conversion.Scope) error {
	return autoConvert_v1_NodeInfoStatus_To_v1beta1_NodeInfoStatus(in, out, s)
}

func autoConvert_v1beta1_NodeMediatedDeviceTypesConfig_To_v1_NodeMediatedDeviceTypesConfig(in *NodeMediatedDeviceTypesConfig, out *v1.NodeMediatedDeviceTypesConfig, s conversion.Scope) error {
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.MediatedDeviceTypes = *(*[]string)(unsafe.Pointer(&in.MediatedDeviceTypes))
	out.MediatedDevicesTypes = *(*[]string)(unsafe.Pointer(&in.MediatedDevicesTypes))
	return nil
}

// Convert_v1beta1_NodeMediatedDeviceTypesConfig_To_v1_NodeMediatedDeviceTypesConfig is an autogenerated conversion function.
func Convert_v1beta1_NodeMediatedDeviceTypesConfig_To_v1_NodeMediatedDeviceTypesConfig(in *NodeMediatedDeviceTypesConfig, out *v1.NodeMediatedDeviceTypesConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_NodeMediatedDeviceTypesConfig_To_v1_NodeMediatedDeviceTypesConfig(in, out, s)
}

func autoConvert_v1_NodeMediatedDeviceTypesConfig_To_v1beta1_NodeMediatedDeviceTypesConfig(in *v1.NodeMediatedDeviceTypesConfig, out *NodeMediatedDeviceTypesConfig, s conversion.Scope) error {
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.MediatedDeviceTypes = *(*[]string)(unsafe.Pointer(&in.MediatedDeviceTypes))
	out.MediatedDevicesTypes = *(*[]string)(unsafe.Pointer(&in.MediatedDevicesTypes))
	return nil
}

// Convert_v1_NodeMediatedDeviceTypesConfig_To_v1beta1_NodeMediatedDeviceTypesConfig is an autogenerated conversion function.
func Convert_v1_NodeMediatedDeviceTypesConfig_To_v1beta1_NodeMediatedDeviceTypesConfig(in *v1.NodeMediatedDeviceTypesConfig, out *NodeMediatedDeviceTypesConfig, s conversion.Scope) error {
	return autoConvert_v1_NodeMediatedDeviceTypesConfig_To_v1beta1_NodeMediatedDeviceTypesConfig(in, out, s)
}

func autoConvert_v1beta1_OperandResourceRequirements_To_v1_OperandResourceRequirements(in *OperandResourceRequirements, out *v1.OperandResourceRequirements, s conversion.Scope) error {
	out.StorageWorkloads = (*apicorev1.ResourceRequirements)(unsafe.Pointer(in.StorageWorkloads))
	out.VmiCPUAllocationRatio = (*int)(unsafe.Pointer(in.VmiCPUAllocationRatio))
	out.AutoCPULimitNamespaceLabelSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.AutoCPULimitNamespaceLabelSelector))
	return nil
}

// Convert_v1beta1_OperandResourceRequirements_To_v1_OperandResourceRequirements is an autogenerated conversion function.
func Convert_v1beta1_OperandResourceRequirements_To_v1_OperandResourceRequirements(in *OperandResourceRequirements, out *v1.OperandResourceRequirements, s conversion.Scope) error {
	return autoConvert_v1beta1_OperandResourceRequirements_To_v1_OperandResourceRequirements(in, out, s)
}

func autoConvert_v1_OperandResourceRequirements_To_v1beta1_OperandResourceRequirements(in *v1.OperandResourceRequirements, out *OperandResourceRequirements, s conversion.Scope) error {
	out.StorageWorkloads = (*apicorev1.ResourceRequirements)(unsafe.Pointer(in.StorageWorkloads))
	out.VmiCPUAllocationRatio = (*int)(unsafe.Pointer(in.VmiCPUAllocationRatio))
	out.AutoCPULimitNamespaceLabelSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.AutoCPULimitNamespaceLabelSelector))
	return nil
}

// Convert_v1_OperandResourceRequirements_To_v1beta1_OperandResourceRequirements is an autogenerated conversion function.
func Convert_v1_OperandResourceRequirements_To_v1beta1_OperandResourceRequirements(in *v1.OperandResourceRequirements, out *OperandResourceRequirements, s conversion.Scope) error {
	return autoConvert_v1_OperandResourceRequirements_To_v1beta1_OperandResourceRequirements(in, out, s)
}

func autoConvert_v1beta1_PciHostDevice_To_v1_PciHostDevice(in *PciHostDevice, out *v1.PciHostDevice, s conversion.Scope) error {
	out.PCIDeviceSelector = in.PCIDeviceSelector
	out.ResourceName = in.ResourceName
	out.ExternalResourceProvider = in.ExternalResourceProvider
	out.Disabled = in.Disabled
	return nil
}

// Convert_v1beta1_PciHostDevice_To_v1_PciHostDevice is an autogenerated conversion function.
func Convert_v1beta1_PciHostDevice_To_v1_PciHostDevice(in *PciHostDevice, out *v1.PciHostDevice, s conversion.Scope) error {
	return autoConvert_v1beta1_PciHostDevice_To_v1_PciHostDevice(in, out, s)
}

func autoConvert_v1_PciHostDevice_To_v1beta1_PciHostDevice(in *v1.PciHostDevice, out *PciHostDevice, s conversion.Scope) error {
	out.PCIDeviceSelector = in.PCIDeviceSelector
	out.ResourceName = in.ResourceName
	out.ExternalResourceProvider = in.ExternalResourceProvider
	out.Disabled = in.Disabled
	return nil
}

// Convert_v1_PciHostDevice_To_v1beta1_PciHostDevice is an autogenerated conversion function.
func Convert_v1_PciHostDevice_To_v1beta1_PciHostDevice(in *v1.PciHostDevice, out *PciHostDevice, s conversion.Scope) error {
	return autoConvert_v1_PciHostDevice_To_v1beta1_PciHostDevice(in, out, s)
}

func autoConvert_v1beta1_PermittedHostDevices_To_v1_PermittedHostDevices(in *PermittedHostDevices, out *v1.PermittedHostDevices, s conversion.Scope) error {
	out.PciHostDevices = *(*[]v1.PciHostDevice)(unsafe.Pointer(&in.PciHostDevices))
	out.USBHostDevices = *(*[]v1.USBHostDevice)(unsafe.Pointer(&in.USBHostDevices))
	out.MediatedDevices = *(*[]v1.MediatedHostDevice)(unsafe.Pointer(&in.MediatedDevices))
	return nil
}

// Convert_v1beta1_PermittedHostDevices_To_v1_PermittedHostDevices is an autogenerated conversion function.
func Convert_v1beta1_PermittedHostDevices_To_v1_PermittedHostDevices(in *PermittedHostDevices, out *v1.PermittedHostDevices, s conversion.Scope) error {
	return autoConvert_v1beta1_PermittedHostDevices_To_v1_PermittedHostDevices(in, out, s)
}

func autoConvert_v1_PermittedHostDevices_To_v1beta1_PermittedHostDevices(in *v1.PermittedHostDevices, out *PermittedHostDevices, s conversion.Scope) error {
	out.PciHostDevices = *(*[]PciHostDevice)(unsafe.Pointer(&in.PciHostDevices))
	out.USBHostDevices = *(*[]USBHostDevice)(unsafe.Pointer(&in.USBHostDevices))
	out.MediatedDevices = *(*[]MediatedHostDevice)(unsafe.Pointer(&in.MediatedDevices))
	return nil
}

// Convert_v1_PermittedHostDevices_To_v1beta1_PermittedHostDevices is an autogenerated conversion function.
func Convert_v1_PermittedHostDevices_To_v1beta1_PermittedHostDevices(in *v1.PermittedHostDevices, out *PermittedHostDevices, s conversion.Scope) error {
	return autoConvert_v1_PermittedHostDevices_To_v1beta1_PermittedHostDevices(in, out, s)
}

func autoConvert_v1beta1_StorageImportConfig_To_v1_StorageImportConfig(in *StorageImportConfig, out *v1.StorageImportConfig, s conversion.Scope) error {
	out.InsecureRegistries = *(*[]string)(unsafe.Pointer(&in.InsecureRegistries))
	return nil
}

// Convert_v1beta1_StorageImportConfig_To_v1_StorageImportConfig is an autogenerated conversion function.
func Convert_v1beta1_StorageImportConfig_To_v1_StorageImportConfig(in *StorageImportConfig, out *v1.StorageImportConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_StorageImportConfig_To_v1_StorageImportConfig(in, out, s)
}

func autoConvert_v1_StorageImportConfig_To_v1beta1_StorageImportConfig(in *v1.StorageImportConfig, out *StorageImportConfig, s conversion.Scope) error {
	out.InsecureRegistries = *(*[]string)(unsafe.Pointer(&in.InsecureRegistries))
	return nil
}

// Convert_v1_StorageImportConfig_To_v1beta1_StorageImportConfig is an autogenerated conversion function.
func Convert_v1_StorageImportConfig_To_v1beta1_StorageImportConfig(in *v1.StorageImportConfig, out *StorageImportConfig, s conversion.Scope) error {
	return autoConvert_v1_StorageImportConfig_To_v1beta1_StorageImportConfig(in, out, s)
}

func autoConvert_v1beta1_USBHostDevice_To_v1_USBHostDevice(in *USBHostDevice, out *v1.USBHostDevice, s conversion.Scope) error {
	out.ResourceName = in.ResourceName
	out.Selectors = *(*[]v1.USBSelector)(unsafe.Pointer(&in.Selectors))
	out.ExternalResourceProvider = in.ExternalResourceProvider
	out.Disabled = in.Disabled
	return nil
}

// Convert_v1beta1_USBHostDevice_To_v1_USBHostDevice is an autogenerated conversion function.
func Convert_v1beta1_USBHostDevice_To_v1_USBHostDevice(in *USBHostDevice, out *v1.USBHostDevice, s conversion.Scope) error {
	return autoConvert_v1beta1_USBHostDevice_To_v1_USBHostDevice(in, out, s)
}

func autoConvert_v1_USBHostDevice_To_v1beta1_USBHostDevice(in *v1.USBHostDevice, out *USBHostDevice, s conversion.Scope) error {
	out.ResourceName = in.ResourceName
	out.Selectors = *(*[]USBSelector)(unsafe.Pointer(&in.Selectors))
	out.ExternalResourceProvider = in.ExternalResourceProvider
	out.Disabled = in.Disabled
	return nil
}

// Convert_v1_USBHostDevice_To_v1beta1_USBHostDevice is an autogenerated conversion function.
func Convert_v1_USBHostDevice_To_v1beta1_USBHostDevice(in *v1.USBHostDevice, out *USBHostDevice, s conversion.Scope) error {
	return autoConvert_v1_USBHostDevice_To_v1beta1_USBHostDevice(in, out, s)
}

func autoConvert_v1beta1_USBSelector_To_v1_USBSelector(in *USBSelector, out *v1.USBSelector, s conversion.Scope) error {
	out.Vendor = in.Vendor
	out.Product = in.Product
	return nil
}

// Convert_v1beta1_USBSelector_To_v1_USBSelector is an autogenerated conversion function.
func Convert_v1beta1_USBSelector_To_v1_USBSelector(in *USBSelector, out *v1.USBSelector, s conversion.Scope) error {
	return autoConvert_v1beta1_USBSelector_To_v1_USBSelector(in, out, s)
}

func autoConvert_v1_USBSelector_To_v1beta1_USBSelector(in *v1.USBSelector, out *USBSelector, s conversion.Scope) error {
	out.Vendor = in.Vendor
	out.Product = in.Product
	return nil
}

// Convert_v1_USBSelector_To_v1beta1_USBSelector is an autogenerated conversion function.
func Convert_v1_USBSelector_To_v1beta1_USBSelector(in *v1.USBSelector, out *USBSelector, s conversion.Scope) error {
	return autoConvert_v1_USBSelector_To_v1beta1_USBSelector(in, out, s)
}

func autoConvert_v1beta1_Version_To_v1_Version(in *Version, out *v1.Version, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	return nil
}

// Convert_v1beta1_Version_To_v1_Version is an autogenerated conversion function.
func Convert_v1beta1_Version_To_v1_Version(in *Version, out *v1.Version, s conversion.Scope) error {
	return autoConvert_v1beta1_Version_To_v1_Version(in, out, s)
}

func autoConvert_v1_Version_To_v1beta1_Version(in *v1.Version, out *Version, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	return nil
}

// Convert_v1_Version_To_v1beta1_Version is an autogenerated conversion function.
func Convert_v1_Version_To_v1beta1_Version(in *v1.Version, out *Version, s conversion.Scope) error {
	return autoConvert_v1_Version_To_v1beta1_Version(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineOptions_To_v1_VirtualMachineOptions(in *VirtualMachineOptions, out *v1.VirtualMachineOptions, s conversion.Scope) error {
	out.DisableFreePageReporting = (*bool)(unsafe.Pointer(in.DisableFreePageReporting))
	out.DisableSerialConsoleLog = (*bool)(unsafe.Pointer(in.DisableSerialConsoleLog))
	return nil
}

// Convert_v1beta1_VirtualMachineOptions_To_v1_VirtualMachineOptions is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineOptions_To_v1_VirtualMachineOptions(in *VirtualMachineOptions, out *v1.VirtualMachineOptions, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineOptions_To_v1_VirtualMachineOptions(in, out, s)
}

func autoConvert_v1_VirtualMachineOptions_To_v1beta1_VirtualMachineOptions(in *v1.VirtualMachineOptions, out *VirtualMachineOptions, s conversion.Scope) error {
	out.DisableFreePageReporting = (*bool)(unsafe.Pointer(in.DisableFreePageReporting))
	out.DisableSerialConsoleLog = (*bool)(unsafe.Pointer(in.DisableSerialConsoleLog))
	return nil
}

// Convert_v1_VirtualMachineOptions_To_v1beta1_VirtualMachineOptions is an autogenerated conversion function.
func Convert_v1_VirtualMachineOptions_To_v1beta1_VirtualMachineOptions(in *v1.VirtualMachineOptions, out *VirtualMachineOptions, s conversion.Scope) error {
	return autoConvert_v1_VirtualMachineOptions_To_v1beta1_VirtualMachineOptions(in, out, s)
}
