//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * This file is part of the KubeVirt project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2026 Red Hat, Inc.
 *
 */

// Code generated by openapi-gen. DO NOT EDIT.

package v1beta1

import (
	common "k8s.io/kube-openapi/pkg/common"
	spec "k8s.io/kube-openapi/pkg/validation/spec"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.ApplicationAwareConfigurations": schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_ApplicationAwareConfigurations(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.CertRotateConfigCA":             schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_CertRotateConfigCA(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.CertRotateConfigServer":         schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_CertRotateConfigServer(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConverged":                 schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_HyperConverged(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedCertConfig":       schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_HyperConvergedCertConfig(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedFeatureGates":     schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_HyperConvergedFeatureGates(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedObsoleteCPUs":     schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_HyperConvergedObsoleteCPUs(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedSpec":             schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_HyperConvergedSpec(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedStatus":           schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_HyperConvergedStatus(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.KubeMacPoolConfig":              schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_KubeMacPoolConfig(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.LogVerbosityConfiguration":      schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_LogVerbosityConfiguration(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.MediatedDevicesConfiguration":   schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_MediatedDevicesConfiguration(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.NodeMediatedDeviceTypesConfig":  schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_NodeMediatedDeviceTypesConfig(ref),
		"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.OperandResourceRequirements":    schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_OperandResourceRequirements(ref),
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_ApplicationAwareConfigurations(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ApplicationAwareConfigurations holds the AAQ configurations",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"vmiCalcConfigName": {
						SchemaProps: spec.SchemaProps{
							Description: "VmiCalcConfigName determine how resource allocation will be done with ApplicationsResourceQuota. allowed values are: VmiPodUsage, VirtualResources, DedicatedVirtualResources, IgnoreVmiCalculator or GuestEffectiveResources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"namespaceSelector": {
						SchemaProps: spec.SchemaProps{
							Description: "NamespaceSelector determines in which namespaces scheduling gate will be added to pods..",
							Ref:         ref("k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelector"),
						},
					},
					"allowApplicationAwareClusterResourceQuota": {
						SchemaProps: spec.SchemaProps{
							Description: "AllowApplicationAwareClusterResourceQuota if set to true, allows creation and management of ClusterAppsResourceQuota",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelector"},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_CertRotateConfigCA(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CertRotateConfigCA contains the tunables for TLS certificates.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"duration": {
						SchemaProps: spec.SchemaProps{
							Description: "The requested 'duration' (i.e. lifetime) of the Certificate. This should comply with golang's ParseDuration format (https://golang.org/pkg/time/#ParseDuration)",
							Default:     "48h0m0s",
							Ref:         ref("k8s.io/apimachinery/pkg/apis/meta/v1.Duration"),
						},
					},
					"renewBefore": {
						SchemaProps: spec.SchemaProps{
							Description: "The amount of time before the currently issued certificate's `notAfter` time that we will begin to attempt to renew the certificate. This should comply with golang's ParseDuration format (https://golang.org/pkg/time/#ParseDuration)",
							Default:     "24h0m0s",
							Ref:         ref("k8s.io/apimachinery/pkg/apis/meta/v1.Duration"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/apis/meta/v1.Duration"},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_CertRotateConfigServer(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CertRotateConfigServer contains the tunables for TLS certificates.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"duration": {
						SchemaProps: spec.SchemaProps{
							Description: "The requested 'duration' (i.e. lifetime) of the Certificate. This should comply with golang's ParseDuration format (https://golang.org/pkg/time/#ParseDuration)",
							Default:     "24h0m0s",
							Ref:         ref("k8s.io/apimachinery/pkg/apis/meta/v1.Duration"),
						},
					},
					"renewBefore": {
						SchemaProps: spec.SchemaProps{
							Description: "The amount of time before the currently issued certificate's `notAfter` time that we will begin to attempt to renew the certificate. This should comply with golang's ParseDuration format (https://golang.org/pkg/time/#ParseDuration)",
							Default:     "12h0m0s",
							Ref:         ref("k8s.io/apimachinery/pkg/apis/meta/v1.Duration"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/apis/meta/v1.Duration"},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_HyperConverged(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HyperConverged is the Schema for the hyperconvergeds API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedSpec", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_HyperConvergedCertConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HyperConvergedCertConfig holds the CertConfig entries for the HCO operands",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"ca": {
						SchemaProps: spec.SchemaProps{
							Description: "CA configuration - CA certs are kept in the CA bundle as long as they are valid",
							Default:     map[string]interface{}{},
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.CertRotateConfigCA"),
						},
					},
					"server": {
						SchemaProps: spec.SchemaProps{
							Description: "Server configuration - Certs are rotated and discarded",
							Default:     map[string]interface{}{},
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.CertRotateConfigServer"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.CertRotateConfigCA", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.CertRotateConfigServer"},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_HyperConvergedFeatureGates(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HyperConvergedFeatureGates is a set of optional feature gates to enable or disable new features that are not enabled by default yet.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"downwardMetrics": {
						SchemaProps: spec.SchemaProps{
							Description: "Allow to expose a limited set of host metrics to guests.",
							Default:     false,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"withHostPassthroughCPU": {
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: This feature gate is ignored",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"enableCommonBootImageImport": {
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: This feature gate is ignored. Use spec.enableCommonBootImageImport instead",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"deployTektonTaskResources": {
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: This feature gate is ignored.",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"deployVmConsoleProxy": {
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: This feature gate is ignored. Use spec.deployVmConsoleProxy instead",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"deployKubeSecondaryDNS": {
						SchemaProps: spec.SchemaProps{
							Description: "Deploy KubeSecondaryDNS by CNAO",
							Default:     false,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"deployKubevirtIpamController": {
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: this feature gate is ignored.",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"nonRoot": {
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: This feature gate is ignored.",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"disableMDevConfiguration": {
						SchemaProps: spec.SchemaProps{
							Description: "Disable mediated devices handling on KubeVirt",
							Default:     false,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"persistentReservation": {
						SchemaProps: spec.SchemaProps{
							Description: "Enable persistent reservation of a LUN through the SCSI Persistent Reserve commands on Kubevirt. In order to issue privileged SCSI ioctls, the VM requires activation of the persistent reservation flag. Once this feature gate is enabled, then the additional container with the qemu-pr-helper is deployed inside the virt-handler pod. Enabling (or removing) the feature gate causes the redeployment of the virt-handler pod.",
							Default:     false,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"enableManagedTenantQuota": {
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: This feature gate is ignored.",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"autoResourceLimits": {
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: this feature gate is ignored.",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"alignCPUs": {
						SchemaProps: spec.SchemaProps{
							Description: "Enable KubeVirt to request up to two additional dedicated CPUs in order to complete the total CPU count to an even parity when using emulator thread isolation. Note: this feature is in Developer Preview.",
							Default:     false,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"enableApplicationAwareQuota": {
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: This field is ignored and will be removed on the next version of the API. Use spec.enableApplicationAwareQuota instead",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"primaryUserDefinedNetworkBinding": {
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: this feature gate is ignored.",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"enableMultiArchBootImageImport": {
						SchemaProps: spec.SchemaProps{
							Description: "EnableMultiArchBootImageImport allows the HCO to run on heterogeneous clusters with different CPU architectures. Setting this field to true will allow the HCO to create Golden Images for different CPU architectures.\n\nThis feature is in Developer Preview.",
							Default:     false,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"decentralizedLiveMigration": {
						SchemaProps: spec.SchemaProps{
							Description: "DecentralizedLiveMigration enables the decentralized live migration (cross-cluster migration) feature. This feature allows live migration of VirtualMachineInstances between different clusters. This feature is in Developer Preview.",
							Default:     true,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"declarativeHotplugVolumes": {
						SchemaProps: spec.SchemaProps{
							Description: "DeclarativeHotplugVolumes enables the use of the declarative volume hotplug feature in KubeVirt. When set to true, the \"DeclarativeHotplugVolumes\" feature gate is enabled instead of \"HotplugVolumes\". When set to false or nil, the \"HotplugVolumes\" feature gate is enabled (default behavior). This feature is in Developer Preview.",
							Default:     false,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"videoConfig": {
						SchemaProps: spec.SchemaProps{
							Description: "VideoConfig allows users to configure video device types for their virtual machines. This can be useful for workloads that require specific video capabilities or architectures. Note: This feature is in Tech Preview.",
							Default:     true,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"objectGraph": {
						SchemaProps: spec.SchemaProps{
							Description: "ObjectGraph enables the ObjectGraph VM and VMI subresource in KubeVirt. This subresource returns a structured list of k8s objects that are related to the specified VM or VMI, enabling better dependency tracking. Note: This feature is in Developer Preview.",
							Default:     false,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"incrementalBackup": {
						SchemaProps: spec.SchemaProps{
							Description: "IncrementalBackup enables changed block tracking backups and incremental backups using QEMU capabilities in KubeVirt. When enabled, this also enables the UtilityVolumes feature gate in the KubeVirt CR. Note: This feature is in Tech Preview.",
							Default:     false,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"containerPathVolumes": {
						SchemaProps: spec.SchemaProps{
							Description: "ContainerPathVolumes enables the use of container paths as volumes in KubeVirt. This allows VMs to access files and directories from the virt-launcher pod's filesystem via virtiofs.",
							Default:     false,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
				},
			},
		},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_HyperConvergedObsoleteCPUs(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HyperConvergedObsoleteCPUs allows avoiding scheduling of VMs for obsolete CPU models",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"minCPUModel": {
						SchemaProps: spec.SchemaProps{
							Description: "MinCPUModel is not in use Deprecated: This field is not in use and is ignored.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"cpuModels": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "set",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "CPUModels is a list of obsolete CPU models. When the node-labeller obtains the list of obsolete CPU models, it eliminates those CPU models and creates labels for valid CPU models. The default values for this field is nil, however, HCO uses opinionated values, and adding values to this list will add them to the opinionated values.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_HyperConvergedSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HyperConvergedSpec defines the desired state of HyperConverged",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"localStorageClassName": {
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: LocalStorageClassName the name of the local storage class.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"tuningPolicy": {
						SchemaProps: spec.SchemaProps{
							Description: "TuningPolicy allows to configure the mode in which the RateLimits of kubevirt are set. If TuningPolicy is not present the default kubevirt values are used. It can be set to `annotation` for fine-tuning the kubevirt queryPerSeconds (qps) and burst values. Qps and burst values are taken from the annotation hco.kubevirt.io/tuningPolicy",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"infra": {
						SchemaProps: spec.SchemaProps{
							Description: "infra HyperConvergedConfig influences the pod configuration (currently only placement) for all the infra components needed on the virtualization enabled cluster but not necessarily directly on each node running VMs/VMIs.",
							Default:     map[string]interface{}{},
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedConfig"),
						},
					},
					"workloads": {
						SchemaProps: spec.SchemaProps{
							Description: "workloads HyperConvergedConfig influences the pod configuration (currently only placement) of components which need to be running on a node where virtualization workloads should be able to run. Changes to Workloads HyperConvergedConfig can be applied only without existing workload.",
							Default:     map[string]interface{}{},
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedConfig"),
						},
					},
					"featureGates": {
						SchemaProps: spec.SchemaProps{
							Description: "featureGates is a map of feature gate flags. Setting a flag to `true` will enable the feature. Setting `false` or removing the feature gate, disables the feature.",
							Default:     map[string]interface{}{},
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedFeatureGates"),
						},
					},
					"liveMigrationConfig": {
						SchemaProps: spec.SchemaProps{
							Description: "Live migration limits and timeouts are applied so that migration processes do not overwhelm the cluster.",
							Default:     map[string]interface{}{},
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1.LiveMigrationConfigurations"),
						},
					},
					"permittedHostDevices": {
						SchemaProps: spec.SchemaProps{
							Description: "PermittedHostDevices holds information about devices allowed for passthrough",
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1.PermittedHostDevices"),
						},
					},
					"mediatedDevicesConfiguration": {
						SchemaProps: spec.SchemaProps{
							Description: "MediatedDevicesConfiguration holds information about MDEV types to be defined on nodes, if available",
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.MediatedDevicesConfiguration"),
						},
					},
					"certConfig": {
						SchemaProps: spec.SchemaProps{
							Description: "certConfig holds the rotation policy for internal, self-signed certificates",
							Default:     map[string]interface{}{},
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedCertConfig"),
						},
					},
					"resourceRequirements": {
						SchemaProps: spec.SchemaProps{
							Description: "ResourceRequirements describes the resource requirements for the operand workloads.",
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.OperandResourceRequirements"),
						},
					},
					"scratchSpaceStorageClass": {
						SchemaProps: spec.SchemaProps{
							Description: "Override the storage class used for scratch space during transfer operations. The scratch space storage class is determined in the following order: value of scratchSpaceStorageClass, if that doesn't exist, use the default storage class, if there is no default storage class, use the storage class of the DataVolume, if no storage class specified, use no storage class for scratch space",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"vddkInitImage": {
						SchemaProps: spec.SchemaProps{
							Description: "VDDK Init Image eventually used to import VMs from external providers\n\nDeprecated: please use the Migration Toolkit for Virtualization",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"defaultCPUModel": {
						SchemaProps: spec.SchemaProps{
							Description: "DefaultCPUModel defines a cluster default for CPU model: default CPU model is set when VMI doesn't have any CPU model. When VMI has CPU model set, then VMI's CPU model is preferred. When default CPU model is not set and VMI's CPU model is not set too, host-model will be set. Default CPU model can be changed when kubevirt is running.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"defaultRuntimeClass": {
						SchemaProps: spec.SchemaProps{
							Description: "DefaultRuntimeClass defines a cluster default for the RuntimeClass to be used for VMIs pods if not set there. Default RuntimeClass can be changed when kubevirt is running, existing VMIs are not impacted till the next restart/live-migration when they are eventually going to consume the new default RuntimeClass.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"obsoleteCPUs": {
						SchemaProps: spec.SchemaProps{
							Description: "ObsoleteCPUs allows avoiding scheduling of VMs for obsolete CPU models",
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedObsoleteCPUs"),
						},
					},
					"commonTemplatesNamespace": {
						SchemaProps: spec.SchemaProps{
							Description: "CommonTemplatesNamespace defines namespace in which common templates will be deployed. It overrides the default openshift namespace.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"storageImport": {
						SchemaProps: spec.SchemaProps{
							Description: "StorageImport contains configuration for importing containerized data",
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1.StorageImportConfig"),
						},
					},
					"workloadUpdateStrategy": {
						SchemaProps: spec.SchemaProps{
							Description: "WorkloadUpdateStrategy defines at the cluster level how to handle automated workload updates",
							Default:     map[string]interface{}{},
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1.HyperConvergedWorkloadUpdateStrategy"),
						},
					},
					"dataImportCronTemplates": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "atomic",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "DataImportCronTemplates holds list of data import cron templates (golden images)",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.DataImportCronTemplate"),
									},
								},
							},
						},
					},
					"filesystemOverhead": {
						SchemaProps: spec.SchemaProps{
							Description: "FilesystemOverhead describes the space reserved for overhead when using Filesystem volumes. A value is between 0 and 1, if not defined it is 0.055 (5.5 percent overhead)",
							Ref:         ref("kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1.FilesystemOverhead"),
						},
					},
					"uninstallStrategy": {
						SchemaProps: spec.SchemaProps{
							Description: "UninstallStrategy defines how to proceed on uninstall when workloads (VirtualMachines, DataVolumes) still exist. BlockUninstallIfWorkloadsExist will prevent the CR from being removed when workloads still exist. BlockUninstallIfWorkloadsExist is the safest choice to protect your workloads from accidental data loss, so it's strongly advised. RemoveWorkloads will cause all the workloads to be cascading deleted on uninstallation. WARNING: please notice that RemoveWorkloads will cause your workloads to be deleted as soon as this CR will be, even accidentally, deleted. Please correctly consider the implications of this option before setting it. BlockUninstallIfWorkloadsExist is the default behaviour.",
							Default:     "BlockUninstallIfWorkloadsExist",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"logVerbosityConfig": {
						SchemaProps: spec.SchemaProps{
							Description: "LogVerbosityConfig configures the verbosity level of Kubevirt's different components. The higher the value - the higher the log verbosity.",
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.LogVerbosityConfiguration"),
						},
					},
					"tlsSecurityProfile": {
						SchemaProps: spec.SchemaProps{
							Description: "TLSSecurityProfile specifies the settings for TLS connections to be propagated to all kubevirt-hyperconverged components. If unset, the hyperconverged cluster operator will consume the value set on the APIServer CR on OCP/OKD or Intermediate if on vanilla k8s. Note that only Old, Intermediate and Custom profiles are currently supported, and the maximum available MinTLSVersions is VersionTLS12.",
							Ref:         ref("github.com/openshift/api/config/v1.TLSSecurityProfile"),
						},
					},
					"tektonPipelinesNamespace": {
						SchemaProps: spec.SchemaProps{
							Description: "TektonPipelinesNamespace defines namespace in which example pipelines will be deployed. If unset, then the default value is the operator namespace. Deprecated: This field is ignored.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"tektonTasksNamespace": {
						SchemaProps: spec.SchemaProps{
							Description: "TektonTasksNamespace defines namespace in which tekton tasks will be deployed. If unset, then the default value is the operator namespace. Deprecated: This field is ignored.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"kubeSecondaryDNSNameServerIP": {
						SchemaProps: spec.SchemaProps{
							Description: "KubeSecondaryDNSNameServerIP defines name server IP used by KubeSecondaryDNS",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"kubeMacPoolConfiguration": {
						SchemaProps: spec.SchemaProps{
							Description: "KubeMacPoolConfiguration holds kubemacpool MAC address range configuration.",
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.KubeMacPoolConfig"),
						},
					},
					"evictionStrategy": {
						SchemaProps: spec.SchemaProps{
							Description: "EvictionStrategy defines at the cluster level if the VirtualMachineInstance should be migrated instead of shut-off in case of a node drain. If the VirtualMachineInstance specific field is set it overrides the cluster level one. Allowed values: - `None` no eviction strategy at cluster level. - `LiveMigrate` migrate the VM on eviction; a not live migratable VM with no specific strategy will block the drain of the node util manually evicted. - `LiveMigrateIfPossible` migrate the VM on eviction if live migration is possible, otherwise directly evict. - `External` block the drain, track eviction and notify an external controller. Defaults to LiveMigrate with multiple worker nodes, None on single worker clusters.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"vmStateStorageClass": {
						SchemaProps: spec.SchemaProps{
							Description: "VMStateStorageClass is the name of the storage class to use for the PVCs created to preserve VM state, like TPM.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"virtualMachineOptions": {
						SchemaProps: spec.SchemaProps{
							Description: "VirtualMachineOptions holds the cluster level information regarding the virtual machine.",
							Default:     map[string]interface{}{"disableFreePageReporting": false, "disableSerialConsoleLog": false},
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.VirtualMachineOptions"),
						},
					},
					"commonBootImageNamespace": {
						SchemaProps: spec.SchemaProps{
							Description: "CommonBootImageNamespace override the default namespace of the common boot images, in order to hide them.\n\nIf not set, HCO won't set any namespace, letting SSP to use the default. If set, use the namespace to create the DataImportCronTemplates and the common image streams, with this namespace. This field is not set by default.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"ksmConfiguration": {
						SchemaProps: spec.SchemaProps{
							Description: "KSMConfiguration holds the information regarding the enabling the KSM in the nodes (if available).",
							Ref:         ref("kubevirt.io/api/core/v1.KSMConfiguration"),
						},
					},
					"networkBinding": {
						SchemaProps: spec.SchemaProps{
							Description: "NetworkBinding defines the network binding plugins. Those bindings can be used when defining virtual machine interfaces.",
							Type:        []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Allows: true,
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("kubevirt.io/api/core/v1.InterfaceBindingPlugin"),
									},
								},
							},
						},
					},
					"applicationAwareConfig": {
						SchemaProps: spec.SchemaProps{
							Description: "ApplicationAwareConfig set the AAQ configurations",
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.ApplicationAwareConfigurations"),
						},
					},
					"higherWorkloadDensity": {
						SchemaProps: spec.SchemaProps{
							Description: "HigherWorkloadDensity holds configuration aimed to increase virtual machine density",
							Default:     map[string]interface{}{"memoryOvercommitPercentage": 100},
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1.HigherWorkloadDensityConfiguration"),
						},
					},
					"enableCommonBootImageImport": {
						SchemaProps: spec.SchemaProps{
							Description: "Opt-in to automatic delivery/updates of the common data import cron templates. There are two sources for the data import cron templates: hard coded list of common templates, and custom (user defined) templates that can be added to the dataImportCronTemplates field. This field only controls the common templates. It is possible to use custom templates by adding them to the dataImportCronTemplates field.",
							Default:     true,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"instancetypeConfig": {
						SchemaProps: spec.SchemaProps{
							Description: "InstancetypeConfig holds the configuration of instance type related functionality within KubeVirt.",
							Ref:         ref("kubevirt.io/api/core/v1.InstancetypeConfiguration"),
						},
					},
					"CommonInstancetypesDeployment": {
						SchemaProps: spec.SchemaProps{
							Description: "CommonInstancetypesDeployment holds the configuration of common-instancetypes deployment within KubeVirt.",
							Ref:         ref("kubevirt.io/api/core/v1.CommonInstancetypesDeployment"),
						},
					},
					"deployVmConsoleProxy": {
						SchemaProps: spec.SchemaProps{
							Description: "deploy VM console proxy resources in SSP operator",
							Default:     false,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"enableApplicationAwareQuota": {
						SchemaProps: spec.SchemaProps{
							Description: "EnableApplicationAwareQuota if true, enables the Application Aware Quota feature",
							Default:     false,
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"liveUpdateConfiguration": {
						SchemaProps: spec.SchemaProps{
							Description: "LiveUpdateConfiguration holds the cluster configuration for live update of virtual machines - max cpu sockets, max guest memory and max hotplug ratio. This setting can affect VM CPU and memory settings.",
							Ref:         ref("kubevirt.io/api/core/v1.LiveUpdateConfiguration"),
						},
					},
					"hypervisors": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "atomic",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "Hypervisors specifies which hypervisor the cluster uses to run virtual machines. If empty or not set, KubeVirt defaults to KVM. Currently, only a single entry is supported. Allowed values for the hypervisor name are \"kvm\" and \"hyperv-direct\".",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("kubevirt.io/api/core/v1.HypervisorConfiguration"),
									},
								},
							},
						},
					},
					"roleAggregationStrategy": {
						SchemaProps: spec.SchemaProps{
							Description: "RoleAggregationStrategy controls whether KubeVirt RBAC cluster roles should be aggregated to the default Kubernetes roles (admin, edit, view). When set to \"AggregateToDefault\" or not specified, the aggregate-to-* labels are added to the cluster roles. When set to \"Manual\", the labels are not added, and roles will not be aggregated to the default roles.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/kubevirt/hyperconverged-cluster-operator/api/v1.HigherWorkloadDensityConfiguration", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1.HyperConvergedWorkloadUpdateStrategy", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1.LiveMigrationConfigurations", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1.PermittedHostDevices", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1.StorageImportConfig", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.ApplicationAwareConfigurations", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.DataImportCronTemplate", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedCertConfig", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedConfig", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedFeatureGates", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.HyperConvergedObsoleteCPUs", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.KubeMacPoolConfig", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.LogVerbosityConfiguration", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.MediatedDevicesConfiguration", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.OperandResourceRequirements", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.VirtualMachineOptions", "github.com/openshift/api/config/v1.TLSSecurityProfile", "kubevirt.io/api/core/v1.CommonInstancetypesDeployment", "kubevirt.io/api/core/v1.HypervisorConfiguration", "kubevirt.io/api/core/v1.InstancetypeConfiguration", "kubevirt.io/api/core/v1.InterfaceBindingPlugin", "kubevirt.io/api/core/v1.KSMConfiguration", "kubevirt.io/api/core/v1.LiveUpdateConfiguration", "kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1.FilesystemOverhead"},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_HyperConvergedStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HyperConvergedStatus defines the observed state of HyperConverged",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"conditions": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type":       "atomic",
								"x-kubernetes-patch-merge-key": "type",
								"x-kubernetes-patch-strategy":  "merge",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "Conditions describes the state of the HyperConverged resource.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("k8s.io/apimachinery/pkg/apis/meta/v1.Condition"),
									},
								},
							},
						},
					},
					"relatedObjects": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "atomic",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "RelatedObjects is a list of objects created and maintained by this operator. Object references will be added to this list after they have been created AND found in the cluster.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("k8s.io/api/core/v1.ObjectReference"),
									},
								},
							},
						},
					},
					"versions": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "atomic",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "Versions is a list of HCO component versions, as name/version pairs. The version with a name of \"operator\" is the HCO version itself, as described here: https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md#version",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.Version"),
									},
								},
							},
						},
					},
					"observedGeneration": {
						SchemaProps: spec.SchemaProps{
							Description: "ObservedGeneration reflects the HyperConverged resource generation. If the ObservedGeneration is less than the resource generation in metadata, the status is out of date",
							Type:        []string{"integer"},
							Format:      "int64",
						},
					},
					"dataImportSchedule": {
						SchemaProps: spec.SchemaProps{
							Description: "DataImportSchedule is the cron expression that is used in for the hard-coded data import cron templates. HCO generates the value of this field once and stored in the status field, so will survive restart.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"dataImportCronTemplates": {
						SchemaProps: spec.SchemaProps{
							Description: "DataImportCronTemplates is a list of the actual DataImportCronTemplates as HCO update in the SSP CR. The list contains both the common and the custom templates, including any modification done by HCO.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.DataImportCronTemplateStatus"),
									},
								},
							},
						},
					},
					"systemHealthStatus": {
						SchemaProps: spec.SchemaProps{
							Description: "SystemHealthStatus reflects the health of HCO and its secondary resources, based on the aggregated conditions.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"infrastructureHighlyAvailable": {
						SchemaProps: spec.SchemaProps{
							Description: "InfrastructureHighlyAvailable describes whether the cluster has only one worker node (false) or more (true).",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"nodeInfo": {
						SchemaProps: spec.SchemaProps{
							Description: "NodeInfo holds information about the cluster nodes",
							Default:     map[string]interface{}{},
							Ref:         ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.NodeInfoStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.DataImportCronTemplateStatus", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.NodeInfoStatus", "github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.Version", "k8s.io/api/core/v1.ObjectReference", "k8s.io/apimachinery/pkg/apis/meta/v1.Condition"},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_KubeMacPoolConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KubeMacPoolConfig defines kubemacpool MAC address range configuration",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"rangeStart": {
						SchemaProps: spec.SchemaProps{
							Description: "RangeStart defines the first MAC address in the kubemacpool range. The MAC address format should be AA:BB:CC:DD:EE:FF.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"rangeEnd": {
						SchemaProps: spec.SchemaProps{
							Description: "RangeEnd defines the last MAC address in the kubemacpool range. The MAC address format should be AA:BB:CC:DD:EE:FF.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_LogVerbosityConfiguration(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "LogVerbosityConfiguration configures log verbosity for different components",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kubevirt": {
						SchemaProps: spec.SchemaProps{
							Description: "Kubevirt is a struct that allows specifying the log verbosity level that controls the amount of information logged for each Kubevirt component.",
							Ref:         ref("kubevirt.io/api/core/v1.LogVerbosity"),
						},
					},
					"cdi": {
						SchemaProps: spec.SchemaProps{
							Description: "CDI indicates the log verbosity level that controls the amount of information logged for CDI components.",
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
				},
			},
		},
		Dependencies: []string{
			"kubevirt.io/api/core/v1.LogVerbosity"},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_MediatedDevicesConfiguration(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MediatedDevicesConfiguration holds information about MDEV types to be defined, if available",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"mediatedDeviceTypes": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "atomic",
							},
						},
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
					"mediatedDevicesTypes": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "atomic",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: please use mediatedDeviceTypes instead.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
					"nodeMediatedDeviceTypes": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "atomic",
							},
						},
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.NodeMediatedDeviceTypesConfig"),
									},
								},
							},
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/kubevirt/hyperconverged-cluster-operator/api/v1beta1.NodeMediatedDeviceTypesConfig"},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_NodeMediatedDeviceTypesConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NodeMediatedDeviceTypesConfig holds information about MDEV types to be defined in a specific node that matches the NodeSelector field.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"nodeSelector": {
						SchemaProps: spec.SchemaProps{
							Description: "NodeSelector is a selector which must be true for the vmi to fit on a node. Selector which must match a node's labels for the vmi to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/",
							Type:        []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Allows: true,
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
					"mediatedDeviceTypes": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "atomic",
							},
						},
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
					"mediatedDevicesTypes": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "atomic",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "Deprecated: please use mediatedDeviceTypes instead.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
				},
				Required: []string{"nodeSelector"},
			},
		},
	}
}

func schema_kubevirt_hyperconverged_cluster_operator_api_v1beta1_OperandResourceRequirements(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "OperandResourceRequirements is a list of resource requirements for the operand workloads pods",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"storageWorkloads": {
						SchemaProps: spec.SchemaProps{
							Description: "StorageWorkloads defines the resources requirements for storage workloads. It will propagate to the CDI custom resource",
							Ref:         ref("k8s.io/api/core/v1.ResourceRequirements"),
						},
					},
					"vmiCPUAllocationRatio": {
						SchemaProps: spec.SchemaProps{
							Description: "VmiCPUAllocationRatio defines, for each requested virtual CPU, how much physical CPU to request per VMI from the hosting node. The value is in fraction of a CPU thread (or core on non-hyperthreaded nodes). VMI POD CPU request = number of vCPUs * 1/vmiCPUAllocationRatio For example, a value of 1 means 1 physical CPU thread per VMI CPU thread. A value of 100 would be 1% of a physical thread allocated for each requested VMI thread. This option has no effect on VMIs that request dedicated CPUs. Defaults to 10",
							Default:     10,
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
					"autoCPULimitNamespaceLabelSelector": {
						SchemaProps: spec.SchemaProps{
							Description: "When set, AutoCPULimitNamespaceLabelSelector will set a CPU limit on virt-launcher for VMIs running inside namespaces that match the label selector. The CPU limit will equal the number of requested vCPUs. This setting does not apply to VMIs with dedicated CPUs.",
							Ref:         ref("k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelector"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/api/core/v1.ResourceRequirements", "k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelector"},
	}
}
