Schema: olm.semver
GenerateMajorChannels: true
GenerateMinorChannels: true
DefaultChannelTypePreference: minor
Candidate:
  Bundles:
    - Image: quay.io/kubevirt/hyperconverged-cluster-bundle:1.11.2
