
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-ssp-operator
  labels:
    operator.kubevirt.io: ""
roleRef:
  kind: ClusterRole
  name: kubevirt-ssp-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kubevirt-ssp-operator
  namespace: kubevirt-hyperconverged
