apiVersion: v1
data:
  default-network-interface: masquerade
  feature-gates: DataVolumes,SRIOV,LiveMigration,CPUManager,CPUNodeDiscovery,Snapshot,dummy,dummy
  machine-type: pc-q35-rhel8.3.0
  migrations: |-
    parallelMigrationsPerCluster: 3
    bandwidthPerMigration: 32Mi
    completionTimeoutPerGiB: 444
  selinuxLauncherType: virt_launcher.process
  smbios: |-
    Family: Red Hat
    Product: Container-native virtualization
    Manufacturer: Red Hat
    Sku: 2.6.2
    Version: 2.6.2
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-18T21:31:20Z"
  labels:
    app: kubevirt-hyperconverged
  name: kubevirt-config
  namespace: kubevirt-hyperconverged
  resourceVersion: "307882"
  uid: 660c2339-e981-496a-8527-7a621e82bcd3