FROM centos:8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177

RUN yum install -y centos-release-openshift-origin311 && \
    yum install -y origin-clients && \
    yum clean all && \
    rm -rf /var/cache/yum

COPY rotate-certs.sh /usr/bin/

RUN chmod +x /usr/bin/rotate-certs.sh

ENTRYPOINT [ "/usr/bin/rotate-certs.sh" ]
