---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: hyperconverged-cluster-operator-service-cert
  labels:
    app: hyperconverged-cluster-operator
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: hyperconverged-cluster
  name: hyperconverged-cluster-operator-metrics-service
spec:
  ports:
  - name: http-metrics
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    name: hyperconverged-cluster-operator
