- metadata:
    annotations:
      cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    name: fedora-image-cron
    namespace: golden-image-namespace
  spec:
    schedule: "* */1 * * *"
    template:
      spec:
        source:
          registry:
            url: docker://quay.io/kubevirt/fedora
    managedDataSource: fedora
- metadata:
    annotations:
      cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    name: centos8-image-cron
    namespace: golden-image-namespace
  spec:
    schedule: "* */1 * * *"
    template:
      spec:
        source:
          registry:
            url: docker://quay.io/kubevirt/centos8
    managedDataSource: centos8
