- metadata:
    name: no-annotations
    namespace: golden-image-namespace
  spec:
    schedule: "* */1 * * *"
    template:
      spec:
        source:
          registry:
            url: docker://quay.io/kubevirt/fedora
    managedDataSource: fedora
- metadata:
    annotations:
      cdi.kubevirt.io/storage.bind.immediate.requested: "false"
    name: from-file-annotation-false
    namespace: golden-image-namespace
  spec:
    schedule: "* */1 * * *"
    template:
      spec:
        source:
          registry:
            url: docker://quay.io/kubevirt/centos8
    managedDataSource: centos8
