name: Auto-Update Image Digests
on:
  schedule:
    - cron:  '0 4/4 * * *'
jobs:
  build:
    name: HCO Update Image Digests Job
    if: (github.repository == 'kubevirt/hyperconverged-cluster-operator')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15' # The Go version to download (if necessary) and use.

      - name: Get dependencies
        working-directory: tools/digester
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build the degister app
        working-directory: tools/digester
        run: go build -v .

      - name: Run the degister app to update the digests
        run: |
          ./automation/digester/update_images.sh
          if ! git diff --quiet --exit-code; then
            echo "CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Regenerage CSV
        if: ${{ env.CHANGED }}
        run: ./hack/build-manifests.sh

      - uses: peter-evans/create-pull-request@v3
        if: ${{ env.CHANGED }}
        with:
          token: ${{ secrets.HCO_BOT_TOKEN }}
          commit-message: |
            Update Image Digests

            Signed-off-by: HCO Bump Bot <noreply@github.com>
          committer: HCO Bump Bot <noreply@github.com>
          title: "Update Image Digests"
          body: |
            Update Image Digests
            Executed by HCO Update Image Digest Bot.
            ```release-note
            Update Image Digests
            ```
          assignees: tiraboschi,orenc1,nunnatsa
          reviewers: tiraboschi,orenc1,nunnatsa
          team-reviewers: owners, maintainers
          branch: update-image-digests
          delete-branch: true
