name: Override Bot
on:
  issue_comment:
    types: [created]
jobs:
  override:
    name: Check for redundant CI lanes for override
    if: (github.event.issue.pull_request != '') && (contains(github.event.comment.body, '/override-bot')) && (github.repository == 'kubevirt/hyperconverged-cluster-operator')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub
      - name: Override redundant lanes across open PRs
        run: python ./automation/override-bot/override-bot.py
        env:
          HCO_BOT_TOKEN: ${{ secrets.HCO_BOT_TOKEN }}
