# This is a basic workflow to help you get started with Actions

name: Sanity Checks

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Sanity Checks
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.19' # The Go version to download (if necessary) and use.

      - name: Do sanity checks
        run: make sanity

      - name: Verify we can actually build the operator
        run: make build

      - name: Unit tests
        run: make test

      - name: Prometheus alerts tests
        run: make prom-rules-verify

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverprofiles/cover.coverprofile

      - name: Verify the current manifests pass validation
        run: make container-build-validate-bundles

  linters:
    name: linter Checks
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        working-directory:
          - "."
          - tests

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: ${{matrix.working-directory}}/go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          skip-pkg-cache: true
          args: --timeout=5m --out-${NO_FUTURE}format line-number
          working-directory: ${{matrix.working-directory}}
