# This is a basic workflow to help you get started with Actions

name: Sanity Checks

# Controls when the action will run.
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Sanity Checks
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15' # The Go version to download (if necessary) and use.

      - name: Do sanity checks
        run: make sanity

      - name: Verify we can actually build the operator
        run: make build

      - name: Unit tests
        run: make test

      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=./coverprofiles/cover.coverprofile -service=github

      - name: Verify the current manifests pass validation
        run: make container-build-operator-courier
