name: Auto-Bump Component's Versions
on:
  schedule:
    - cron:  '0 5 * * *'
jobs:
  build:
    name: HCO Release Bump Job
    if: (github.repository == 'kubevirt/hyperconverged-cluster-operator')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15' # The Go version to download (if necessary) and use.
      - name: Check for new releases and update
        run: ./automation/release-bumper/release-bumper.sh
      - name: Set "UPDATED_COMPONENT" environment variable
        run: echo "::set-env name=UPDATED_COMPONENT::$(cat updated_component.txt)";
      - name: Set "UPDATED_VERSION" environment variable
        run: echo "::set-env name=UPDATED_VERSION::$(cat updated_version.txt)";
      - name: Remove temporary files
        run: rm -f updated_component.txt updated_version.txt
      - uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.HCO_BOT_TOKEN }}
          commit-message: |
            Bump ${{ env.UPDATED_COMPONENT }} to ${{ env.UPDATED_VERSION }}

            Signed-off-by: HCO Bump Bot <noreply@github.com>
          committer: HCO Bump Bot <noreply@github.com>
          title: "Bump ${{ env.UPDATED_COMPONENT }} to ${{ env.UPDATED_VERSION }}"
          body: |
            Bump ${{ env.UPDATED_COMPONENT }} to ${{ env.UPDATED_VERSION }}
            Executed by HCO Release-Bumper Bot.
            ```release-note
            Bump ${{ env.UPDATED_COMPONENT }} to ${{ env.UPDATED_VERSION }}
            ```
          assignees: tiraboschi,orenc1,nunnatsa
          reviewers: tiraboschi,orenc1,nunnatsa
          team-reviewers: owners, maintainers
          branch: bump_${{ env.UPDATED_COMPONENT }}_${{ env.UPDATED_VERSION }}
